### ISSUE TITLE
iex --werl unicode characters paste issue

### ISSUE THREAD

**Issue by vivek12895** [elixir-lang/elixir#10481] opened 2020-11-04 15:25 UTC
IEx 1.11.1 (compiled with Erlang/OTP 21)
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.1 (compiled with Erlang/OTP 21)

Stumbled upon this weird bug.
This happens in windows

When trying to paste the U+0939 character. iex crashes after the length exceeds some limit. 
Attaching a unlisted youtube video to show this bug in my system.

https://www.youtube.com/watch?v=dVXrsIze4No

**Comment by josevalim** [comment] 2020-11-04 15:27
Hi @vivek12895, please fill in the issues template with more information. The more information you can give, screenshots, and so on, the better. Thank you!

**Comment by vivek12895** [comment] 2020-11-04 15:28
> Hi @vivek12895, please fill in the issues template with more information. The more information you can give, screenshots, and so on, the better. Thank you!

sorry accidentally submitted before updating the info completely, reopen?

**Comment by josevalim** [comment] 2020-11-04 15:32
Thank you! Can you please run `werl` directly, so you open up the Erlang shell and see if you can reproduce the issue there? It seems to be an Erlang issue. :)

**Comment by josevalim** [comment] 2020-11-04 15:33
Also, does the bug happen with other Unicode characters? Such as "ハロー・ワールド" or only the ones you mentioned?

**Comment by vivek12895** [comment] 2020-11-04 15:33
i tried with three other characters , it worked fine, just with this one

**Comment by vivek12895** [comment] 2020-11-04 15:35
werl directly i tried with that character its working fine

**Comment by vivek12895** [comment] 2020-11-04 15:57
was just testing this a bit more even this crashes the iex --werl window
String.duplicate("ह", 1000)

**Comment by josevalim** [comment] 2020-11-04 16:04
Does it work on `iex` without the `--werl` flag? Note you will have to configure the the codepoint pages for your terminal.

**Comment by vivek12895** [comment] 2020-11-04 16:07
I tried the same thing in terminal without the --werl flag,  it works without crash.

**Comment by zengjiapei3000** [comment] 2020-12-10 10:59
hello man, I have a similar characters issue when using iex.

OS: win7
using environment: CMD
and "CMD property"-- "options" -- "current code page" this value is "`936`" (ANSI/OEM - simplified Chinese GBK),

    The issue had happened  in **iex**, firstly I open CMD, and typed "iex“ then CMD is going to **interactive mode**;
Then I typed h( ), some help information characters looks like  strange, here my all look in CMD:

`C:\Windows\System32>iex
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> h()

                                  IEx.Helpers

Welcome to Interactive Elixir. You are currently seeing the documentation for
the module `IEx.Helpers` which provides many helpers to make Elixir's shell
more joyful to work with.

This message was triggered by invoking the helper `h()`, usually referred to as
`h/0` (since it expects 0 arguments).

You can use the `h/1` function to invoke the documentation for any Elixir
module or function:

    iex> h(Enum)
    iex> h(Enum.map)
    iex> h(Enum.reverse/1)

You can also use the `i/1` function to introspect any value you have in the
shell:

    iex> i("hello")

There are many other helpers available, here are some examples:

  鈥?`b/1`            - prints callbacks info and docs for a given module
  鈥?`c/1`            - compiles a file
  鈥?`c/2`            - compiles a file and writes bytecode to the given
    path
  鈥?`cd/1`           - changes the current directory
  鈥?`clear/0`        - clears the screen
  鈥?`exports/1`      - shows all exports (functions + macros) in a module
  鈥?`flush/0`        - flushes all messages sent to the shell
  鈥?`h/0`            - prints this help message
  鈥?`h/1`            - prints help for the given module, function or macro
  鈥?`i/0`            - prints information about the last value
  鈥?`i/1`            - prints information about the given term
  鈥?`ls/0`           - lists the contents of the current directory
  鈥?`ls/1`           - lists the contents of the specified directory
  鈥?`open/1`         - opens the source for the given module or function in
    your editor
  鈥?`pid/1`          - creates a PID from a string
  鈥?`pid/3`          - creates a PID with the 3 integer arguments passed
  鈥?`port/1`         - creates a port from a string
  鈥?`port/2`         - creates a port with the 2 non-negative integers
    passed
  鈥?`ref/1`          - creates a reference from a string
  鈥?`ref/4`          - creates a reference with the 4 integer arguments
    passed
  鈥?`pwd/0`          - prints the current working directory
  鈥?`r/1`            - recompiles the given module's source file
  鈥?`recompile/0`    - recompiles the current project
  鈥?`runtime_info/0` - prints runtime info (versions, memory usage, stats)
  鈥?`v/0`            - retrieves the last value from the history
  鈥?`v/1`            - retrieves the nth value from the history

Help for all of those functions can be consulted directly from the command line
using the `h/1` helper itself. Try:

    iex> h(v/0)

To list all IEx helpers available, which is effectively all exports (functions
and macros) in the `IEx.Helpers` module:

    iex> exports(IEx.Helpers)

This module also includes helpers for debugging purposes, see `IEx.break!/4`
for more information.

To learn more about IEx as a whole, type `h(IEx)`.`


I can take any information what do you need if I can find. But maybe I will late to reply nearly 10 hours, I'm sorry, but I will **### certainly reply**~  :smiley:

**Comment by josevalim** [comment] 2020-12-10 11:17
Hi @zengjiapei3000. That's a separate issue, I will push a fix for it soon.

**Comment by josevalim** [comment] 2020-12-21 14:11
I have reproduced this and I have verified it has been fixed on more recent Erlang versions. I tested on 23.2 and it worked. Thank you for the report.

**Closed by josevalim** 2020-12-21 14:11 UTC
Labels: App:IEx, Note:Windows
