### ISSUE TITLE
Strange problem when compiling an Elixir project (an Erlang depdendency)

### ISSUE THREAD

**Issue by Zac-Garby** [elixir-lang/elixir#7343] opened 2018-02-13 16:31 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20, Elixir 1.6.1
* Operating system: macOS 10.13.4 Beta

### Current behaviour

I'm trying to compile [UltraDark](https://github.com/UltraDark/UltraDark). I cloned the repository and typed these commands:

```bash
mix local.rebar
rm -rf _build deps
mix deps.get
mix
```

The first 4 commands work, but when I type the last one it does a load of checks (as expected) then gives me a couple of errors:

```
config.status: creating Makefile
dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/bin/gawk
  Reason: image not found
sed: stdout: Broken pipe
./config.status: line 1226: 50903 Done(1)                 eval sed \"\$ac_sed_extra\" "$ac_file_inputs"
     50904 Abort trap: 6           | $AWK -f "$tmp/subs.awk" > $tmp/out
config.status: error: could not create Makefile
===> Hook for compile failed!

** (Mix) Could not compile dependency :eleveldb, "/Users/zacg/.mix/rebar3 bare compile --paths "/Users/zacg/Desktop/UltraDark/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile eleveldb", update it with "mix deps.update eleveldb" or clean it with "mix deps.clean eleveldb"
```

I've tried for hours to:

 - Install libmpfr 4 (about three times now)
 - Load libmpfr on gawk (`otool` and `install_name_tool`)
 - Reinstall elixir, Erlang, rebar, and libmpfr (and all their dependencies)
 - Spoken to the UltraDark people

But nothing seems to work. Any suggestions?

### Expected behaviour

It should compile properly and create two apps for me.

**Comment by OvermindDL1** [comment] 2018-02-13 16:42
Does `/usr/local/opt/mpfr/lib/libmpfr.4.dylib` exist would be the first question I think?  If not then what `/usr/local/opt/mpfr/lib/libmpfr.*.dylib` do exist?

**Comment by Zac-Garby** [comment] 2018-02-13 16:45
`libmpfr.6.dylib` exists, but not `libmpfr.4.dylib`

**Comment by josevalim** [comment] 2018-02-13 17:09
My suggestion is to try to clone the eleveldb dependency and compile it directly. If that still fails, you will at least be closer to the root cause of the problem.

**Comment by Zac-Garby** [comment] 2018-02-13 18:52
@josevalim I cloned eleveldb and `rebar compile`'d it, which resulted in the same exact error.

**Comment by OvermindDL1** [comment] 2018-02-13 18:58
If you have 6 but not 4, then you probably have some mpfr.4 dependency that you could install I'd imagine?

**Comment by OvermindDL1** [comment] 2018-02-13 18:59
Ah, as a matter of fact that is how it is on my OS (not mac), I have to install `libmpfr4` to get version 4, or I install `libmpfr` (no 4) to get the latest.

**Comment by Zac-Garby** [comment] 2018-02-13 19:06
The weird thing is, homebrew says I have version 4 installed, but the dylib is called `libmpfr.6.dylib`. Also, no version 6 even exists - version 4.0.1 was released just a few days ago

**Comment by OvermindDL1** [comment] 2018-02-13 19:52
That... sounds like a bug?  o.O?

**Comment by josevalim** [comment] 2018-02-14 11:50
Since you can reproduce it even without Elixir, it is not an Elixir bug, so I will go ahead and close this. However if you have further questions please post them here and we will follow up. :)

**Closed by josevalim** 2018-02-14 11:50 UTC

**Comment by Zac-Garby** [comment] 2018-02-14 11:52
@josevalim sure, I managed to fix it now anyway. In case anyone else has the same problem, I `brew reinstall`'d `gawk` and used `asdf` to manage my elixir/erlang versions instead of homebrew. thanks for the help though :)
