### ISSUE TITLE
`mix local.hex` improve message when replacing existing archive

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#4497] opened 2016-04-08 07:49 UTC
```sh
$ mix local.hex
Found existing archive(s): hex-0.11.3.ez.
Are you sure you want to replace them? [Yn]
```

only after I hit <kbd>Y</kbd>, I know what I'm gonna replace that archive with

```sh
* creating ~/.mix/archives/hex-0.11.5.ez
```

I think a message like this will help:
`Are you sure you want to replace them with hex-0.11.5.ez? [Yn]`

Also mix consider them a more than one archive, when it mentions "them".

**Comment by eksperimental** [comment] 2016-04-08 07:49
I will submit a PR

**Comment by ericmj** [comment] 2016-04-08 13:16
This is my output when running the task:

```
~/code/hex λ mix local.hex
Found existing archive: /Users/ericmj/.mix/archives/hex.ez.
Are you sure you want to replace it with "https://hexpmrepo.global.ssl.fastly.net/installs/1.2.0/hex-0.11.5.ez"? [Yn]
```

Did you run master? There has been changes around this since the last stable release.

**Comment by dmitryU** [comment] 2016-04-09 08:47
I have the same problem. Running on Windows:
```
$ mix local.hex
Found existing archive(s): hex-0.11.3.ez.
Are you sure you want to replace them? [Yn] y
* creating c:/Users/maestro/.mix/archives/hex-0.11.5.ez
```

**Comment by ericmj** [comment] 2016-04-09 08:48
@dmitryU Are you running on master?

**Comment by dmitryU** [comment] 2016-04-09 08:53
I'm using version 1.2.3. Just downloaded elixir-master:
```
$ ../elixir-master/bin/mix local.hex
Found existing archive(s): hex-0.11.3.ez.
Are you sure you want to replace them? [Yn] y
* creating c:/Users/maestro/.mix/archives/hex-0.11.5.ez
$ ../elixir-master/bin/mix --version
Mix 1.2.4
```

**Comment by ericmj** [comment] 2016-04-09 08:54
If you aren't using elixir master it's expected to not get changes that are only in master :).

Suggesting we close this unless there are other changes needed?

**Comment by dmitryU** [comment] 2016-04-09 08:59
I'm tested it on the master, see my previous comment :)

**Comment by ericmj** [comment] 2016-04-09 09:00
But mix reported version 1.2.4, master is on 1.3.0-dev.

**Comment by josevalim** [comment] 2016-04-09 09:11
I can confirm it is fixed in master:

```
$ mix local.hex
Found existing archive: /Users/jose/.mix/archives/hex-0.11.4.ez.
Are you sure you want to replace it with "https://hexpmrepo.global.ssl.fastly.net/installs/1.2.0/hex-0.11.5.ez"? [Yn]
```

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Closed by josevalim** 2016-04-09 09:11 UTC

**Comment by eksperimental** [comment] 2016-04-11 20:06
sorry for the false alarm I didn't run it from master

there's one caveat,
```shell
$ mix local.hex
Found existing archive: ~/.mix/archives/hex-0.11.5.ez.
Are you sure you want to replace it with "https://hexpmrepo.global.ssl.fastly.net/installs/1.2.0/hex-0.11.5.ez"? [Yn] 
```

My local hex was up to date, still offered to install it.
Woudln't it be better to check for an sha1 hash and avoid downloading an exact copy of what we already have in the system

**Comment by ericmj** [comment] 2016-04-11 20:07
How would we hash the archive without downloading it?

**Comment by eksperimental** [comment] 2016-04-11 20:12
I haven't looked at the code, so I have no idea of the internals, but when you request the url of the latest archive, wouldn't it be possible to obtain its hash from the server?

**Comment by ericmj** [comment] 2016-04-11 20:14
Yes, we already do that because we sign that hash, but it seems like an unnecessary optimization? We already do one request to the server, I don't think it matters much if we do one more.

**Comment by eksperimental** [comment] 2016-04-11 20:20
I find it unnecessary to ask the user if he wants to download something that's already there.
it's not so much about the requests but about the bandwidth on both sides (specially on the user side).

Actually I think it would be best not to open up the dialog at all, and finish straight away if we could manage to get the hash.

**Comment by ericmj** [comment] 2016-04-11 20:24
If you want to work on it please send PR but I don't find it's high priority at this time.

**Comment by eksperimental** [comment] 2016-04-11 20:27
Sure! I will give it a try.
Will contact you if I have questions regarding the server side

thank you

**Comment by ericmj** [comment] 2016-04-11 20:32
No problem, thank you.

I believe everything should already be there for you in the csv file with hashes but feel free to ask any questions.

**Comment by eksperimental** [comment] 2016-11-08 23:57
@ericmj I am trying to take a stab at it.
I just realized that  `~./mix/` doesn't hold any .ez file. it's all uncompressed, so it's hard to tell whether the files are the same, eventhough they have the same name.
So should we trust what's inside mix, and do not install it, and say: "It's already installed. run the command with `--force` if you want to overwrite it.
I don't know if there are situations where that will not be the proper way of dealing with it.
ideas?

**Comment by ericmj** [comment] 2016-11-09 13:23
In that case I don't think it's worth it, the hash check is a very minor optimization anyway.
