### ISSUE TITLE
Application hex exited on M1 cross-build docker build

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#11747] opened 2022-04-08 10:15 UTC
### Environment

* Elixir & Erlang/OTP versions: 1.13.4 / 24.3.3
* Operating system: debian (Docker linux/amd64 cross-build from Apple M1)

### Current behavior

I'm trying to do a cross build on my Mac, which has an M1 processor, and I'm getting the following error when `mix deps.get` runs inside the docker container:

```
#19 3.144 08:20:14.694 [notice] Application hex exited: exited in: Hex.Application.start(:normal, [])
#19 3.144     ** (EXIT) an exception was raised:
#19 3.144         ** (MatchError) no match of right hand side value: {:map_reduce_ok, 3}
#19 3.144             (elixir 1.13.4) src/elixir_def.erl:102: :elixir_def.store_definition/5
#19 3.144             (mix 1.13.4) lib/mix/scm.ex:130: Mix.SCM.available/0
#19 3.144             (hex 1.0.1) lib/hex/application.ex:9: Hex.Application.start/2
#19 3.144             (kernel 8.1.2) application_master.erl:293: :application_master.start_it_old/4
```

This issue is already mentioned in the fly.io community: https://community.fly.io/t/error-when-running-fly-deploy-for-generated-phoenix-app-after-fly-launch/3665.

Does someone have any idea why this is happening?

**Comment by josevalim** [comment] 2022-04-08 15:26
Nothing comes to mind. The stacktrace itself doesn't make sense. We would need a way to reproduce the issue that rules out it being an Elixir specific issue, given that changing other parts of the stack seems to address it.

**Comment by dvic** [comment] 2022-04-15 07:00
I tried replicating it with a separate repo but I can't because I'm getting 

```
#0 0.667 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#0 0.677 Segmentation fa
```

So it seems like a deeper problem in Docker.

**Comment by whatyouhide** [comment] 2022-04-16 06:24
@dvic what Docker image are you using? I recently switched to an M1 Mac as well and have had trouble here and there depending on the image. The official images and the ones built by the Hex team have been working, for example.

**Comment by dvic** [comment] 2022-04-16 10:59
Yeah in this instance I'm on the `hexpm/elixir` images. I'll see if I can try it with other base images. But I can't reproduce it with a clean phoenix project using the same images (because I'm getting the segmentation fault).

**Comment by josevalim** [comment] 2022-04-26 12:24
I will close this as I don't believe this is an Elixir specific issue. Elixir does not ship with native code, so it cannot be affected by architecture. The issue is most likely upstream. Thanks!

**Closed by josevalim** 2022-04-26 12:24 UTC
Labels: Note:Needs more info
