### ISSUE TITLE
ExUnit diff of two lists is confusing when head is missing

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#6768] opened 2017-10-09 22:18 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

* Operating system: 

OS X 10.12.6

### Current behavior

Given this failing test, where the difference between two lists is a missing element at the end:

``` elixir
  test "diffing date lists with a missing date at end" do
    dates_1 = [~D[2017-06-01], ~D[2017-06-02], ~D[2017-06-03]]
    dates_2 = [~D[2017-06-01], ~D[2017-06-02]                ]

    assert dates_1 == dates_2
  end
```

...it produces a really nice, clear diff:

![screen shot 2017-10-09 at 3 14 12 pm](https://user-images.githubusercontent.com/49391/31360718-8d0592ae-ad04-11e7-8d40-5971d16bbb6a.png)

...but given this failing test, where the first element is missing:

``` elixir
  test "diffing date lists with a missing date at start" do
    dates_1 = [~D[2017-06-01], ~D[2017-06-02], ~D[2017-06-03]]
    dates_2 = [                ~D[2017-06-02], ~D[2017-06-03]]

    assert dates_1 == dates_2
  end
```

...it produces a confusing diff:

![screen shot 2017-10-09 at 3 15 28 pm](https://user-images.githubusercontent.com/49391/31360766-be167fc0-ad04-11e7-8796-680e7d5c6ef2.png)

### Expected behavior

It would be great if the diff for the latter case was more like the first one, showing that the difference is the missing first element, instead of individually diffing the list elements position by position.  Not sure how feasible that is, but figured I'd ask :).

**Comment by josevalim** [comment] 2017-10-09 22:20
Assigned to @lexmag as he is the one who will know if this is possible or not.

**Comment by devonestes** [comment] 2018-05-06 10:57
Hey, so since this has been open for a while, I figured I'd take a swing at this one. I've played around a bit with this, and do y'all think it would be cool if the output looked like this:
![format_script](https://user-images.githubusercontent.com/8422484/39672504-705abbd6-512b-11e8-9d0f-15e09797e076.png)

And here's what Myron's original example would look like:
![date_script](https://user-images.githubusercontent.com/8422484/39672558-7ac6a30e-512c-11e8-8aed-345c23e29d83.png)


The colors are right, but there isn't any additional padding in the front to make the similar elements line up as they do when there's a missing element at the end of the list. I have a feeling that without that vertical alignment this might not be as helpful as one might want, but maybe this is still better than the existing behavior?

Based on my quick exploration this does seem totally possible, although I don't have an actual implementation yet. While I'm waiting for feedback I'm going to take a swing at an implementation, but feel free to let me know how this looks and if there are better ways y'all can think of to make this clearer for users.

**Comment by lexmag** [comment] 2018-05-06 11:15
Hey @devonestes, yeah, I believe your output looks correct.
To get such output we should apply the difference algorithm backward—in some cases (like this issue) Myers algorithm produces better script when applied backward.

**Comment by josevalim** [comment] 2018-05-06 13:05
The problem is how to choose if we should apply it backwards or not? If we
always apply it backwards, then the other case in the issue will  perform
worse.

A simple heuristic would be to see if the first or last elements are equal
and decide accordingly. But if someone has already researched and published
that would be better.

Note the Meyer algorithm does have version that performs from the front and
back at the same time. It is also more performant albeit more complex.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lexmag** [comment] 2018-05-06 13:11
@josevalim I thought about the following approach:
Considering that today we run the diffing in a `Task`, we can run backwards in another `Task`.
Then we weight each script afterwards: less `:del` and/or `:ins` with more `:eq` wins.

**Comment by devonestes** [comment] 2018-05-06 13:59
So it seems like y'all want to support the full reverse Myers algorithm for all data types then, and not just handling this single case of lists with a missing head? If so, I'll close #7651 and take a swing at the reverse Myers. I like the comparison of the diff scripts to see which gives a better fit, but if I can find the version that does forwards and backwards at the same time, I might try and do that.

**Comment by lexmag** [comment] 2018-05-06 14:26
I think choosing where to start is not that easy.
@josevalim can you elaborate on "based on the equality"?

@devonestes I believe we should not target only one very particular case.

**Comment by devonestes** [comment] 2018-05-06 14:35
@lexmag I think that's what José was getting at when he said
> A simple heuristic would be to see if the first or last elements are equal
and decide accordingly

So, if the first elements aren't equal and the last elements are equal, then it might make sense to use the reverse algorithm. You could I guess see how many consecutive elements are equal going forwards and backwards, and based on that go with the normal or reverse algorithm. So, something like:

| List1  | List2 | Forward Num | Backwards Num | Direction
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| [1,2,3]  | [2,3]  | 0 | 2 | Backward
| [1,2,3]  | [1,2]  | 2 | 0 | Forward
| [1,2,3,4,5] | [1,2,3,5] | 3 | 1 | Forward
| [1,2,3,4,5] | [1,3,4,5] | 1 | 3 | Backward

**Comment by lexmag** [comment] 2018-05-06 14:41
@devonestes Unfortunately this way is too simple and will make other cases to be worse. We should also consider lists of lists for example.

**Comment by josevalim** [comment] 2018-05-06 14:55
Can you give examples of where it would be worse? It is the best heuristic
so far in terms of implementation and simplicity?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lexmag** [comment] 2018-05-06 15:05
@josevalim In a case when we have "front equals" < "back equals" we would to do the diffing backwards, however the middle part could give better script if diffed forward. Checking front and back for equality is not enough to tell which way is better.

**Comment by josevalim** [comment] 2018-05-06 15:12
Why don’t we check then both back and front for equality, take the equal
ones out from the diffing, diff the rest and then prepend and append
accordingly? It is semantically correct and it will work on all cases.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lexmag** [comment] 2018-05-06 16:58
Semantically it could be considered correct, but that way won't be always giving most precise and longest script.

**Comment by devonestes** [comment] 2018-05-06 18:28
So, the good news is, if I'm reading [this paper](http://www.xmailserver.org/diff2.pdf) correctly, it looks like the "middle snake" refinement that he describes starting around pages 11/12 means there's an existing algorithm to essentially gets the best of both directions in one pass. Seems like this would eliminate the need to decide when to go forwards or backwards, which would be nice 😉 

It is pretty tricky, though, and my CS kung-fu isn't super strong, so it might take me a little longer to really digest and understand how to implement it. But, it's a promising lead!

**Comment by lexmag** [comment] 2018-05-06 18:40
The "middle snake" refinement is not completely about finding the best script, but rather time and space optimization. In some case running forward and backward separately would give better result.
But when we implement it we obtain possibility to run the diffing backwards; means we can compare the "forward+backward" and the "middle snake" approaches.

**Comment by josevalim** [comment] 2018-05-06 19:11
> Semantically it could be considered correct, but that way won't be always (maybe even too frequently) giving most precise and longest :eq script.

Good point. It is not optimal. @lexmag but we can always remove from the front, right? Since that's the first thing the algorithm does anyway.

**Comment by lexmag** [comment] 2018-05-07 13:37
@josevalim removing from the front affects the output script. The algorithm can produce a script where first matching element won't be considered as `:eq`, and it will be the longest snake.

**Comment by josevalim** [comment] 2018-05-07 13:50
@lexmag so the only property I can think of that would be semantically correct would be for us to remove all of the shared elements in the front, remove all of the shared elements in the back and then check one of the lists has to be empty. In this case, it is guaranteed we found the shortest path and it would fix the issues at hand.

I am not really a fan of traversing both the front and the back in a task given the cost in terms of performance and complexity.

**Comment by lexmag** [comment] 2018-05-07 14:03
Yeah, with a check for empty leftover list we should get the correct and best script.
Also, I think most common occurrences of this problem will be solved.

> I am not really a fan of traversing both the front and the back in a task given the cost in terms of performance and complexity.

I thought, given that running the diffing (test failing) is not something every test run expected to do, perhaps it is fine—we already timebox script building.

**Comment by josevalim** [comment] 2018-05-09 08:38
@lexmag beautiful!

So @devonestes, we have reached a conclusion in case you would still like to give this a try. The idea is to remove the common elements at the front and the common elements at the back. If one of the lists ends up empty as we do so, then we can generate a manual diff, otherwise we fallback to the existing mechanism.

**Comment by devonestes** [comment] 2018-05-09 18:10
Oh, cool! So my original attempt at this wasn't that far off, then 😉 

I'll update that branch to be more general in this way, taking the matching elements from the front and back of the list, and then diffing the remainder in the normal way we're doing it now, then putting those three pieces back together again. Once I get the gist of that done for lists I'll push it back up to make sure I'm really understanding what y'all want here, and then I'll tackle this for the other data types as well.

**Comment by josevalim** [comment] 2018-05-09 19:09
> Oh, cool! So my original attempt at this wasn't that far off, then 😉

Exactly, we just generalized it a bit more!

> then diffing the remainder in the normal way we're doing it now

Just to clarify: one of the lists has to be empty, so we won't perform any diffing per-se. Depending on the side, all of the entries remaining will be removals or additions.

**Closed** 2018-05-10 18:59 UTC
Labels: App:ExUnit, Kind:Enhancement, Level:Advanced, Note:Discussion
