### ISSUE TITLE
warning in Mix test: redefining module GitRepo

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3911] opened 2015-10-24 11:27 UTC
```sh
Randomized with seed 64945
==> mix (exunit)
...............................................................................................................................................................................................................................................lib/git_repo.ex:2: warning: redefining module GitRepo
...................................
```

the offending line is  https://github.com/elixir-lang/elixir/blob/c859e49199bb24190656e6d3acb6cf35fe70e8bb/lib/mix/test/test_helper.exs#L194

should we clean "fixtures/git_repo" on setup_all ?

**Comment by ericmj** [comment] 2015-10-24 15:33
Cleaning fixtures/git_repo unfortunately won't work. To fix this we need to purge `GitRepo` after the test that is loaded is finished, finding the offending test can be quite tricky.

**Comment by eksperimental** [comment] 2015-10-25 09:08
I was trying to see if I could solve this, and the warning is not happening anymore.
anyway to replicate this by forcing the giving key in the original example?

**Comment by ericmj** [comment] 2015-10-25 10:23
It's hard to reproduce because it's a timing issue depending on the order
tests run.

One way to possibly reproduce is to wait until it happens again and record
the seed.

On Sunday, 25 October 2015, eksperimental <notifications@github.com> wrote:

> I was trying to see if I could solve this, and the warning is not
> happening anymore.
> anyway to replicate this by forcing the giving key in the original example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3911#issuecomment-150904226>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by eksperimental** [comment] 2015-10-25 10:57
Yes, the seed was 64945. How can i reproduce it again?

**Comment by ericmj** [comment] 2015-10-25 10:59
Try mix test --seed 64945.

On Sunday, 25 October 2015, eksperimental <notifications@github.com> wrote:

> Yes, the seed was 64945. How can i reproduce it again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3911#issuecomment-150912142>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by josevalim** [comment] 2015-10-25 23:54
We can't use mix to test mix so you will need to open up the test_helper.exs for mix and directly add `[seed: 64945]` to the exunit.configure call.

**Comment by eksperimental** [comment] 2015-10-25 23:58
thank you @josevalim I will try that then

**Comment by lexmag** [comment] 2015-12-28 01:02
Closed via e0fd6dee99d81b72d81fd858d1c387b7760f1090.

**Closed by lexmag** 2015-12-28 01:02 UTC
Labels: App:Mix, Kind:Chore

**Comment by lexmag** [comment] 2015-12-28 01:21
It was pretty straightforward. :smile:
Most of the Mix tests use `MixTest.Case` template, thus we can add:
```elixir
before = Enum.map(:code.all_loaded, &elem(&1, 0))
on_exit(fn ->
  diff = Enum.map(:code.all_loaded, &elem(&1, 0)) -- before
  if diff != [], do: IO.inspect(diff)
end)
```
and it produces one suspicious entry: `[GitRepo, Collectable, :fprof]`.

**Comment by eksperimental** [comment] 2016-02-12 22:44
thank you @lexmag for looking after this, as I never had the time to do it.
once more trick learned
