### ISSUE TITLE
IEx default_prompt configuration compatibility with IEx history

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#6448] opened 2017-08-11 13:46 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  
```
Erlang/OTP 20 [erts-9.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```
* Operating system: Docker container `elixir:1.5.1-alpine`

### Current behavior

I have configured IEx to print the current `MIX_ENV` in the prompt to provide visual feedback when opening consoles in different environments. 

Everything works fine, except for the IEx history. When I use the up/down cursors to move through the history, the `iex(` prefix gets stacked.

Here is an example:

``` 
iex(dev,9)>
iex(iex(iex(dev,10)>
iex(iex(iex(iex(iex(iex(iex(iex(iex(iex(iex(iex(iex(iex(dev,11)>
```

Here is my `.iex.exs` configuration:

```elixir
env = case System.get_env("MIX_ENV") || "dev" do
  "prod" -> IO.ANSI.red() <> "prod" <> IO.ANSI.reset()
  "dev" -> IO.ANSI.green() <> "dev" <> IO.ANSI.reset()
  "test" -> IO.ANSI.green() <> "test" <> IO.ANSI.reset()
  mix_env -> IO.ANSI.yellow() <> mix_env <> IO.ANSI.reset()
end

IEx.configure(
  default_prompt: "%prefix(#{env},%counter)>",
  alive_prompt: "%prefix(#{env},%node,%counter)>"
)
```

### Expected behavior

I would expect the prompt to not accumulate `iex(` prefixes.

**Comment by ggcampinho** [comment] 2017-08-16 11:07
I tried to debug this and here are my thoughts. If I understood correctly, the history in the shell is managed in the Erlang shell, not IEx. I could reproduce the same problem only changing the [Erlang prompt](https://github.com/erlang/otp/blob/dd9e39dc2b97e30c03b24a00eb757be7d2c2bdc2/lib/kernel/src/group.erl#L858) to `"\e[31mprod\e[0m "`. a strange case happens with smaller strings, my first attempt was with `"\e[31mfoo\e[0m "`  and it works correctly.

I think the error is in the [function `del_chars` of the Erlang driver](https://github.com/erlang/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L990), apparently, it doesn't handle well the ANSI colors. I'm trying to confirm this, but I wanted to share what I found because I think this issue is complex.

An example of the behaviour in Erlang:
```
Erlang/OTP 21 [DEVELOPMENT] [erts-9.0.2] [source-589b8769a] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0.2  (abort with ^G)
prod a.
a
prod b.
b
prod c.
c
ppppprod  
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C%
```

**Comment by ggcampinho** [comment] 2017-08-23 09:24
The fix was merged to Erlang, I don't know if we need to do something here or we can just close the ticket

**Comment by josevalim** [comment] 2017-08-23 09:37
Beautiful, thank you for fixing it and for the follow up! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Closed** 2017-08-23 09:37 UTC
Labels: App:IEx, Kind:Bug, Level:Intermediate

**Comment by fertapric** [comment] 2017-08-23 09:39
Thanks @ggcampinho! ❤️
