### ISSUE TITLE
Recent elixir_dispatch changes causing DB timeouts, only on 1.9+ and OTP 21+ running in a CI

### ISSUE THREAD

**Issue by Kuret** [elixir-lang/elixir#9324] opened 2019-09-02 11:10 UTC
When trying to upgrade our application to 1.9.1 we were hit with database timeouts which only seems to occur when running tests in CircleCI. Running the same commands in the same docker images as our Circle setup uses locally works fine.

We were able to solve it by increasing the `:queue_target` and `:queue_interval` options for our Ecto repo, but this doesn't solve the root of the problem.

I was finally able to track the problem to a specific change: https://github.com/elixir-lang/elixir/commit/59fcce0b927b926d9eb5a91851300e43dead21bd#diff-791e156e023ca9c24d2833639dc989b6R297 but I do not really understand what is happening here, and why it seems to be only affecting CircleCI in combination with 1.9+ and OTP 21+.

When I revert the `erlang:module_loaded` parts to the `code:is_loaded` implementation everything works fine again.

We were using some OTP21 features when our app ran fine with 1.8 and the docker images for Elixir 1.9.1 also use OTP22 so it is currently not easy to downgrade our setup to 1.9.1-OTP20.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.9+ with OTP-21+
* Operating system: Elixir docker 1.9.1 running in CircleCI

### Current behavior

```** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 716ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information```

Happens at random in tests, and only in CircleCI in combination with Elixir 1.9.1 with OTP21 or 22.

### Expected behavior

I would assume the `module_loaded` change affected performance in this situation somehow? Should there be a version check?

**Comment by josevalim** [comment] 2019-09-02 12:57
We use `erlang:module_loaded` precisely because it is faster and it doesn't talk to the code server, which can be a bottleneck. So my current theory is that the change impacted performance positively, which puts more pressure on the pool (in the same way that removing a bottleneck often puts the pressure in the next bottleneck). So unless there a clear evidence that `erlang:module_loaded` is detrimental to performance, increasing the pool timeout is the way to go here.

**Comment by josevalim** [comment] 2019-09-10 14:36
I will go ahead and close this. If you have more evidence that things are actually slower and we can effectively reproduce them, then please let us know. Thanks!

**Closed by josevalim** 2019-09-10 14:36 UTC
Labels: Note:Needs more info
