### ISSUE TITLE
Requiring the current module doesn't give a proper error.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9494] opened 2019-11-06 01:17 UTC
```
$ iex
Erlang/OTP 22 [erts-10.5.2] [source] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule A do
...(1)>   require A
...(1)> end
** (CompileError) iex:2: you are trying to use the module A which is currently being defined.

This may happen if you accidentally override the module you want to use. For example:

    defmodule MyApp do
      defmodule Supervisor do
        use Supervisor
      end
    end

In the example above, the new Supervisor conflicts with Elixir's Supervisor. This may be fixed by using the fully qualified name in the definition:

    defmodule MyApp.Supervisor do
      use Supervisor
    end
```

**Comment by josevalim** [comment] 2019-11-06 07:38
Hi @eksperimental, please do your best to provide more information in your error reports. We have an issue template and filling it accordingly **helps us a lot**. For example, i consider the error message to be correct, as you would have run into the issue described above if you renamed your module from A to Supervisor. But since you haven't provided enough information, I don't really know what you mean. So I will close this issue due to the lack of information.

**Closed by josevalim** 2019-11-06 07:38 UTC

**Comment by eksperimental** [comment] 2019-11-06 13:35
Sorry, but you can see I started IEx with no arguments, and I just punched in the code you see, nothing else. and the Elixir/Erlang versions are provided there.

The example talks about two modules `Supervisor` and `MyApp.Supervisor`.
Here's just one module named `A`.
I define `A` and I require `A` from the same module that is being defined.

**Comment by josevalim** [comment] 2019-11-06 13:53
It is not about the versions in this case, but describing what you saw and
what you expected.

The nesting is an example of the error, but it also happens without
nesting. Just name your module Supervisor instead of A and you will see it.

The message also says “may”, to indicate it is a possibility but not
necessarily the root cause.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment] 2019-11-06 15:00
If I rename `A` with `Supervisor` I get a totally different message, which is a warning and it compiles. Since this error happens when it is being defined for the first time.

```iex
iex(1)> defmodule Supervisor do
...(1)>   require Supervisor
...(1)> end
warning: redefining module Supervisor (current version loaded from bin/../lib/elixir/ebin/Elixir.Supervisor.beam)
  iex:1
```

Anyway, reading carefully the CompileError message is correct and not misleading _per se_.
but when it is followed by the example is what makes is misleading IMO.
I think is the use of the word "use" when it says " you are trying to use the module A which is currently being defined."
And in the examples given the root of the cause is caused by the `use/2` macro calling the conflicting module.

My suggestion would be to give an error like this:

> ** (CompileError) iex:2: you are trying to **require** the module A which is currently being defined.

or using the word "load" which may not necessarily mean `require/2`, and it may imply `use/import/require` macros 
> ** (CompileError) iex:2: you are trying to **load** the module A which is currently being defined.

And since this error is less like to happen, I would leave for the end of the message a hint of what could also be wrong

```
Alternatively, it could happen because you are accidentally requiring the same module that is being defined:

    defmodule YourApp do
      require YourApp
    end
```
