### ISSUE TITLE
Difficult to diagnose compilation error in Phoenix app

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#8153] opened 2018-08-30 13:11 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Operating system: OSX 13.6
* Phoenix 1.3.4

### Current behavior
I'm not sure if this is Elixir or Phoenix error.
When compiling Phoenix app (umbrella) with plug `MyPlug` in `my_plug.ex` used in router
```
defmodle MyPlug do
  def init(opts) ...
  def call(conn, opts) ...
  defp my_func(%MyStruct{}) ...
end
```
when `MyStruct` is not aliased I get random errors like
```
== Compilation error in file lib/my_app/views/my_view.ex ==
** (CompileError) lib/my_app/views/my_view.ex:3: module MyApp.Router.Helpers is not loaded and could not be found
    expanding macro: MyApp.__using__/1
    lib/my_app/views/my_view.ex:3: MyApp.MyView (module)
    (elixir) expanding macro: Kernel.use/2
    lib/my_app/views/my_view.ex:3: MyApp.MyView (module)
```
By random I mean every time the view that fails to compile is different
### Expected behavior

Proper error message indicating that `MyStruct` in `my_plug.ex:{line}` is not defined

**Comment by josevalim** [comment] 2018-08-30 13:18
Can you please provide an application that reproduces the error? That will make sure we can reproduce it effectively and efficiently and that we are working on the same bug as the one reported. Thanks!

**Comment by lukaszsamson** [comment] 2018-08-30 13:31
I was able to reproduce it by adding the broken plug to freshly generated phoenix app
https://github.com/lukaszsamson/phoenix_compile_error_reproduction

**Comment by josevalim** [comment] 2018-08-30 21:41
Unfortunately this is very hard to fix because the compiler can't see the relationship between `MyApp.Router.Helpers` and ``MyApp.Router`. So once it seems compilation can't proceed, its best hint is to try to complete compilation of some of those view files hoping one of them will include the missing struct.

Phoenix v1.4 will bypass this issue altogether by no longer importing the Helpers file, and aliasing it instead. Other than that, I don't think there is a proper fix for the compiler. So I will mark this as won't fix. Thanks!

PS: this had a better error on v1.6 because Elixir v1.6 wouldd take the wrong decision and attempt to compile the wrong file, causing codebases that should compile to not compile.

**Closed by josevalim** 2018-08-30 21:41 UTC
Labels: App:Elixir (compiler), Level:Advanced, Note:Needs more info
