### ISSUE TITLE
Mix complains about a false dependency conflict after upgrading to 1.2

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/elixir#4191] opened 2016-01-12 20:22 UTC
Basically top-level project says it doesn't care about a version (dependency is specified there only for dialyxir's sake) while a library have a stricter constraint. Furthermore this happens during `deps.get` with existing `mix.lock` — in general I didn't expect any checks to be performed at this stage.

```
Dependencies have diverged:
* plug (Hex package)
  the dependency plug

  > In mix.exs:
    {:plug, ">= 0.0.0", [hex: :plug, manager: :mix]}

  does not match the requirement specified

  > In deps/oauth2/mix.exs:
    {:plug, "~> 1.0", [optional: false, hex: :plug]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by josevalim** [comment] 2016-01-12 21:14
@sumerman good catch. Can you provide a simple mix.exs file that reproduces the error? Thank you. :)

**Comment by josevalim** [comment] 2016-01-12 21:14
@ericmj / @lexmag let's solve this before shipping 1.2.1.

**Comment by sumerman** [comment] 2016-01-13 09:42
@josevalim It's surprisingly hard to reproduce: on a different machine with the same repo it gives me a different set of conflicting deps, and "minimal example" I'm trying to comp up with just works. Could you point me to the part of Mix code where resolution happens, so I will have a better idea what's going on.

**Comment by josevalim** [comment] 2016-01-13 10:04
@sumerman if it works on another machine it can be two reasons:

1. it has different elixir/hex versions
2. this bug only shows up when upgrading code. so if you have recently upgraded oauth2 or plug, maybe having the old lock with the mix.exs file is enough to reproduce it

**Comment by sumerman** [comment] 2016-01-13 10:10
@josevalim not quite: the repo with the problem just gives me a different conflicts set. But a brand-new repo works.

1. Versions are the same
2. I'm deleting `deps` folders before running `deps.get`

Removing `_build` folder helped, though. I will check with another machine tonight.

**Comment by josevalim** [comment] 2016-01-13 10:12
Ok, perfect. I will hold the release until then, if we still can't reproduce it, no issues. It can always be fixed later on.

**Comment by ericmj** [comment] 2016-01-13 15:46
Make sure you have the same `mix.lock` file when reproducing. This error happens when you have a fetched and compiled dependency A and add a new dep B that depends on A but the version requirement B set on A does not match the version you have of A.

Example:
You have dep A with version 1.0.0. You and dep B that depends on A with the requirement "~> 2.0", the new requirement does not match on 1.0.0 and you get this error.

You could get this error due to a bug in Mix but regardless the error message needs to be improved.

**Comment by sumerman** [comment] 2016-01-13 15:58
I've been preserving the lock file all the time and of course will preserve
it for further edperiments.

On Wednesday, 13 January 2016, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> Make sure you have the same mix.lock file when reproducing. This error
> happens when you have a fetched and compiled dependency A and add a new dep
> B that depends on A but the version requirement B set on A does not match
> the version you have of A.
>
> Example:
> You have dep A with version 1.0.0. You and dep B that depends on A with
> the requirement "~> 2.0", the new requirement does not match on 1.0.0 and
> you get this error.
>
> You could get this error due to a bug in Mix but regardless the error
> message needs to be improved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4191#issuecomment-171337296>
> .
>


-- 
Sincerely,
(Mr.) Valery Meleshkin

**Comment by sumerman** [comment] 2016-01-13 21:31
`_build` folder removal helped on the other machine as well

**Comment by josevalim** [comment] 2016-01-13 21:41
Perfect. We will improve the error message for upcoming releases anyway. Thank you!

**Comment by josevalim** [comment] 2016-01-14 18:33
This is related to #4162 btw.

**Comment by josevalim** [comment] 2016-05-22 21:51
Closing as part of #4162.

**Closed by josevalim** 2016-05-22 21:51 UTC
Labels: App:Mix, Kind:Bug, Level:Advanced
