### ISSUE TITLE
test/elixir/system_test.exs:72: anonymous fn/1 in SystemTest.test cmd/1/1

### ISSUE THREAD

**Issue by matwey** [elixir-lang/elixir#3314] opened 2015-05-09 10:26 UTC
Hi,

I am facing the following issue, building elixir 1.0.4 with erlang 17.5

```
[  212s] + make test
[  212s] ==> elixir (compile)
[  217s] ==> elixir (eunit)
[  219s]   All 196 tests passed.
[  219s] 
[  219s] ==> elixir (exunit)
[  250s] ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[  250s] 
[  250s]   1) test cmd/1 (SystemTest)
[  250s]      test/elixir/system_test.exs:62
[  250s]      Expected to catch error, got nothing
[  250s]      stacktrace:
[  250s]        test/elixir/system_test.exs:72: anonymous fn/1 in SystemTest.test cmd/1/1
[  250s]        (elixir) lib/file.ex:1061: File.cd!/2
[  250s]        test/elixir/system_test.exs:69
[  250s] 
[  250s] ............................
[  250s] 
[  250s] Finished in 30.5 seconds (22.1s on load, 8.3s on tests)
[  250s] 1803 tests, 1 failures
[  250s] 
[  250s] Randomized with seed 259933
[  250s] make: *** [test_stdlib] Error 1
```

How could I provide additional information to resolve this?

**Comment by ericmj** [comment] 2015-05-09 11:40
You can probably ignore that error. The test calls the `echo2` executable expecting it to be missing. You probably have an executable in your `PATH` named `echo2` causing the test to fail. The test has been removed on master.

**Comment by nurugger07** [comment] 2015-05-12 01:28
I don't have `echo2` in my path and received the error above on v1.0.4.

I also pulled master and I'm receiving a similar error on this [test](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/system_test.exs#L72)

I can look into it and report back or fix

**Comment by nurugger07** [comment] 2015-05-12 02:12
I've fixed the failing test and submitted a pull request https://github.com/elixir-lang/elixir/pull/3321

**Comment by eksperimental** [comment] 2015-05-12 09:19
Just to avoid the chance of somone having a command named echo2, wouldnt it be bette to call the command "echo-" + md5 hash of current timestamp?

**Comment by josevalim** [comment] 2015-05-12 09:24
Well, since he doesn't have echo2 in his path, there is something else happening. We need to figure out what it is. :)

**Comment by nurugger07** [comment] 2015-05-12 12:00
I don't have `echo2` in my path. I stepped through the test code in iex to verify the point of failure. Once the assertion happens in the function supplied to `File.cd!/2`, then "echo2" is available and the "hello" message is returned. Are you not seeing this locally?

**Comment by eksperimental** [comment] 2015-05-12 12:07
@josevalim i know, but that was something that was asked to the OP of this bug to check. If we use echo2, system that have this command in their path wont be able to pass this test.

**Comment by ericmj** [comment] 2015-05-12 12:11
@nurugger07 `System.cmd/2` is not supposed to run executables in the current directory unless giving an absolute path to it, which the test tries to verify. Your PR changes the test so it doesn't test the intended behaviour. Can you show your $PATH?

**Comment by nurugger07** [comment] 2015-05-12 12:21
@ericmj then the issue may be within `System.cmd/2` because I'm able to do just that. I'll look at the code & verify again but I'm still curious as to why this is working for others. One other thing to note is the Travis CI results. In a single erlang version the suite is failing on a completely unrelated test.

**Comment by oneeman** [comment] 2015-05-12 12:23
This is tangential, but perhaps worth mentioning.

When I was working on the tests for https://github.com/elixir-lang/elixir/pull/3294 and trying to get them to use parallel compile directly rather than through the CLI, the part which I said at the time (in irc) that I couldn't get to work was due to problems which seem reminiscent of this.  In the test I was writing, I was bizarrely getting an exception when not trying to catch one, but when trying to catch it would tell me the expected error didn't get thrown.  I couldn't make head or tails of it.

**Comment by nurugger07** [comment] 2015-05-12 12:38
@oneeman as I stated though, it seems the `File.cmd/2` is calling the command successfully once in the directory as well as with the absolute path.

@ericmj the test is actually unclear as to what the expectation is. I would assume that if the `System.cmd/2` found the command in the current directory that it would execute it.

**Comment by oneeman** [comment] 2015-05-12 12:50
@nurugger07 Sorry, I didn't mean to imply this is exactly the same, just that they seem possibly related.  

One thought, though: when you say it's being executed when given a relative path, are you basing that on the fact that the exception that's expected doesn't get thrown and caught in the test, or have you also verified it separately (e.g. just trying to run something in the current directory from iex using a relative path)?  The only reason I ask is that there may be a problem with catching the exits or something related, that could confound things.

**Comment by oneeman** [comment] 2015-05-12 12:51
Oops, nevermind, reread your earlier comments and saw you did get the output.  Sorry again!

**Comment by nurugger07** [comment] 2015-05-12 13:15
@oneeman no worries. After confirming that "echo2" wasn't in my path, mimicking the action by running the code as a user would in iex was my next step. I'm thinking that `System.cmd/2` isn't behaving as expected. I'll look into the source later today and confirm.

**Comment by josevalim** [comment] 2015-05-16 08:17
Fixed in master, thank you!

**Closed by josevalim** 2015-05-16 08:17 UTC

**Comment by matwey** [comment] 2015-07-03 22:10
The issue is still present in 1.0.5
