### ISSUE TITLE
Elixir 1.15.0 breaks command line on Windows

### ISSUE THREAD

**Issue by Intelliractive** [elixir-lang/elixir#12715] opened 2023-06-26 11:13 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

### Operating system

Windows 10 latest

### Current behavior

Regardless of the command line app (Command Prompt or Windows Terminal) or type (Cmd or Powershell), it breaks when Elixir starts. It even breaks other apps like Clipdiary(clipboard manager)
---
Examples:
- Backspace starts to delete whole words

 https://github.com/elixir-lang/elixir/assets/98094811/3331f59b-879f-4786-9423-793909a3ec2a

- Y/N confirmations are broken

https://github.com/elixir-lang/elixir/assets/98094811/cf679dfa-61eb-4eb9-b59d-7e7b2427882c

- Broken Clipdiary

https://github.com/elixir-lang/elixir/assets/98094811/9d2c687e-5ce1-4745-9a7e-ee1a6791b3da

- Broken command prompt after running `elixir -v`

https://github.com/elixir-lang/elixir/assets/98094811/385e725e-84ff-4b02-bfae-edeed7fa37a7

### Expected behavior

Obviously, various confirmations should work normally and command line behaviour shouldn't break
Expected Clipdiary behaviour: 

https://github.com/elixir-lang/elixir/assets/98094811/262695c4-1afb-4787-9bca-84ba13933dbc

**Comment by josevalim** [comment] 2023-06-26 11:26
Can you reproduce this by running `erl`? My suspicion is that it is an Erlang issue.

**Comment by Intelliractive** [comment] 2023-06-26 11:53
> Can you reproduce this by running `erl`? My suspicion is that it is an Erlang issue.

No. Unfortunately, it is not.

**Comment by josevalim** [comment] 2023-06-26 12:47
@Intelliractive and if you do `erl -noshell -s erlang halt`, does it break it? Or `erl -noshell` only.

**Comment by baskint** [comment] 2023-06-26 14:23
fwiw, had a few issues on Windows with Elixir 1.15.0, but removed previous Erlang and reinstalled Erlang 26.0.1 along with a fresh installation of Elixir, got everything working on this Windows 10 instance.

![image](https://github.com/elixir-lang/elixir/assets/211107/16e894dd-520e-4aa6-bc37-66d351bc32ad)

**Comment by Intelliractive** [comment] 2023-06-28 09:24
> @Intelliractive and if you do `erl -noshell -s erlang halt`, does it break it? Or `erl -noshell` only.

Good Morning, @josevalim! Yes, it does. You were right! I think the problem was born when they decided to stop shipping the graphical shell app

**Comment by Intelliractive** [comment] 2023-06-28 09:28
> fwiw, had a few issues on Windows with Elixir 1.15.0, but removed previous Erlang and reinstalled Erlang 26.0.1 along with a fresh installation of Elixir, got everything working on this Windows 10 instance.
> 
> ![image](https://user-images.githubusercontent.com/211107/248834893-16e894dd-520e-4aa6-bc37-66d351bc32ad.png)

Hello! I reinstalled Erlang while installing Elixir since it's not shipped out of the box, but I have the problem

**Comment by josevalim** [comment] 2023-06-28 09:30
Hi @Intelliractive, I cannot reproduce this issue on my WIndows VM. I assume there is something else at play in your machine which we need to isolate. Perhaps clipdiary or another app is messing with the shell/terminal?

**Comment by Intelliractive** [comment] 2023-06-28 09:58
So, I discovered that Erlang 26 was a big release that discontinued the GUI shell and introduced further actions on `Ctrl-C`. It also utilises a different directory (at least on my machine), so I eventually had both of them. Erlang 26 made a mess!😤 It would work now, I suppose, but I switched to Elixir on OTP 25, sorry for not testing

**Comment by Intelliractive** [comment] 2023-06-28 10:06
Color support in terminal may also be the problem

**Comment by Intelliractive** [comment] 2023-09-02 12:37
Good day! I decided to finally upgrade to `Elixir 1.15.5 on OTP 26` (since that Erlang GUI app became irrelevant) and I experience the issue again, but in a slightly different manner: I am totally sure that the further actions dialog appearing after `^c` is the problem root. I also guess that is linked with color codes in Windows command line.

![изображение](https://github.com/elixir-lang/elixir/assets/98094811/99975054-1a72-4439-a1b8-fd61efe05cb4)

| ![изображение](https://github.com/elixir-lang/elixir/assets/98094811/e0a66b5b-2778-4113-b775-207960f66d13) |
| :--: |
| *Everything was OK here, such a specific flaw!* |

![изображение](https://github.com/elixir-lang/elixir/assets/98094811/c9c760ff-16fb-4f97-9f50-2a55b5b9274f)
 
---

Should I create an issue at Erlang repo?

**Comment by josevalim** [comment] 2023-09-02 12:58
Can you reproduce it only with `erl`? If so, yes, please report it upstream!

**Comment by josevalim** [comment] 2023-09-02 13:02
When you report it upstream, remember to include how you installed Erlang and how are you starting the shell (cmd, powershell, etc). You also mentioned you have an app for managing clip board, please confirm if it reproduces the issue even when uninstalled. :) feel free to ask if you have questions.

**Comment by josevalim** [comment] 2023-09-10 11:15
Hi @Intelliractive, I will go ahead and close this, as it is an Erlang issue. If you find anything that may point to Elixir or you need help filing upstream, please let me know. Thank you. :)

**Closed by josevalim** 2023-09-10 11:15 UTC
Labels: Kind:Bug, App:IEx, Note:Needs more info

**Comment by user20230119** [comment] 2023-10-26 11:13
Issue reports on erlang https://github.com/erlang/otp/issues/7621
