### ISSUE TITLE
Formatter doesn't work under windows

### ISSUE THREAD

**Issue by fklement** [elixir-lang/elixir#7625] opened 2018-04-30 05:44 UTC
### Environment

* Erlang/OTP 20 [erts-9.3] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:10]
   Elixir 1.6.4 (compiled with OTP 19)
* Operating system: Windows 10 Pro

### Current behavior

In our project the `.formatter.exs` looks like this:  
```
[
  inputs: [
    "lib/**/*.{ex,exs}",
    "mix.exs",
    "test/support/**/*.{ex,exs}"
  ],
  locals_without_parens: [
    # Kernel
    inspect: 1,
    inspect: 2,

    # Phoenix
    plug: 1,
    plug: 2,
    action_fallback: 1,
    render: 2,
    render: 3,
    render: 4,
    redirect: 2,
    resources: 2,
    resources: 3,
    resources: 4,
    get: 4,
    post: 4,
    delete: 4,
    forward: 4,
    get: 3,
    post: 3,
    delete: 3,
    forward: 3,
    get: 2,
    post: 2,
    delete: 2,
    forward: 2,

    # Ecto Schema
    field: 2,
    field: 3,
    belongs_to: 2,
    belongs_to: 3,
    has_one: 2,
    has_one: 3,
    has_many: 2,
    has_many: 3,
    embeds_one: 2,
    embeds_one: 3,
    embeds_many: 2,
    embeds_many: 3,
    many_to_many: 2,
    many_to_many: 3,
    add: 3,

    # Ecto Query
    from: 2
  ]
]
```

The problem is, that the list get's correctly returned but it does not affect the formatted code when i hit save.  

### Expected behavior
For example:
`embeds_one :rates, Type.Rates` becomes `embeds_one(:rates, Types.Rates)` which should not be.  

My colleague is using MacOS and here works everyting fine.

**Comment by josevalim** [comment] 2018-04-30 06:08
Does it work if you run “mix format” from your project root? I.e. from the
same directory where .formatter.exs is placed?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fklement** [comment] 2018-04-30 06:32
I tried. But nothing happens at all.

**Comment by josevalim** [comment] 2018-04-30 08:51
It doesn’t happen because the code is already formatted? If you add “foo 1,
2” to a file that is listed, does it add parens?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment] 2018-04-30 08:55
If that still does not work, can you please provide an application that
reproduces the issue? We know for certain that it works on windows so we
need more information to effectively reproduce this. Thank you!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment] 2018-05-05 11:50
Ping!

**Comment by josevalim** [comment] 2018-05-06 21:53
I will go ahead and close this for now. We will gladly reopen once we have a mechanism to reproduce the issue.

**Closed** 2018-05-06 21:53 UTC
Labels: Note:Formatter, Note:Needs more info

**Comment by princemaple** [comment] 2018-08-24 07:03
I have some problem that might be related

```
~\my_proj [master ↑3 +8 ~8 -0 !] [Aug-24 16:58:04]
> mix format .\lib\app\flow\update_stock_check.ex
** (Mix) Could not find a file to format. The files/patterns given to command line did not point to any existing file. Got: [".\\lib\\app\\flow\\update_stock_check.ex"]
~\my_proj [master ↑3 +8 ~8 -0 !] [Aug-24 16:58:29]
> mix format ./lib/app/flow/update_stock_check.ex
~\my_proj [master ↑3 +8 ~8 -0 !] [Aug-24 16:58:50]
> elixir --version
Erlang/OTP 21 [erts-10.0.1] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.7.1 (compiled with Erlang/OTP 19)
```

Notice how the windows `\` separated path does not work.
After changing them to `/` it worked

**Comment by princemaple** [comment] 2018-08-24 07:14
Looks like it's caused by `Path.wildcard` returning empty list for the windows path
```elixir
iex(2)> Path.wildcard(".\\lib\\app\\flow\\update_stock_check.ex")
[]
```
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/format.ex#L334

**Comment by princemaple** [comment] 2018-08-24 07:36
Thanks for the quick reply, @josevalim . I'm on PowerShell & OTP21, it's installed via Chocolatey. I don't have an easy way to install an OTP20 version... I normally dev in docker so it's not a problem for me. I found out about this because I use a build system in Sublime to call formatter, which calls the Elixir on Windows, not the Elixir in docker.

**Comment by princemaple** [comment] 2018-08-26 06:27
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/path.ex#L650
@josevalim Looks like this is documented:

> Directory separators must always be written as /, even on Windows.

at http://erlang.org/doc/man/filelib.html

**Comment by princemaple** [comment] 2018-08-29 07:48
@josevalim I guess `Path.wildcard` behaves as expected, according to the above. And `mix format` probably needs to do some unification before passing paths to Path.wildcard..?
