### ISSUE TITLE
`Mix.install` fails with `MatchError` when specifying a `path` dependency with some other dependency

### ISSUE THREAD

**Issue by 0x009922** [elixir-lang/elixir#13627] opened 2024-06-01 00:52 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.3 (compiled with Erlang/OTP 26)

### Operating system

macOS Sonoma 14.5

### Current behavior

Steps to reproduce:

1. Create new Mix project: `mix new sample_project`
2. Add a Hex dependency to it, e.g. `{:nimble_parsec, "~> 1.1.1"}`
3. Run `Mix.install` using this project as a path dependency. For example, in IEx session:

```elixir
Mix.install([{:sample_project, path: "./sample_project"}])
```

You can also add this dependency in any other way (from other project, or from Livebook, as in my case) - it doesn't matter until it has `path`.

It fails with the following error:

```
Resolving Hex dependencies...
** (MatchError) no match of right hand side value: :error
    (hex 2.1.1) lib/hex/solver/package_lister.ex:47: anonymous fn/4 in Hex.Solver.PackageLister.dependencies_as_incompatibilities/4
    (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (hex 2.1.1) lib/hex/solver/package_lister.ex:46: Hex.Solver.PackageLister.dependencies_as_incompatibilities/4
    (hex 2.1.1) lib/hex/solver/solver.ex:123: Hex.Solver.Solver.choose_package_version/1
    (hex 2.1.1) lib/hex/solver/solver.ex:25: Hex.Solver.Solver.solve/2
    (hex 2.1.1) lib/hex/solver.ex:64: Hex.Solver.run/5
    (hex 2.1.1) lib/hex/remote_converger.ex:69: Hex.RemoteConverger.run_solver/5
    iex:1: (file)
```

I noticed that this error doesn't occur if `sample_project` doesn't have any dependencies.

Some context: initially tried to use a local `path` dependency in my Livebook, but faced this cryptic error =(

**upd:** got the same error (in Livebook) when I added same dependency via remote `git` url.

### Expected behavior

_At least_ expected to get an error with an explanation of what I did wrong and an actionable way to fix it.

Ideally, expected this thing to just work (as it often does in Elixir!)

**Comment by ericmj** [comment] 2024-06-01 07:33
When I try to reproduce this on Elixir 1.16.2 I get no errors and when I try on Elixir 1.17.0-dev I get:

```
Unchecked dependencies for environment dev:
* nimble_parsec (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix.Error) Can't continue due to errors on dependencies
    (mix 1.17.0-dev) lib/mix.ex:588: Mix.raise/2
    (mix 1.17.0-dev) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.17.0-dev) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.0-dev) lib/mix.ex:947: anonymous fn/5 in Mix.install/2
    (elixir 1.17.0-dev) lib/file.ex:1665: File.cd!/2
    (mix 1.17.0-dev) lib/mix.ex:911: Mix.install/2
    (elixir 1.17.0-dev) src/elixir.erl:385: :elixir.eval_external_handler/3
    (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
    (elixir 1.17.0-dev) src/elixir.erl:363: :elixir.eval_forms/4
    (elixir 1.17.0-dev) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
    (iex 1.17.0-dev) lib/iex/evaluator.ex:332: IEx.Evaluator.eval_and_inspect/3
    (iex 1.17.0-dev) lib/iex/evaluator.ex:306: IEx.Evaluator.eval_and_inspect_parsed/3
    (iex 1.17.0-dev) lib/iex/evaluator.ex:295: IEx.Evaluator.parse_eval_inspect/4
    (iex 1.17.0-dev) lib/iex/evaluator.ex:187: IEx.Evaluator.loop/1
```

@0x009922 I have not been able to reproduce your error. Can you provide a mix project and the full list of commands you run to recreate it?

**Comment by josevalim** [comment] 2024-06-01 08:31
I get another error:

```
iex(1)> Mix.install([{:sample_project, path: "./sample_project"}])
Resolving Hex dependencies...
Resolution completed in 0.011s
Because your app depends on nimble_parsec ~> 1.1.1 which doesn't match any versions, version solving failed.
** (Mix.Error) Hex dependency resolution failed
    (mix 1.18.0-dev) lib/mix.ex:588: Mix.raise/2
    (mix 1.18.0-dev) lib/mix/dep/converger.ex:133: Mix.Dep.Converger.all/4
    (mix 1.18.0-dev) lib/mix/dep/converger.ex:89: Mix.Dep.Converger.converge/4
    (mix 1.18.0-dev) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.18.0-dev) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.18.0-dev) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.0-dev) lib/mix.ex:938: anonymous fn/5 in Mix.install/2
    iex:1: (file)
```

Using 1.17.0-dev and latest Hex. This is the same error I get on on Hex 2.0.7 too.

**Comment by 0x009922** [comment] 2024-06-02 00:28
Ahh, my bad... I used `nimble_options` `v1.1.1` package, not `nimble_parsec`. Anyway, it doesn't matter what the package is - it failed with `jason` too, for example. 

Will create a reproduction repo.

**Comment by 0x009922** [comment] 2024-06-02 01:08
Here it is: https://github.com/0x009922/elixir-issue-13627-repro

Reproduced the same error while running `Mix.install` both from IEx and Livebook.

**Comment by josevalim** [comment] 2024-06-02 13:05
Thank you. I could not reproduce it even with the repo :( using same Elixir and Hex versions, it just works here. Let's see if @ericmj has better luck.

**Comment by 0x009922** [comment] 2024-06-03 21:23
Tried to reproduce it in a Docker container - it works there as well.

I guess I'll have to debug what's going on my machine.

**Comment by ericmj** [comment] 2024-06-03 21:51
When I got the `** (Mix.Error) Can't continue due to errors on dependencies` error I changed the dependency definition `{:nimble_parsec, "~> 1.1.1"}` to one that matches available nimble_parsec versions: `{:nimble_parsec, ">= 0.0.0"}`.

**Comment by ericmj** [comment] 2024-06-03 21:58
@0x009922 It is possible you have a corrupted cache or using a private repo that returns bad data. You can try to run `mv ~/.hex/cache.ets ~/.hex/cache-backup.ets` to get a fresh cache.

**Comment by 0x009922** [comment] 2024-06-04 07:16
> You can try to run `mv ~/.hex/cache.ets ~/.hex/cache-backup.ets` to get a fresh cache.

It resolved the issue. Thank you! I wonder why `:force` option didn't affect this (which says that "if true, removes install cache").

Also, I guess this issue is more related to https://github.com/hexpm/hex repo rather than to this one.

**Comment by josevalim** [comment] 2024-06-10 14:38
@ericmj can you please move this one to hex repo and then close it? :) Thank you!

**Comment by ericmj** [comment] 2024-06-11 15:26
> It resolved the issue. Thank you! I wonder why :force option didn't affect this (which says that "if true, removes install cache").

It's referring to the mix install cache which is different from the hex cache.

Can you send `~/.hex/cache-backup.ets` to support@hex.pm so we can figure out what the corruption was?

> can you please move this one to hex repo and then close it? :) Thank you!

I can't move it to another organization unfortunately so just closing here.

**Closed by ericmj** 2024-06-11 15:26 UTC
Labels: App:Mix, Note:Needs more info, Kind:Dependencies
