### ISSUE TITLE
Elixir v1.14 charch with message: init terminating in do_boot

### ISSUE THREAD

**Issue by sysmat** [elixir-lang/elixir#12153] opened 2022-09-25 13:18 UTC
### Elixir and Erlang/OTP versions
- using elixir-websetup.exe
- `elixir --version`  output is:
`{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1190}]},{init,do_boot,3,[{file,"init.erl"},{line,888}]}]}}
`

### Operating system

windows 10

### Current behavior

`{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1190}]},{init,do_boot,3,[{file,"init.erl"},{line,888}]}]}}
`

### Expected behavior

- to print version to console
- Elixir 1.13.4 (compiled with Erlang/OTP 22) works fine

**Comment by josevalim** [comment] 2022-09-25 16:06
What is your `erl` version? This is caused by running Erlang/OTP 25 with 1.13.4. You need to either use OTP 24 if on 1.13. Or update to 1.14 and use OTP 25.

**Comment by sysmat** [comment] 2022-09-25 16:27
- I install OTP 25.1
- Eshell V12.0
- update to 1.14 but still get error:

```
❯ elixir --version
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1190}]},{init,do_boot,3,[{file,"init.erl"},{line,888}]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done

```

**Comment by josevalim** [comment] 2022-09-25 18:34
Thank you!

There is definitely something wrong happening. It indeed cannot find the elixir files. Can you please go to your Elixir installation and make sure there is a file at `lib/elixir/ebin/elixir.beam`?

**Comment by sysmat** [comment] 2022-09-26 07:27
@josevalim in `C:\Program Files (x86)\Elixir\lib` I don't have **ebin** folder

**Comment by BE-Webdesign** [comment] 2022-10-02 22:49
I am experiencing the same issue as well. Tried doing fresh installs multiple times, same result.

**Comment by BE-Webdesign** [comment] 2022-10-08 13:23
For me which is probably separate from what @sysmat  is experiencing, it was a local issue with Git Bash, using regular command prompt elixir worked just fine.

**Comment by josevalim** [comment] 2022-10-18 10:08
> I install OTP 25.1
> Eshell V12.0

This is inaccurate. Eshell v12.0 means Erlang/OTP 24. Can you please run `erl`? Which versions it reports?

In any case, I have submitted a PR to Erlang/OTP to improve errors in cases like this.

**Comment by josevalim** [comment] 2022-10-18 10:09
> I install OTP 25.1
> Eshell V12.0

Those are conflicting versions. :) Eshell v12.0 means Erlang/OTP 24. @sysmat, can you please run `erl`? Which versions it reports?

In any case, I have submitted a PR to Erlang/OTP to improve errors in cases like this.

**Comment by josevalim** [comment] 2022-10-25 20:22
Closing for now. In any case, I have sent a PR to Erlang/OTP for a clearer error message.

**Closed by josevalim** 2022-10-25 20:22 UTC
Labels: Note:Needs more info

**Comment by RoboZoom** [comment] 2022-11-29 13:38
I don't know if this warrants a new issue, or just a comment here, but I thought it worth noting that I ran into this same issue today.  It appears as if the official Windows binary installer mismatches erlang/elixir versions by default.  When running a fresh install on windows, the installer will use Erlang/OTP v24, and Elixir version 1.14.2

**Comment by hotbrainy** [comment] 2022-12-13 15:16
I've installed Erlang OPT 24 and EShell v12.2 and Elixir 14.2.
but got same error.
`{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1191}]},{init,do_boot,3,[{file,"init.erl"},{line,889}]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done`
how can I solve this issue?

**Comment by josevalim** [comment] 2022-12-13 15:36
This means you are using an Elixir version that was compiled for a more recent Erlang version. You need to download Elixir for an earlier version or update to Erlang/OTP 25.

**Comment by lorenzosinisi** [comment] 2022-12-30 10:21
Hi @josevalim do you think it make sense to add a check + a warning so that rather than `"init terminating in do_boot"` we could output something like "you are using an Elixir version that was compiled for a more recent Erlang version. You need to download Elixir for an earlier version or update to Erlang/OTP 25." ?

**Comment by josevalim** [comment] 2022-12-30 10:29
This check has been added to Erlang. From OTP 26 onwards.

**Comment by emekauser** [comment] 2023-05-16 10:44
I had this issue, I had this issue on Windows. i had to remove the previous erlang (24) version that was not removed and it worked

**Comment by charlenopires** [comment] 2023-06-12 01:17
I encountered the same issue using Ubuntu, WSL inside Windows, and solved it with 'make clean test' in the root directory of Elixir.
