### ISSUE TITLE
Is there a way to know in advance which files Elixir Compilers will compile before calling `mix deps.compile` and `mix compile`?

### ISSUE THREAD

**Issue by scottming** [elixir-lang/elixir#12549] opened 2023-05-05 01:21 UTC
These past few months, I have been helping with Elixir LSP-related tasks. After opening the editor and starting the LSP, it needs to do some things before it can truly start working, such as fetching deps and compiling. Using WorkDoneProgress to report progress is a good way.

https://user-images.githubusercontent.com/12830256/236360424-95a4d5e3-3a44-411d-b5d2-7fec725162a2.mp4

https://github.com/lexical-lsp/lexical/pull/135

I mainly use a compile tracer to achieve this, which looks good but is not Awesome. Is there a way to know which files the Elixir compiler will compile so that I can calculate the total number in advance and have a precise percentage? This would make the UI/UX better and the progress more straightforward.

In addition, I have looked at the logic of `mix/tasks/compile.ex` and `mix/tasks/compile_all.ex`, but I don’t quite understand their dependency calculation logic.

p.s. It seems that this compiler question is difficult to get an answer on ElixirForum, so I posted it here.

**Comment by scottming** [comment] 2023-05-05 09:44
Currently, we have two nodes in operation: a server node and a remote control node. They are responsible for the tasks you mentioned earlier. Thanks to Steve's excellent design, it has eliminated a lot of complexity and made many features much simpler to implement. It has also made some **practical** features possible, such as **as-type-complication** (real-time diagnostics without needing to save - currently my favorite feature). Additionally, it greatly reduces the problem of LSP and user project contamination.

Furthermore, Steve has done a lot of work on the protocol layer, which allows contributors to focus solely on business logic instead of worrying about protocol issues. For example, I spent only 2 hours making this *WorkDoneProgress** feature work, which I couldn't imagine before.

I haven't discussed this with Łukasz Samson yet, and I feel sorry because I would like to contribute more to ElixirLS, but its complexity exceeds my understanding.

**Comment by scottming** [comment] 2023-05-05 10:14
> Maybe we can emit tracer events though whenever a cycle starts or finish. Would that help?


It probably wouldn't be helpful because the actual `begin` and `end` events are [here](https://github.com/lexical-lsp/lexical/blob/6259f361ddd02a61edcd6b6275e0be3a59ff309c/apps/remote_control/lib/lexical/remote_control/build/state.ex#L193), and this is the [with_progress](https://github.com/lexical-lsp/lexical/blob/6259f361ddd02a61edcd6b6275e0be3a59ff309c/apps/remote_control/lib/lexical/remote_control/build/progress.ex#L6) function, while the compile tracer reported event kind is `:report`,

That's okay, and I'm quite satisfied with the current UI/UX. We can leave it this way. At that time, I guessed it would be difficult to know in advance how many files really needed to be compiled, so I asked this question.

**Comment by josevalim** [comment] 2023-05-05 10:14
Cool. I will go ahead and close this then, but please don't hesitate to reach out :)

**Closed by josevalim** 2023-05-05 10:14 UTC

**Comment by scottming** [comment] 2023-05-05 10:19
> Btw, if we tell you how many files there are to compile, perhaps you could show "Compiling 13 out of 56" files in the bottom, which may be a better indicator than cycling through the filenames? Your call :)

Yes, that would be better.

**Comment by scottming** [comment] 2023-05-05 10:37
And if excluding cycles? Then I can easily know the number of files will be compiled in advance?

**Comment by josevalim** [comment] 2023-05-05 10:43
@scottming we know how many files are available in a cycle but we don't know how many cycles that will be (most times it will be one). Is this something you would like us to expose?

**Comment by scottming** [comment] 2023-05-05 10:47
To be honest, I'm not sure. I may need some time to think about it. I'll come back in a few days and ask again when I have a clear question.

Thank you for your patience.

**Comment by josevalim** [comment] 2023-05-05 16:05
> For example, it would be awesome if compiler errors were consistently emitted as data structures rather than just printing to stdout

If compilation fails, you should be able to get the failure reason as a compiler diagnostic. For example, I added `raise "OMG"` to a file and I got this:

```elixir
{:error,
 [
   %Mix.Task.Compiler.Diagnostic{
     file: "/Users/jose/OSS/elixir/foo/lib/foo.ex",
     severity: :error,
     message: "** (RuntimeError) OMG\n    lib/foo.ex:20: (file)\n    (elixir 1.15.0-dev) lib/kernel/parallel_compiler.ex:379: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8\n",
     position: 20,
     compiler_name: "Elixir",
     details: nil
   }
 ]}
```

There is still some parsing required there but we can add more information to make it easier? So next steps:

1. If we are not returning an exception as diagnostic, please find a bug report
2. If you are having to parse the diagnostic above, let us know so we can provide it in a more structured fashion

>  It would also be great if we could extract code intelligence from livebook and publish that as its own library

The issue is "where the knowledge base comes from". Livebook is an evaluation tool, so all of the module information will be available in the runtime. elixir_sense is a compilation tool, so the information may be in a dependency or in a module that you compiled in a previous cycle. So far we are trying to implement the shared functionality between them in Elixir. In the future, we can provide more, but we would probably need a new abstraction (some idea of provider which can answer what are the variables, aliases, imports, and so on available in a given place).

>  I do understand that dialyzer has always been a double edged sword

I hope in 2 years we will have a better integrated type system in Elixir (if everything goes according to plan). So if the goal is to have a new tool, perhaps it could avoid adding what could soon become legacy. On the other hand, the new incremental Dialyzer mode in OTP 26 seems like a massive improvement and that may help.

**Comment by scohen** [comment] 2023-05-05 16:07
> If compilation fails, you should be able to get the failure reason as a compiler diagnostic. For example, I added raise "OMG" to a file and I got this:

Let me be more clear. Warnings are not reliably emitted as data structures, even when `--errors-as-warnings` is passed (which we cannot do, because we need to be able to emit build artifacts for projects with warnings)

**Comment by josevalim** [comment] 2023-05-05 16:09
@scohen sounds like a bug. If you can reproduce it, please let me know how. :)

**Comment by scohen** [comment] 2023-05-05 16:13
@josevalim it's been a bit since I've needed to mess with the build code, but the way to reproduce this is via `Code.compile_quoted`, and not via Mix.

**Comment by scohen** [comment] 2023-05-05 22:34
that's the one ;)
