### ISSUE TITLE
Formatter breaks single line clauses because of comments

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#7742] opened 2018-06-11 15:25 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.5 and master

### Current behavior

```elixir
case x do
  # comment
  :foo -> :bar
end
```

is formatted into

```elixir
case x do
  # comment
  :foo ->
    :bar
end
```

### Expected behavior

Keep clauses as single line because they are not beyond the line length limit and comments should not affect it.

**Comment by Hanspagh** [comment] 2018-06-25 13:30
This also seems to be the case when adding a line break in any of the case statements

    case x do
      :foo -> :bar
      :foo -> 
        :bar
    end
is formatted to 

    case x do
      :foo ->
        :bar

      :foo ->
        :bar
    end

**Comment by fertapric** [comment] 2018-06-25 13:31
@Hanspagh I think that's an expected behavior.

**Comment by ericmj** [comment] 2018-06-25 13:34
Yes, that's expected behavior, the formatter works similarly on other circumstances.

**Comment by Hanspagh** [comment] 2018-06-25 13:51
@fertapric I expected that as well, but was not able to find any docs to support this, so I though I might as well report it

**Comment by josevalim** [comment] 2018-07-09 09:12
Closing in favor of #7843.

**Closed by josevalim** 2018-07-09 09:12 UTC
Labels: App:Elixir, Kind:Bug, Note:Formatter
