### ISSUE TITLE
Suspected Memory Leak in Iex

### ISSUE THREAD

**Issue by suprafly** [elixir-lang/elixir#4200] opened 2016-01-14 18:53 UTC
Hey there, just getting into Elixir, which I love so thanks for all your hard work, and I'm running into a nagging problem that everytime I use Iex to run some code over time it ends up eating all of my memory and swapping me.

Running: Xubuntu 14.04
Latest stable Elixir installed from the repositories as directed in the installation guide.
On a small and (purposefully) underpowered Asus x200ca (model # X200CA-DH21T)
from a Terminator instance

Actually, the swapping happens pretty much upon starting up Iex, which is strange because my system load monitor shows that I am swapping a little bit but that I have plenty of free ram.

Methods for reproducing this are consistent and easy:
- Start up iex from the terminal
- Load a file with c "filename.exs" command
- Do some things
- Edit file, reload file, etc

Over time, my system becomes increasingly more strained to the point where I must reboot.

**Note**
I have never had a problem like this with this machine in the past 2 years in which I've been using it daily for development.

**Comment by josevalim** [comment] 2016-01-14 19:20
What are your Erlang and elixir versions?

On Thursday, January 14, 2016, Chris <notifications@github.com> wrote:

> Hey there, just getting into Elixir, which I love so thanks for all your
> hard work, and I'm running into a nagging problem that everytime I use Iex
> to run some code over time it ends up eating all of my memory and swapping
> me
>
> Running: Xubuntu 1404
> Latest stable Elixir installed from the repositories as directed in the
> installation guide
> On a small and (purposefully) underpowered Asus x200ca (model #
> X200CA-DH21T)
> from a Terminator instance
>
> Actually, the swapping happens pretty much upon starting up Iex, which is
> strange because my system load monitor shows that I am swapping a little
> bit but that I have plenty of free ram
>
> Methods for reproducing this are consistent and easy:
>
>    - Start up iex from the terminal
>    - Load a file with c"filenameexs" command
>    - Do some things
>    - Edit file, reload file, etc
>
> Over time, my system becomes increasingly more strained to the point where
> I must reboot
>
> *Note*
> I have never had a problem like this with this machine in the past 2 years
> in which I've been using it daily for development
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4200>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by suprafly** [comment] 2016-01-14 19:24
**Output of: iex --version**

Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Elixir 1.1.1

**Comment by josevalim** [comment] 2016-01-15 10:00
Hi @suprafly! Glad you enjoy and thanks for the report!

You may try to updating your Erlang version because some version in the 18 series had a memory leak. Although, the memory leak was related to whatever you type in the terminal, it would not grow on its own forever.

On the other hand, it may be related to something in your application or the code being reloaded. If you start a new application with `mix new foo`, and try `iex -S mix`, do you have a memory leak? If you run just `iex`, do you have it?

At this point, it would be very important for us to find a way to reproduce this, otherwise there isn't much we can do. So steps to reproduce, sharing snippets, will help a lot. Thank you!

**Comment by suprafly** [comment] 2016-01-16 03:45
Agreed. I'm happy to help. I will work on getting a sensible series of steps together to reproduce this, as well as as much info as possible.

**Comment by josevalim** [comment] 2016-01-19 22:05
I am closing this until we get a way to reproduce it. Please @suprafly just ping here or open up a new issue. :)

**Closed by josevalim** 2016-01-19 22:05 UTC
Labels: Note:Needs more info

**Comment by suprafly** [comment] 2016-01-20 01:22
Sounds good José.

I am still having the issue, but having a difficult time getting a lock on
a specific and reproducible pathway to get it to happens. It's one of those
particularly annoying bugs that only surfaces when you get back to work :)

..Chris

**Comment by suprafly** [comment] 2016-01-21 20:00
I'm working on getting some simple code that will consistently reproduce
this, but as of right now here's what I did this morning..

I have nothing open but SublimeText, terminator.

I run iex with the simple command: iex

Now, I am working on an algorithm to build a prefix tree from a dictionary
of about 250k words. My workflow (which admittedly may not be correct, as
I've only been with elixir for 19 days now) is thus:

  c "trie.exs"
  t = Trie.make("words.txt")

At this point, I will go back to sublime, make some edits, then "reload"
the module and try again using the same commands above.
Occasionally I seem to need to abort iex because, my tree is so large that
upon successful evaluation and return, iex attempts to inspect the result,
but it's too much to render to output and so it hangs for a long time.

After breaking out, I simply do the same steps again:
  > iex
  c "trie.exs"
  t = Trie.make("words.txt")

After a couple of hours of this workflow, my ram and swap are both reaching
maxed out.

As elixir is my first foray into the Erlang VM, I did a quick search to see
if I could kill the erlang processes that were responsible for maintaining
the VM. I found and ran this bash script:

  for i in `ps -ef | grep erl | awk '{print $2}'`; do echo $i; kill -9 $i;
done

That produced a massive drop in my ram and swap as it cycled through and
killed everything.

In total it killed 155 processes.


Hope this helps!

..Chris

**Comment by lexmag** [comment] 2016-01-21 21:52
@suprafly are you using ElixirSublime plugin?
I suspect it might be the same as in the #3951: the problem in that plugin vishnevskiy/ElixirSublime/issues/20.

**Comment by suprafly** [comment] 2016-01-22 04:19
@lexmag This might be the root cause. I've removed the ElixirSublime plugin and after some light testing, I am not seeing the problem. I will do a bit more heavy testing w/o the plugin this weekend to ensure that this fixes the issue.

Thanks so much!

**Comment by suprafly** [comment] 2016-01-22 20:26
Confirming that this problem is nto related to Elixir, or Iex, but to #3951 in the ElxixirSublime plugin.

Tested at 4 hours of continuous usage w/o the Plugin installed, no problems were seen.
