### ISSUE TITLE
Auto merge mix.lock when there are merge conflicts

### ISSUE THREAD

**Issue by blatyo** [elixir-lang/elixir#6554] opened 2017-09-09 13:01 UTC
Whenever two people make updates to the `mix.lock`, merge conflicts can emerge. Once there is a merge conflict, `mix` is no longer able to read the `mix.lock` and the user is responsible for manually merging. This process is error prone because the user is editing an automatically generated file and may introduce errors while attempting to resolve the merge conflicts.

This can be addressed by `mix` handling the merge and picking a permutation of the versions that satisfies the projects dependencies.

Initial discussion about this feature can be found [here](https://groups.google.com/forum/#!topic/elixir-lang-core/sSzR6GT3H-0).

Inspiration for this feature comes from this [yarn commit](https://github.com/yarnpkg/yarn/pull/3544/files) which added a similar feature.

**Comment by joshprice** [comment] 2017-09-15 02:32
I had this exact issue the other day because we were depending on the Github version of a dependency which had changed. I resolved on a couple of occasions by deleting `mix.lock` and re-running `mix deps.get`.

This appears to be the strategy that Yarn uses when it can't auto resolve the lock file conflicts. `'A merge conflict was found in yarn.lock but it could not be successfully merged, regenerating yarn.lock from scratch.'` (see https://github.com/yarnpkg/yarn/blob/2c8a0b2d809505b018faa3bd230cedb715b2bd17/src/reporters/lang/en.js#L86-L88)

Unless I'm missing something, it seems to me that this is probably the safest option. And as long regenerating the lock file from a clean `mix.exs` is fast enough, I can't think of any other drawbacks.

**Comment by michalmuskala** [comment] 2017-09-15 04:11
Regenerating from scratch does not sound safe at all to me. The reason for the lock file is to prevent unexpected upgrades. Once you delete the lock file, all bets are off.

**Comment by joshprice** [comment] 2017-09-15 04:50
Fair enough, is there some way to use the manifest (`.compile.lock`) to prevent unexpected upgrades?

**Comment by michalmuskala** [comment] 2017-09-15 04:53
That is the only reason the `mix.lock` file exists, I don't think the responsibility is replicated anywhere else.

**Comment by joshprice** [comment] 2017-09-15 05:12
I couldn't follow from https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/lock.ex exactly what the manifest was doing.

Do you think it makes sense to try and merge the conflicts in the lockfile in the style of yarn?

Is version control not a reasonable safety for unexpected upgrade issue?

**Comment by josevalim** [comment] 2017-09-15 07:38
I agree with @michalmuskala we should never delete the lock file. If we can't solve conflicts, then we should abort and let the user handle it. Most likely by checking the latest version from version control. I am actually surprised Yarn does otherwise, as that defeats the point of a lock. 

The manifest is used for something different. We write to the manifest to know when we need to recompile the whole project depending on the Elixir+OTP versions. We should likely not use it to handle other lock concerns. :)

**Comment by joshprice** [comment] 2017-09-15 08:17
Fair enough, I suppose this was a reasonable strategy for me at the time as I was up to date with all deps so this didn't cause any problems. However if you were preserving older versions for a reason this definitely would be undesirable/unexpected behaviour.

I'll have a go at parsing and resolving the conflicts in the mix file then.

**Comment by dkarter** [comment] 2017-09-22 13:27
I found that we had conflicts in the mix.lock file when people were using different versions of hex. Once all machines were updated the conflict was gone. Not sure if others in the community had a similar experience.

If I am able to replicate this I will suggest we add a line in the mix.lock recording that it was last generated with "hex v0.17.1". 

This can be used by mix deps.get to warn the user in case they have a different version that their mix.lock file will be different.

Ruby does something similar in Bundler in `Gemfile.lock` with 

```
BUNDLED WITH
   1.16.0.pre.2
```

Any thoughts on that?

**Comment by ericmj** [comment] 2017-09-24 16:48
@dkarter Unfortunately I don't see how we can add something to the lock file that tracks the version of elixir or hex. Hex also warns the user once every day if they use an old version so I don't think more warnings would necessarily help.

I have opened the issue https://github.com/hexpm/hex/issues/429 to investigate if we can keep lock entries in a newer format even when using older clients so that lock entries are not rolled back to the old format when using an old client.

**Comment by kelvinst** [comment] 2017-11-08 12:56
@josevalim I will work on this tonight if no one else is working on it...

**Comment by kelvinst** [comment] 2018-02-23 13:34
@josevalim I guess it's decided to actually not make this at all, didn't it?

**Comment by josevalim** [comment] 2018-02-23 15:32
Yes, good catch. :)

**Closed by josevalim** 2018-02-23 15:32 UTC
Labels: App:Mix, Kind:Feature, Level:Intermediate
