### ISSUE TITLE
escript.install fails when $HOME is a relative path

### ISSUE THREAD

**Issue by uhthomas** [elixir-lang/elixir#10905] opened 2021-04-14 23:58 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system:  linux/amd64

### Current behavior

Given a valid mix project which depends on https://hex.pm/packages/protobuf.

```sh
export HOME=test
mix do local.hex --force, local.rebar --force, deps.get, deps.compile, escript.install hex protobuf --force
```

It will then output

```
* creating test/.mix/escripts/protoc-gen-elixir
```

But the file doesn't exist and `mix escript list` says
```
No escripts currently installed.
```

### Expected behavior

The escript should successfully install with relative paths.

**Comment by josevalim** [comment] 2021-04-15 05:40
Does the directory exists? Also, is there any documentation that explicitly forbids or denies that the $HOME directory can be a relative path?

**Comment by josevalim** [comment] 2021-04-15 06:07
I have debugged this and the issue is that we install it in the "test" directory inside the checked out project (in this case, protobuf). I will go ahead and close this as won't fix because, if you are using relative paths, that's precisely what will happen if a script - such as mix escript.install - is changing the current working directory. Here is my session:

```
==> ex_doc
Compiling 23 files (.ex)
Generated ex_doc app
Generated escript ex_doc with MIX_ENV=prod
Are you sure you want to install "ex_doc"? [Yn]
* creating test/.mix/escripts/ex_doc

warning: you must append "/private/var/folders/zk/rs0s0clx0c1195vldcftpc9c0000gn/T/mix-local-installer-fetcher-ov1b8w/deps/ex_doc/test/.mix/escripts" to your PATH if you want to invoke escripts by name
```

**Closed by josevalim** 2021-04-15 06:07 UTC
