### ISSUE TITLE
Formatter does not respect `.formatter.exs` when piping code into it

### ISSUE THREAD

**Issue by bitboxer** [elixir-lang/elixir#7573] opened 2018-04-20 12:23 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.6.3 (compiled with OTP 19)
```

* Operating system: 

```
Ubuntu 16.04.4 LTS
```

### Current behavior

When piping code into the formatter like this:

```
cat path/to/file.ex | mix format -
```

it does not respect the local `.formatter.exs`. It also ignores the `--dot-formatter` setting.

Am I doing something wrong? Is this a bug?

### Expected behavior

It should format the code using the local `.formatter.exs` or at least the one I specify in the params.

**Comment by NobbZ** [comment] 2018-04-20 12:28
Ignoring the default `.formatter.exs` is by design, as a piped in stream of characters is considered to be unrelated to the current (or any) project.

In my opinion it should respect an explicitely passed in config file via `--dot-formatter` though.

**Comment by josevalim** [comment] 2018-04-20 12:37
This is fixed on v1.6.4.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Closed** 2018-04-20 12:41 UTC

**Comment by bitboxer** [comment] 2018-04-20 13:07
Thanks for the quick reply 👍

**Comment by bitboxer** [comment] 2018-04-23 06:56
Just found time to test this in my local elixir 1.6.4

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 19)
```

Sadly I can't confirm that this works.

I did this:

```
cat path/to/file.exs |  mix format --dot-formatter=path/to/.formatter.exs -
```

And it did non respect the config I gave to it. Using 

``
mix format --dot-formatter=path/to/.formatter.exs path/to/file.exs
```

it worked.

**Comment by josevalim** [comment] 2018-04-23 08:31
@bitboxer it worked just fine here. Here is what I did:

    $ cat foo.ex | mix format --dot-formatter=path/to/elixir/repo/.formatter.exs -
    assert_same bar

Notice that it did not add parens around assert_same since it is listed in .formatter.exs.

**Comment by bitboxer** [comment] 2018-04-23 08:42
Maybe the issue is that my `.formatter.exs` looks like this:

```
[
  inputs: ["mix.exs", "config/*.exs"],
  subdirectories: ["apps/*"]
]
```

and in the subdirectories I have some additional formatter files. Will try it out with moving the stuff into the main config file tonight.

**Comment by josevalim** [comment] 2018-04-23 10:02
The input file `-` will never traverse the subdirectories since it doesn't have any path in it. It always consider the root one. And since you don't have anything at the root then it will only o the default formatting.

**Comment by bitboxer** [comment] 2018-04-23 13:03
Other languages have a parameter for the formatter to set the root path if you pipe a file into the formatter. But it's okay if you think this might be too much overhead for elixir. I can work around that with saving the file in a specific directory and deleting it afterwards.
