### ISSUE TITLE
Ensure we recompile protocols on IEx.Helpers.recompile

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4151] opened 2016-01-03 19:41 UTC

**Comment by emilsoman** [comment] 2016-02-25 08:20
@josevalim this bit me too. I spent some time yesterday debugging this.
Here's what I found:

Step 1. Create an app with a protocol and compile for the first time -> works as expected
Step 2. Change the protocol and compile again -> compiles fine, but function in protocol not dispatched properly.

I think the problem is that we don't check for stale protocols, instead currently only additions or removals result in fresh consolidation. I tried to see if I can put together a fix that checks if protocol files become stale compared to the protocol manifest in order to mark them for consolidation.

Here's the code that I have so far : https://github.com/emilsoman/elixir/commit/223b809b2b252f4d84f28c2e5b7ba9a78f6b0cc8 . Please let me know if this is in the right direction.

**Comment by josevalim** [comment] 2016-02-25 08:26
@emilsoman I think we should be able to simply call "compile.protocols" inside the recompile task. Have you tried this approach? Also, can you provide a repo that reproduces the issue? :) It will make it easier for us to verify a fix. Thank you!

**Comment by emilsoman** [comment] 2016-02-25 09:16
@josevalim Here's a repository which demonstrates the issue : https://github.com/emilsoman/protocol_recompile .

Please note that I'm using the master branch of Elixir. Steps to reproduce are mentioned on the README. Thanks :)

**Comment by emilsoman** [comment] 2016-03-07 14:58
@josevalim were you able to reproduce the issue ?

**Comment by josevalim** [comment] 2016-03-07 15:02
Sorry, I didn't try it yet! I will do once i am back to tackling issues.

**Comment by tuvistavie** [comment] 2016-03-07 15:20
I managed to reproduce the issue here, but I did not find a solution yet.
Calling `compile.protocols` does not work, as [`Mix.Utils.stale?` seems to return `false`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.protocols.ex#L52),
and the manifest itself is not changed, as it does not contain information about
the name of the functions in the protocol.
I will try to check why `stale?` is returning `false` when I have a moment.

**Comment by emilsoman** [comment] 2016-03-07 15:35
I was preparing a fix for this. Can you check this comment above : https://github.com/elixir-lang/elixir/issues/4151#issuecomment-188666329

**Closed** 2016-05-13 16:34 UTC
Labels: App:IEx, Kind:Bug, Level:Intermediate
