### ISSUE TITLE
`Path.wildcard` fails for `"{"`.

### ISSUE THREAD

**Issue by reitermarkus** [elixir-lang/elixir#6311] opened 2017-07-08 21:03 UTC
## Environment

Elixir version: 1.4.5
Erlang version: 20.0
Operating system: macOS 10.13

### Current behavior

```bash
mkdir -p '{'
iex -e 'Path.wildcard("{")'
```

produces an ErlangError:

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

** (ErlangError) erlang error: {:badpattern, :missing_delimiter}
    (stdlib) filelib.erl:62: :filelib.wildcard/2
    (elixir) lib/path.ex:594: Path.wildcard/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:170: Code.eval_string/3
```

### Expected behavior

This should not fail and return `["{"]`.

**Comment by josevalim** [comment] 2017-07-08 21:08
Thank you! I think the error is correct, it is a bad pattern. The issue is that it doesn't seem to have anyway to escape the pattern. 

As the error message says, we simply delegate to Erlang, so I would advise sending a pull request there.

**Comment by josevalim** [comment] 2017-07-10 12:37
Closing this as it is rather a bug coming from Erlang, which requires fixing in OTP, as mentioned above.

**Closed by josevalim** 2017-07-10 12:37 UTC
Labels: App:Elixir, Kind:Chore, Note:Discussion, Note:Erlang bug
