### ISSUE TITLE
Formatter writes empty files

### ISSUE THREAD

**Issue by baldmountain** [elixir-lang/elixir#6972] opened 2017-10-25 17:46 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0-dev (58a973ae1) (compiled with OTP 20)

* Operating system: MacOS High Sierra

### Current behavior

I have an umbrella project with several apps. I installed Elixir master today (11-25-2017) using `kiex` to try the new formatter. My .formatter.exs looks like:

```elixir
[
  inputs: [
    "mix.exs",
    "config/**/*.{ex,exs}",
    "apps/graphql/{config,lib,test}/**/*.{ex,exs}",
    "apps/pacer/{config,lib,test}/**/*.{ex,exs}",
    "apps/ui/{config,lib,test}/**/*.{ex,exs}"
  ]
]
```

The ui app is a Phoenix app and the other two apps are regular Elixir apps. Most times when I run `mix format` it works as expected. But the formatter complained that I had a compile error in the pacer app and the apps/ui/lib/ui/application.ex and apps/ui/lib/ui/ui_web/ui.ex files were both empty when the formatter finished.

Luckily I could rebuild the files since they are simple, but the formatter shouldn't ever overwrite a file with an empty file.

Sorry, this is a non-open source project so I can't give access to it.

### Expected behavior

Non-empty files not empty

**Comment by josevalim** [comment] 2017-10-25 17:56
Do you still have the full error and stacktrace from when you get the compilation error?

**Comment by josevalim** [comment] 2017-10-25 17:57
Nevermind, I found the root cause. :)

**Comment by josevalim** [comment] 2017-10-25 18:02
Fixed in master, it was a race condition. Thanks for the report!

**Closed** 2017-10-25 18:02 UTC

**Comment by baldmountain** [comment] 2017-10-25 19:25
You're welcome and wow that was fast! :)
