### ISSUE TITLE
Map initialized in different sequence cause error

### ISSUE THREAD

**Issue by hupengbuaa** [elixir-lang/elixir#7734] opened 2018-06-09 13:40 UTC
I tried this expression in `iex`:
```
%{"hi"=>1, a: 2}
# %{:a => 3, "hi" => 1}
```
while tried this:
```
%{a: 2, "hi"=>1}
# ** (SyntaxError) iex:11: syntax error before: "hi"
```
Quite strange, isn't it? Is it a bug or a feature?

**Comment by fertapric** [comment] 2018-06-09 13:43
Duplicate of https://github.com/elixir-lang/elixir/issues/7497

**Comment by josevalim** [comment] 2018-06-09 15:16
Yes, Elixir only supports keywords at the trailing position. :)

**Closed by josevalim** 2018-06-09 15:16 UTC
