### ISSUE TITLE
Add hint for misspellings when unknown local function call

### ISSUE THREAD

**Issue by viniciusmuller** [elixir-lang/elixir#12957] opened 2023-09-23 04:08 UTC
### Elixir and Erlang/OTP versions

main

### Operating system

any

### Current behavior

```ex
defmodule Test do
  def run(n) do
    get_resut(n)
  end

  def get_result(term), do: term + 1
end
```

Running this gives us:
```
    error: undefined function get_resut/1 (expected Test to define such a function or for it to be imported, but none are available)
    │
  3 │     get_resut(n)
    │     ^^^^^^^^^
    │
    └─ unknown-local-call.ex:3:5: Test.run/1
```

### Expected behavior

The idea:

```
    error: undefined function get_resut/1 (expected Test to define such a function or for it to be imported, but none are available)
    hint: function with similar name "get_result" defined at line 6
    │
  3 │     get_resut(n)
    │     ^^^^^^^^^
    │
    └─ unknown-local-call.ex:3:5: Test.run/1
```

Or if we're feeling much more adventurous (but I don't think it plays well with having the span, it probably would look better if we used just a └ in the function call, and might look a bit overwhelming)

```
    error: undefined function get_resut/1 (expected Test to define such a function or for it to be imported, but none are available)
    │
  3 │     get_resut(n)
    │     ^^^^^^^^^ undefined function called here
    │
  6 │  def get_result(term), do: term + 1
    │      └ similarly named function defined here
    │
    └─ unknown-local-call.ex:3:5: Test.run/1
```

**Comment by josevalim** [comment] 2023-09-23 09:01
The challenge with introducing this functionality is that you may have intended either a local function or an imported function. However, in order to suggest an imported function, we would need to know and store all imports at the place the local call happened.

So we have two options:

1. Don't show anything
2. Only show local functions, as you suggested, knowing that we may be misleading for not including local functions

**Comment by viniciusmuller** [comment] 2023-09-23 13:45
I'm not so familiar with this part of the compiler, but would it be an enormous task for us to track imports as well in locals trackers and be able to show something like `hint: did you mean 'from'? (imported from Ecto.Query)`

**Comment by josevalim** [comment] 2023-09-23 14:55
It is easy to store it, the issue is that it is _expensive_ to store it. We would need to store all modules and fa pairs on every function call you make, which i wouldn't be surprised if it has an actual effect on compilation times.

**Comment by viniciusmuller** [comment] 2023-09-23 15:07
Hmm, would we need to save this data for every function call? 
I was thinking about  having an agent/ets table for every module that would track all the imports, but I guess we can´t do it per module because someone could import it only inside a scope (although uncommon)?

**Comment by josevalim** [comment] 2023-09-23 15:31
Exactly, the issue is that you can import something anywhere, so we would need to keep a tree of scopes, which is definitely doable, but there is a lot of complexity related to that.

**Comment by josevalim** [comment] 2023-09-23 15:37
I will go ahead and close this one. Glad to revisit if I can think of a break through for tackling this. :)

**Closed by josevalim** 2023-09-23 15:37 UTC

**Comment by viniciusmuller** [comment] 2023-09-23 15:42
That's fine I guess

I think for us to just do something like

``` 
# local = unknown local

hint = locals
|>Enum.map(&compare_distance(&1, local))
|> Enum.filter(fn distance ->distance >= @threshold)
|> Enum.sort
|> Enum.first()
```

This shouldn't affect and I think should already be a first step in this direction, I think it's fine not to show it for every case of unknown local call, in the same way sometimes we might not show because there's nothing in scope that is similar enough to the unknown call
