### ISSUE TITLE
In elixir.bat some argument values are not properly quoted

### ISSUE THREAD

**Issue by E14** [elixir-lang/elixir#13565] opened 2024-05-17 00:53 UTC
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

### Operating system

Windows 11

### Current behavior

When passing CLI parameter `-pa` with an argument that contains spaces, the elixir startup batch file will strip quotes and `cmd.exe` will fail with an error message. This message can vary depending on how the path is constructed, for example here is the most simple reproducer I could think of

```cmd
C:\>"c:\Program Files\Elixir\bin\elixir.bat" "-pa" "c:/Program files" -e "IO.puts('Success!')"
No file named files
```

This very likely applies to other parameters as well, like `-r`, `-pa`, `-pr`, `-pz`, as I understand all of those take a path value, but I don't know the semantics

Here's the code in question:
https://github.com/elixir-lang/elixir/blob/6f84158baefec6298e6b7727d4ec7cf73687cf1c/bin/elixir.bat#L132-L135

Here's a diff/patch of the changes I made that resolved my immediate issue (but I'm not certain it won't produce other issues, quoting in CMD is *weird*):
```diff
--- a/elixir.prev.bat
+++ b/elixir.bat
@@ -129,10 +129,10 @@ if ""==!par:--rpc-eval=! (
   goto startloop
 )
 rem ******* ELIXIR PARAMETERS **********************
-if ""==!par:-r=!          (set "parsElixir=!parsElixir! -r %~1" && shift && goto startloop)
-if ""==!par:-pr=!         (set "parsElixir=!parsElixir! -pr %~1" && shift && goto startloop)
-if ""==!par:-pa=!         (set "parsElixir=!parsElixir! -pa %~1" && shift && goto startloop)
-if ""==!par:-pz=!         (set "parsElixir=!parsElixir! -pz %~1" && shift && goto startloop)
+if ""==!par:-r=!          (set "parsElixir=!parsElixir! -r "%~1"" && shift && goto startloop)
+if ""==!par:-pr=!         (set "parsElixir=!parsElixir! -pr "%~1"" && shift && goto startloop)
+if ""==!par:-pa=!         (set "parsElixir=!parsElixir! -pa "%~1"" && shift && goto startloop)
+if ""==!par:-pz=!         (set "parsElixir=!parsElixir! -pz "%~1"" && shift && goto startloop)
 if ""==!par:-v=!          (set "parsElixir=!parsElixir! -v" && goto startloop)
 if ""==!par:--version=!   (set "parsElixir=!parsElixir! --version" && goto startloop)
 if ""==!par:--no-halt=!   (set "parsElixir=!parsElixir! --no-halt" && goto startloop)
```

So the `%~1` removes surrounding quotes if they exist, then we add it again, now we're relatively certain that the values are quoted exactly once.

Here's a related issue: #6455 though at the time this was resolved, the `-pa` et. al. worked just without the `~`. That would have worked for me as well, so I'm not completely certain why the tilde was introduced.

### Expected behavior

```
C:\>"c:\Program Files\Elixir\bin\elixir.bat" "-pa" "c:/Program files" -e "IO.puts('Success!')"
Success
```

**Comment by josevalim** [comment] 2024-05-17 07:56
Somewhat duplicate of #13165. We are currently rewriting those scripts to powershell because the quoting rules in batch are just too complicate to manage in the long term. :) However, I think we should give your suggestions a try. We definitely quote everything that is sent to Erlang.

**Closed** 2024-05-17 09:26 UTC

**Comment by E14** [comment] 2024-05-17 15:28
Thank you! Assuming this is working well, is there a chance that the change will be backported to previous versions?

> Somewhat duplicate of #13165. 
Somewhat, it might be due to https://github.com/elixir-lang/elixir/blob/11a493ec4a07479a74e605b409dd16e23bb5cafe/bin/elixir.bat#L101 and https://github.com/elixir-lang/elixir/blob/11a493ec4a07479a74e605b409dd16e23bb5cafe/bin/elixir.bat#L156

The `!par!` should be quoted there... I think. Because in L93 you're using `%~1` (which I think it is correct to not quote considering the later processing done.

> We are currently rewriting those scripts to powershell because the quoting rules in batch are just too complicate to manage in the long term.

I'll definitely be watching out for that change, I didn't have much luck and essentially given up to get startup scripts to run properly on Windows and was planning on just writing them in a compiled language or just give in and use .net.

**Comment by josevalim** [comment] 2024-05-17 15:54
Let's give it a try! I pushed a PR here with your changes, feel free to poke at it: https://github.com/elixir-lang/elixir/pull/13166
