### ISSUE TITLE
with clause cannot match when case is inside else block

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/elixir#6738] opened 2017-10-09 16:07 UTC
This is very similar to #6380, but shows up when using a `case` expression inside the `else` block of a `with`.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.5.2, Erlang 20.0
* Operating system: OS X 10.12.6 Sierra

### Current behavior
The following code functions correctly, but emits the `this clause cannot match because of different types/sizes` warning during compilation.

```elixir
with {:first, int1} when is_integer(int1)   <- {:first, Integer.gcd(2, 4)},
     {:second, int2} when is_integer(int2)  <- {:second, Integer.gcd(2, 4)} do
  {:ok, int1 + int2}
else
  error ->
    case error do
      {:first, nil}  -> {:error, "first number is not integer"}
      {:second, nil} -> {:error, "second number is not integer"}
    end
end
```

Obviously in this example it's not useful to have an embedded case expression, but I've found it to be useful a number of times for logging an error-specific message and then sharing any amount of cleanup/retry code inside the `else` block.

Failing test commited to `warning_test.exs` here: https://github.com/jordan0day/elixir/commit/ff4611acf3f1565f7c4989ade96e24a85ea68860

### Expected behavior
No warning should be emitted.

**Comment by josevalim** [comment] 2017-12-06 11:17
I am not sure if there is much we can do on this case besides maybe moving the logic to a private function. :( To solve this for good, we would need changes in the Erlang compiler as I really don't think we should mark everything in the `else` block as generated.

/cc @ggcampinho @michalmuskala

**Comment by michalmuskala** [comment] 2017-12-06 11:33
There are some changes in the erlang compiler around case statements (in master and PRs) that might make `with` optimize better. The problem is, it would work nice on OTP 21, but it would work worse then now on previous versions.

**Comment by jordan0day** [comment] 2017-12-06 15:03
Not a huge showstopper obviously, and wrapping the case bits in another function (even a local anonymous fn) seems to eliminate the compiler warning. Feel free to close the issue unless you'd like to keep it open to reexamine after OTP 21 is released.

**Comment by ggcampinho** [comment] 2017-12-06 17:01
I have the impression that is possible to mark the variables generated in the else clause and add `generated: true` where they are used directly, but it's not so easy to do it.

**Comment by josevalim** [comment] 2017-12-06 18:48
@ggcampinho it is definitely possible but I really don't think we should do it! :D

**Comment by ggcampinho** [comment] 2017-12-11 20:15
Agreed! I also think it's better to wait for OTP 21, maybe put a reference to that issue

**Comment by michalmuskala** [comment] 2017-12-12 10:45
Well, we first need to implement this optimization and get it merged for OTP 21 release 😆

**Comment by josevalim** [comment] 2018-10-25 08:51
@CharlesOkwuagwu what do you mean? This issue is not closed and, as you said, the issue still exists.

**Comment by michalmuskala** [comment] 2018-10-25 09:55
@CharlesOkwuagwu I'd say this is a completely separate issue. In this case you're pattern-matching on a compile-time constant value, so the compiler is right to complain some of the branches can never match.

The compiler has a very simple heuristic to decide if it should warn in such cases - it only doesn't warn if the argument of case is a constant. In this case it's only partially constant. I'd say this is more of an issue with the erlang compiler than the elixir layer on top.

**Comment by CharlesOkwuagwu** [comment] 2018-10-25 10:54
@josevalim Sorry, my mistake, I saw the closed from `Dialyzer only taking one path in `with` statement #7177`.

But yes, the warning still comes up.

@michalmuskala If values coming from `Application.get_env/2` are compile-time constant , then we will always have these warning anytime we try to do branching logic based on a `compile-time constant`

**Comment by dengbh** [comment] 2018-11-26 02:48
why not has Open source  in code?

**Comment by fertapric** [comment] 2019-01-21 11:00
I would like to share my findings in case it helps to future readers.

Elixir's `with` is internally expanded to a series of nested cases. To give an idea, the code above would be expanded to something similar to:

```elixir
case {:first, Integer.gcd(2, 4)} do
  {:first, int1} when is_integer(int1) ->
    case {:second, Integer.gcd(2, 4)} do
      {:second, int2} when is_integer(int2) ->
        {:ok, int1 + int2}

      var1 ->
        case var1 do
          error ->
            case error do
              # The Erlang compiler is smart enough to know this will never match.
              {:first, nil}  -> {:error, "first number is not integer"} 
              {:second, nil} -> {:error, "second number is not integer"}
            end

          var2 ->
            error({:with_clause, var2})
        end
    end

  var1 ->
    case var1 do
      error ->
        case error do
          {:first, nil}  -> {:error, "first number is not integer"}
          {:second, nil} -> {:error, "second number is not integer"}
        end

      var2 ->
        error({:with_clause, var2})
    end
end
```

The warning of this issue is emitted because the Erlang compiler is smart enough to know that the result of the nested case `case {:second, Integer.gcd(2, 4)} do` would never match`{:first, nil}`.

One idea to solve this issue is to change the code generated by `with`, so the the current code is wrapped into a parent `case` and the results are forwarded to that parent `case` using `:ok/:error` tuples. The example above would be then expanded to something like:

```elixir
case (
  case {:first, Integer.gcd(2, 4)} do
    {:first, int1} when is_integer(int1) ->
      case {:second, Integer.gcd(2, 4)} do
        {:second, int2} when is_integer(int2) ->
          {:ok, (
            {:ok, int1 + int2}
          )}

        err ->
          {:error, err}
      end

    err ->
      {:error, err}
  end
) do
  {:ok, ok} ->
    ok

  {:error, var1} ->
    case var1 do
      error ->
        case error do
          {:first, nil}  -> {:error, "first number is not integer"}
          {:second, nil} -> {:error, "second number is not integer"}
        end

      var2 ->
        error({:with_clause, var2})
    end
end
```

which does not emit any warning.

**Comment by fertapric** [comment] 2019-01-21 11:37
Other idea ([based on this comment by @nox](https://github.com/elixir-lang/elixir/pull/8661#issuecomment-456040834)) is to move the error handling to its own closure:

```elixir
fun = fn var1 ->
  case var1 do
    error ->
      case error do
        {:first, nil}  -> {:error, "first number is not integer"}
        {:second, nil} -> {:error, "second number is not integer"}
      end

    var2 ->
      error({:with_clause, var2})
  end
end

case {:first, Integer.gcd(2, 4)} do
  {:first, int1} when is_integer(int1) ->
    case {:second, Integer.gcd(2, 4)} do
      {:second, int2} when is_integer(int2) ->
        {:ok, int1 + int2}

      var1 ->
        fun.(var1)
    end

  var1 ->
    fun.(var1)
end
```

**Comment by josevalim** [comment] 2019-01-21 13:02
Yes, we want to do the closure but we need to push some improvements to the Erlang compiler to make it more efficient.

**Comment by josevalim** [comment] 2022-03-25 09:41
This will be fixed on Erlang/OTP 25. We are tracking it here: #11220.

**Closed by josevalim** 2022-03-25 09:41 UTC
Labels: Kind:Bug, App:IEx, Level:Advanced

**Comment by eseres** [comment] 2024-01-19 15:59
I actually see the same dialyzer report when I directly pattern match each possible return value from the functions in the `with` block. That is, I have multiple clauses in the `else` block vs. a single clause and a `case` block inside of it.

**Comment by sabiwara** [comment] 2024-01-19 23:50
Actually I think we should re-open @josevalim , since we weren't able to compile it as `maybe` due to the lack of guards?
https://github.com/elixir-lang/elixir/pull/12428#discussion_r1118591145
https://erlangforums.com/t/support-guards-in-erlang-maybe/2406

Should I give the closure approach a try? (will first double check if it causes any performance regression)

**Comment by josevalim** [comment] 2024-01-20 07:51
With our work on the system, will be the ones to emit these warnings, so this will be naturally addressed

**Comment by michalmuskala** [comment] 2024-01-20 18:37
FWIW Erlang's `maybe` is compiled with a closure for `else` handler https://github.com/erlang/otp/blob/43d2f9b647f03b55a423f156446411cd4c04f271/lib/compiler/src/v3_core.erl#L730

**Comment by josevalim** [comment] 2024-01-20 19:12
The benefit would be to remove code duplication in the beam file. I am unsure. :)

**Comment by sabiwara** [comment] 2024-01-21 00:31
> The benefit would be to remove code duplication in the beam file

Indeed, that's a great point.

> FWIW Erlang's maybe is compiled with a closure for else handler

In that case it's probably fine. The performance impact is only noticeable if the rest of the function barely doesn't do anything (which is the example I tried to capture in my artificial bench). In real world case it should be negligible.

@josevalim should I give this a try, WDYT?

**Comment by josevalim** [comment] 2024-01-21 08:14
Definitely, please give it a go!
