### ISSUE TITLE
Mix should not error out on non-SemVer versions, warning should be enough

### ISSUE THREAD

**Issue by martin-langhoff** [elixir-lang/elixir#4423] opened 2016-03-22 21:40 UTC
### Environment

* Elixir version (elixir -v): v1.2.3
* Operating system: Fedora 23 (I'm your friendly Fedora packager) and CentOS/RHEL 7.

### Current behavior

Our (complex, large) projects generate daily builds; and generally we can create a build from any git commit on our project. These happen to get built as rpms, but that's a minor detail.

These projects are not Elixir only, Python and other languages are used.

For offical builds, we use SemVer-formatted git tags. So far, so good. For daily builds we use version strings based on the output of `git describe --all --tags`, which is common/standard/best practice and widely used for many things (ie: pre-release builds for major projects in rpm and deb packages).

These versions look like: `v4.0.0_dev3_8_g4c4be2c` -- that's the 8th commit after `v4.0.0_dev3`, with a commit has starting with `4c4be2c`.

Mix (we are using `exrm` here) barfs at these "versions". Of course, they are not hard, formal versions; however,

 * a built tool must be used for building many intermediate builds
 * we are not going to issue a formal SemVer for infinite intermediate builds
 * we _do_ need to identify our builds, as they go to test/qa servers; `git describe` style is a fantastic fit and widely used
 * Mix should not be in the business of only building final releases, nor of dictating my scratch build versioning

It's all good if Mix issues a warning. Hopefully that is an acceptable tradeoff? Alternatively, an option to say "--ignore-version-foolishness".

### Expected behavior

Build my software, like a good build tool :-)

Related: this amazing example of SemVer shortsightedness https://github.com/mojombo/semver/issues/145

**Comment by josevalim** [comment] 2016-03-22 22:46
Hey @martin-langhoff, thank you for the report. We could allow you to build a non-semver version but you would still run into limitations like you won't be able to publish packages to Hex. Regardless of the pros and cons of semver, semver defines how versions should be ordered and this is very important for package managers like Hex.

Btw, is there any reason why you can't version it as "3.0.0+whatever_you_want_really"?

**Comment by ericmj** [comment] 2016-03-23 11:31
The version for your mix project does not have to match your git tags.

I am guessing you have something automated that generates the mix project version from git or something similar? A simple regex would likely be enough to make it conform to semver.

**Comment by martin-langhoff** [comment] 2016-03-23 13:23
@josevalim so I guess I had missed that semver handles plus signs for daily snaps. I can probably fix things up to make git describe output match.

I am still partial to a `--do-not-validate-version` option, not all my projects are Elixir-centric; Mix as a build tool should not be so heavy handed.

I completely agree, Hex and its public repositories need strict version handling for ordering consistency.

What's good for a daily or scratch build might not be acceptable for a release build; that is no surprise, but we sure need both kinds...

@ericmj -- it does not have to literally match them, and a simple regex is acceptable, in fact I already use one. It won't be trivial if it's to work with git describe output but I'll get it through.

**Comment by josevalim** [comment] 2016-03-23 14:58
Thanks @martin-langhoff. I will close this then because `+` will likely handle your use case. If folks have other use cases, please let us know.

**Closed by josevalim** 2016-03-23 14:58 UTC

**Comment by martin-langhoff** [comment] 2016-03-25 21:43
@josevalim thanks for your help so far.

After a bit of experimentation with '+' for snaps etc, we still have a problem. 

SemVer with prerelease tags does not play well at all with rpm or deb because it uses hyphens. The only way to identify a pre-release is to tag it "1.0.0-alpha". From git describe with a regex I can make subsequent commits look like "1.0.0-alpha+10-gf234ga"; however rpm will not like the either version string.

Right now, if I mangle the version string to remove hyphens, it fails to be SemVer. If I do not, Mix builds it but `exrm-rpm` fails.

**Comment by ericmj** [comment] 2016-03-25 21:46
@martin-langhoff What about sending a patch to exrm-rpm so that it changes the version to something rpm can handle? This really sounds like it should be handled by the tool that generates rpm packages.

We can't expect Mix to work with every possible versioning scheme.

**Comment by martin-langhoff** [comment] 2016-03-25 21:59
Hi @ericmj !  Mix is a build tool, using it to _mandate_ a version string is misguided. Good old `make` is flexible and agnostic and widely used.

I am fine with Mix pushing for SemVer, but a build tool must be humble and flexible; it might be used in an environment where is not the dominant tool. For example, a shop mainly using other languages / toolchains where folks are starting to use Elixir. That's how you sneak in and become popular :-)

SemVer is all cool and popular, but it is an immature format, so it has problems. When dealing with pre-release versions, it has a collision with the two main packaging toolchains (debian and rpm).

I am affected by this problem a bit ahead of the curve; as Elixir becomes more popular this will hit more folks.

If Mix prepares the build with `version=1.2.3-alpha` and exrm and exrm-rpm mangle the version string, we will set ourselves up for a situation where the strings don't match, files and directories do not match expected name and location.

**Comment by ericmj** [comment] 2016-03-25 22:02
> SemVer is all cool and popular, but it is an immature format, so it has problems. When dealing with pre-release versions, it has a collision with the two main packaging toolchains (debian and rpm).

The problem isn't with semver, it's a perfectly fine versioning format. The issues is that you expect semver to work with every possible, existing versioning scheme. That's just not possible.

> If Mix prepares the build with version=1.2.3-alpha and exrm and exrm-rpm mangle the version string, we will set ourselves up for a situation where the strings don't match, files and directories do not match expected name and location.

Can you show where this will be an issue?

**Comment by martin-langhoff** [comment] 2016-03-25 22:11
I expect SemVer to work nicely with rpm and deb packaging, and in some cases it does not. That is a major gotcha.

I also expect _build tools_ to be build tools :-) -- again kindly pointing folks in a good direction is fine, but mandating a versioning scheme is not. Why would Mix need that? Hex repositories (as gatekeepers before Hex clients) do need it, and that is the right place to do it.

Where will this be an issue? Versioning of the release tarballs for a start.

**Comment by ericmj** [comment] 2016-03-25 22:16
> I expect SemVer to work nicely with rpm and deb packaging, and in some cases it does not. That is a major gotcha.

That's expected because they use different versioning schemes.

> I also expect build tools to be build tools :-) -- again kindly pointing folks in a good direction is fine, but mandating a versioning scheme is not. Why would Mix need that? Hex repositories (as gatekeepers before Hex clients) do need it, and that is the right place to do it.

Mix is building mix projects, mix projects require semver. All projects using semver means that we can set proper version requirements on dependencies (and dependencies doesn't have to be hex packages). If it's not using semver we can't use version requirements that make sense.

> Where will this be an issue? Versioning of the release tarballs for a start.

I proposed a solution for this; patch exrm-rpm. Can you explain why this won't work=

**Comment by martin-langhoff** [comment] 2016-03-25 22:26
> That's expected because they use different versioning schemes.

Hmmm? Not so, please read the bug in the SemVer gihub repo I linked in the opening of this issue. Not expected, definitely a misfeature. Nobody wants to make their version strings awkward for deb and rpm packaging. See mojombo/semver#145

I have fleshed out other answers already, I hope we can leave this circular stage of the discussion behind ...

**Comment by ericmj** [comment] 2016-03-25 22:34
> Hmmm? Not so, please read the bug in the SemVer gihub repo I linked in the opening of this issue. Not expected, definitely a misfeature. Nobody wants to make their version strings awkward for deb and rpm packaging. See mojombo/semver#145

I have already read the issue and there doesn't seem be a consensus if it's an actual issue. Some people seem to think that semver should change to be compatible with debian and rpm and others believe that a new standard shouldn't be expected to conform to every other existing versioning scheme. We have to agree to disagree, like the many others in the issue you linked.

> I have fleshed out other answers already, I hope we can leave this circular stage of the discussion behind ...

I am trying to do so. If you can explain the issue with my proposed solution, which I am posting here for the third time, we can move forward:

"I proposed a solution for this; patch exrm-rpm. Can you explain why this won't work?"

**Comment by martin-langhoff** [comment] 2016-03-25 23:17
Patching exrm-rpm - there is quite a bit of surface to that; I pointed out matching version numbers of the tarballs included already. Perhaps you missed that?

I am not familiar with the internals of how Mix, exrm and exrm-rpm interop. I cannot tell you it won't work but it looks rather messy. Separating version strings in exrm-rpm based on usage, and policing that any scripts and tools that get the "rpm_version" do not interop with components that know the "version".

Having worked for almost two decades with toolchains for Perl, Python, Ruby, PHP and Erlang, and in packaging for Fedora and Debian, I find one of the most important points for build tooling is to be flexible and helpful. I am packaging Elixir in Fedora :-)

In any case, I can report that a one-line patch to `validate_version()` in Mix works as a quick hack and allows me to build snapshot RPMs.

**Comment by ericmj** [comment] 2016-03-25 23:27
> Patching exrm-rpm - there is quite a bit of surface to that; I pointed out matching version numbers of the tarballs included already. Perhaps you missed that?

I did not miss that but I think you missed my follow up question: "Can you show where this will be an issue?". If all tarballs follow the rpm versioning scheme then where will matching be an issue?

> I am not familiar with the internals of how Mix, exrm and exrm-rpm interop. I cannot tell you it won't work but it looks rather messy. Separating version strings in exrm-rpm based on usage, and policing that any scripts and tools that get the "rpm_version" do not interop with components that know the "version".

To me it's messy to not enforce semver. That means if someone accidentally sets a version that is not compatible with semver it means I won't be able to use their project as a dependency.

If it's impossible to make this work in exrm-rpm I think the best solution is to add a `--no-enforce-semver` flag to the `compile.app` that skips the semver validation in `validate_version`.

**Comment by martin-langhoff** [comment] 2016-03-25 23:35
@ericmj thanks. Keep in mind we are talking daily builds, usually of the top project, not libs, so they are not a dep for others. 

And I completely agree this should be an override. I just need it to be available.

**Comment by josevalim** [comment] 2016-03-26 08:53
I am thinking we should go from an error to a warning. @ericmj, does Hex.pm already validate the published version format? We just need to be safe on Hex' front.

**Comment by ericmj** [comment] 2016-03-26 10:18
Hex.pm does validate.

On Saturday, 26 March 2016, José Valim <notifications@github.com> wrote:

> I am thinking we should go from an error to a warning. @ericmj
> <https://github.com/ericmj>, does Hex.pm already validate the published
> version format? We just need to be safe on Hex' front.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4423#issuecomment-201736359>
>


-- 
Eric Meadows-Jönsson

**Comment by joeellis** [comment] 2017-11-10 21:16
Is there still interest in a PR to add such an override / warning?  I'd be interested in trying to take it on.  I am 100% in favor of keeping semver as a default and as a requirement of things that will be used as dependencies - but it is rather to have to semver things like web applications that won't be serve as a dependency for others and have frequent version changes.

I understand that web apps are not the main focus of Elixir and Mix, but with the growing popularity of Phoenix, I don't think it's crazy to have an option for them.

**Comment by ericmj** [comment] 2017-11-10 21:19
@joeellis Why can't web apps follow the semver format? What format do you want to use instead?

**Comment by joeellis** [comment] 2017-11-11 00:05
@ericmj For a web app specifically, I would version using git refs. I feel its common practice, and in a continuous delivery / deployment environment with a constant stream of daily builds where our app is in constant flux, a uniquely identifiable build version and a timeline are the two most important pieces of info needed for a given release. `git` already gives us both, and we can already use `git` itself to perform ref lookups, diagnose / bisect problems between versions, and easily tie Phoenix deployments together with other deployment tools we use (which are heavily based around git themselves).

A web app *could* use semver, sure - I don't believe it makes sense to force it across the board though. For a sizable team pushing out a sizable number of builds per day, I have a hard time understanding how an org could really enforce semver (at least the spirit behind it) to any true degree or how it would be valuable enough to be worth the extra friction on what is likely already a complicated deployment process. Either way, it feels like a decision to be left up to the organization, not the build tool.

So I do agree with @martin-langhoff that it feels strange there is a semver mandate across everything right now. As mentioned earlier, the semver req seems to only exist to solve for Hex.pm package enforcement. The typical web app will not be used as packages / dependencies, though, and users (usually) cannot control which version of the web app they use. So I think providing at least an override option makes reasonable sense.

**Comment by martin-langhoff** [comment] 2017-11-11 00:09
Using "git describe" output is damn useful. It should just work for the
internal or web app builds, including draft/scratch builds.

Not every build is of something that's tagged-and-released...

**Comment by ericmj** [comment] 2017-11-14 17:12
If you don’t intend to tag or release the version I don’t see a reason to update the version in mix.exs, if it's part of a continuous deployment it sounds even more annoying to do so.

I think your release tool should instead be able to override the version in mix.exs with a flag or similar. If this is not possible without changes in mix.exs please let us know and we can look into that.

**Comment by martin-langhoff** [comment] 2017-11-14 17:43
@ericmj we key lots of things in the version tracked in `mix.exs`. Our software gets released, so the final release gets a proper SemVer. But lots of interim builds don't -- daily builds, etc. 

The version in `mix.exs` is shown in the UI, so QA teams can report what build they repro'd a bug, or what build fixed it. It is all pretty useful.

A version is a version is a version; different people will use it differently. Seeing Elixir used in workflows you didn't expect is a feature, not a bug :-) -- passing judgement on it isn't the winning move.

(Can we workaround it? Yes, we can, and we do -- we mangle the output of `git describe`. We'd like to drop silly workarounds.)

**Comment by ericmj** [comment] 2017-11-14 17:57
> The version in mix.exs is shown in the UI, so QA teams can report what build they repro'd a bug, or what build fixed it. It is all pretty useful.

Don't use the version in mix.exs in that case you can read this string from anywhere.

> A version is a version is a version; different people will use it differently. Seeing Elixir used in workflows you didn't expect is a feature, not a bug :-) -- passing judgement on it isn't the winning move.

Knowing what format the version is is also useful. If we do not warn about the version format then you may not notice that it's invalid semver until it's used as a dependency. Keep in mind that you can fetch dependencies using git, so you will notice it with `mix hex.publish`.

Have you tried using the build part of the semver version? `1.2.3+GITHASH`.

**Comment by martin-langhoff** [comment] 2017-11-14 18:41
Yes we can make up our own "my_version" property. Seems silly given that there's a version property. mix.exs is used by apps not meant for publishing on Hex / being used/distributed as a library or reusable app or component. 

Every time you make your own "final" app, your own hello_world app, you are building something not meant for reuse, and that's a valid use case. We'd all be unemployed without it :-)

Perhaps `hex.publish` is the place to get strict about the format being SemVer?

**Comment by ericmj** [comment] 2017-11-14 19:43
Can you elaborate about why you can't use the build metadata in the semver string? Build metadata exists for this reason.

**Comment by josevalim** [comment] 2017-11-14 19:45
Can you please describe where the workflow is breaking when you use a
version that is not a semver?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by maxlapshin** [comment] 2019-09-23 14:44
We use ubuntu-like versioning:   19.04,  19.09, 19.10  and  personally me I consider that semver is a non-working technique: these versions mean nothing in practice, they do not promise anything.

So strict forcing semantic versioning is too much.

**Comment by OvermindDL1** [comment] 2019-09-23 14:49
Calver, like ubuntu uses, is best used for end-user software to see the related version between.  For things that expose API's like libraries them Semver is best as it defines how the API is compatible between versions, without necessarily saying anything about release ordering between disparate parts.

**Comment by maxlapshin** [comment] 2019-09-23 14:53
> that expose API's like libraries them Semver is best

Better to write: "I think that it would be good if and thing that exposes API will adopt SemVer in it development process"

Semver is not about versioning, it is about designing features and developing them.

Teams are moving from 1,5 year release cycle in the past to rolling deploying features and it is impossible to say then feature is already in code or not yet.

This is why a modern project that really adopts SemVer can endlessly live in something useless like 0.1.499.32

Forcing SemVer is really too strict thing.

**Comment by maxlapshin** [comment] 2019-09-23 15:11
as an example: C++ moved to calendar versioning.

Erlang itself doesn't use SemVer.

**Comment by OvermindDL1** [comment] 2019-09-23 15:34
All of those are full releases, of which calver is appropriate for, they aren't for versioned updates of features/patches in an API.

**Comment by martin-langhoff** [comment] 2019-09-23 17:44
Daily builds, CI builds. I need them to have both a version that indicates what branch or major/minor version they are "from", and a commit hash to identify uniquely. 

Not everything you build is a release :-)

**Comment by maxlapshin** [comment] 2019-09-23 17:45
```
  defp retrieve_version_from_git() do
    System.cmd("/bin/sh", ["-c", "git describe --abbrev=7 --long | sed 's/^v//g' | sed 's/\\.0/\\./g'"])
    |> elem(0)
  end
```

**Comment by maxlapshin** [comment] 2021-06-04 16:20
Seems that problem is still there and it is impossible to use calver.

It _is_ a problem.

**Comment by josevalim** [comment] 2021-06-04 19:07
It seems some wires got crossed here. Mix will enforce the versions of **Mix projects** to be semver. But your dependencies can have whatever version if you use a regex as the requirement. So we are not asking existing software to change but, if you want to work with a Mix project, then you have to follow Mix rules, and we don't plan to change this particular aspect.
