### ISSUE TITLE
Another crash in Module.Types.Of.struct/3

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12361] opened 2023-01-23 23:23 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

`mix compile` run on generated protocol structs from https://github.com/elixir-lsp/elixir-ls/pull/793 crashes

Repro:
1. Checkout https://github.com/scohen/elixir-ls/commit/7353f8c62affeb1caba72c42c5a2516a4d8f4f9d
2. `mix deps.get`
3. `cd apps/language_server`
4. `mix compile`
5. `mix lsp.mappings.generate`
6. 4. `mix compile`

Result:
```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for ElixirLS.LanguageServer.Experimental.SourceFile.apply_change/2

defp apply_change(
       %ElixirLS.LanguageServer.Experimental.SourceFile{} = source,
       %ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent{
         range: nil
       } = change
     ) do
  new_state = increment_version(new(source.uri, change.text, source.version))
  {:ok, new_state}
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.__struct__/0 is undefined or private
        ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.__struct__()
        (elixir 1.14.3) lib/module/types/of.ex:131: Module.Types.Of.struct/3
        (elixir 1.14.3) lib/module/types/pattern.ex:754: Module.Types.Pattern.of_shared/4
        (elixir 1.14.3) lib/module/types/pattern.ex:47: Module.Types.Pattern.of_pattern/3
        (elixir 1.14.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.14.3) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
        (elixir 1.14.3) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
        (elixir 1.14.3) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5

```

Note there are duplicated modules

Earlier similar issues:

- https://github.com/elixir-lang/elixir/issues/12113
- https://github.com/elixir-lang/elixir/issues/12054
- https://github.com/elixir-lang/elixir/issues/11547
- https://github.com/elixir-lang/elixir/issues/10784
- https://github.com/elixir-lang/elixir/issues/10584
- https://github.com/elixir-lang/elixir/issues/10535

### Expected behavior

No crash

**Comment by AndreasBergmanOP** [comment] 2023-01-25 13:23
I have an similar issue regarding this. Im currently testing a struct but when i create the basic struct.

```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for MyApp.Applications.ApplicationTest."test Application flow: delete cascade"/1

def test Application flow: delete cascade(%{conn: conn}) do
  (
    changeset =
      MyApp.Applications.Application.changeset(
        %MyApp.Applications.Application{
          __meta__: %{
            __struct__: Ecto.Schema.Metadata,
            context: nil,
            prefix: nil,
            schema: MyApp.Applications.Application,
            source: "application",
            state: :built
          },
          data_attributes: %{
            __cardinality__: :many,
            __field__: :data_attributes,
            __owner__: MyApp.Data.Attributes,
            __struct__: Ecto.Association.NotLoaded
          },
          id: nil,
          inserted_at: nil,
          name: nil,
          owner: %{
            __cardinality__: :one,
            __field__: :owner,
            __owner__: MyApp.Applications.Application,
            __struct__: Ecto.Association.NotLoaded
          },
        },
        %{name: "test"}
      )

    IO.inspect(changeset)
  )

  :ok
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function MyApp.Applications.Application.__struct__/0 is undefined or private
        (MyApp 4.0.0) MyApp.Applications.Application.__struct__()
        (elixir 1.14.2) lib/module/types/of.ex:131: Module.Types.Of.struct/3
        (elixir 1.14.2) lib/module/types/expr.ex:197: Module.Types.Expr.of_expr/4
        (elixir 1.14.2) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.14.2) lib/module/types/expr.ex:403: Module.Types.Expr.of_expr/4
        (elixir 1.14.2) lib/module/types/expr.ex:140: Module.Types.Expr.of_expr/4
        (elixir 1.14.2) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.14.2) lib/module/types/expr.ex:213: Module.Types.Expr.of_expr/4
        (elixir 1.14.2) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.14.2) lib/module/types/expr.ex:213: Module.Types.Expr.of_expr/4
        (elixir 1.14.2) lib/module/types.ex:63: Module.Types.warnings_from_clause/6
        (elixir 1.14.2) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.14.2) lib/enum.ex:4249: Enum.flat_map_list/2
        (elixir 1.14.2) lib/module/parallel_checker.ex:233: Module.ParallelChecker.check_module/2
        (elixir 1.14.2) lib/module/parallel_checker.ex:78: anonymous fn/5 in Module.ParallelChecker.spawn/3
```

**Comment by josevalim** [comment] 2023-02-13 12:26
@lukaszsamson unfortunately I cannot reproduce this because the linked commit does not exist in any branch: https://github.com/scohen/elixir-ls/commit/7353f8c62affeb1caba72c42c5a2516a4d8f4f9d

I assume it was erased or similar. If you or @scohen still have it locally, can you please push somewhere?

**Comment by scohen** [comment] 2023-02-13 17:32
@josevalim that code is in the `master` branch now.

**Comment by josevalim** [comment] 2023-02-17 10:53
The module `ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent` is defined in two places and, in one of them, it is definitely not a struct:

* apps/language_server/lib/generated/language_server/experimental/protocol/types/text_document/content_change_event.ex:1

* apps/language_server/lib/language_server/experimental/protocol/types.ex:45

So the error message is correct. :)

**Comment by josevalim** [comment] 2023-02-17 11:11
I will close this for now. We could change the error message to ask them to not report a bug but that may hide legitimate cases, so we will continue collecting reports for now. Thank you!

**Closed by josevalim** 2023-02-17 11:11 UTC
Labels: Note:Needs more info
