### ISSUE TITLE
Elixir eats error when using macro pulls in pipelines.

### ISSUE THREAD

**Issue by valevalorin** [elixir-lang/elixir#3373] opened 2015-06-03 15:46 UTC
So, when trying to organize my Phoenix router I wanted to move my pipelines into a different module, then I wanted to use a macro to pull them all back in. The pipeline module looks something like this:

```elixir
defmodule OpenAperture.ModelPipelines do

 defmacro __using__(_) do
    quote do
      alias OpenAperture.Manager.DB.Models
      alias OpenAperture.Manager.DB.Queries
      alias OpenAperture.Manager.Plugs
      alias OpenAperture.Manager.Repo

      pipeline :find_cluster, do: plug(Plugs.GetModel, [Models.EtcdCluster, "etcd_token", &Queries.EtcdCluster.get_by_etcd_token(&1)])
      #More pipelines follow
```

When I try to run my server with more than pipeline in this macro I get the following error:

```
== Compilation error on file web/router.ex ==
** (FunctionClauseError) no function clause matching in :elixir_errors.handle_file_error/2
    (elixir) src/elixir_errors.erl:177: :elixir_errors.handle_file_error("elixir_compiler_32", {:beam_validator, {{:elixir_compiler_32, :__MODULE__, 1}, {{:call_ext, 1, {:extfunc, RuntimeError, :exception, 1}}, 257, :ambiguous_catch_try_state}}})
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

I'd like to figure out how to get my macro working but without exceptions to tell me what's wrong I'm having a really hard time doing that.

**Comment by ericmj** [comment] 2015-06-03 16:00
Duplicate of #3225. It's a bug in OTP, the fix will be included in the OTP 18 release.

**Closed by ericmj** 2015-06-03 16:00 UTC
