### ISSUE TITLE
(ArgumentError) argument error

### ISSUE THREAD

**Issue by kishorevaishnav** [elixir-lang/elixir#6981] opened 2017-10-26 22:46 UTC
I am very new to this so pardon me if I should not report this here.

### Environment
* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0-dev (4b930b0a0) (compiled with OTP 20)
```

* Operating system: **macOS Sierra Version 10.12.6**

### Current behavior
Compile fails in the Phoenix app and the error is
```
Generated postgrex app
==> ecto
Compiling 69 files (.ex)
warning: function slice/1 required by protocol Enumerable is not implemented (in module Enumerable.Ecto.Adapters.SQL.Stream)
  lib/ecto/adapters/sql/stream.ex:12


== Compilation error in file lib/ecto/adapters/postgres/connection.ex ==
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:322: :erl_anno.set(:generated, false, {"lib/ecto/adapters/postgres/datetime.ex", 48})
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

I tried all the above-mentioned options, but none worked out:
`mix deps.compile ecto`
`mix deps.update ecto`
`mix deps.clean ecto`

I even tried to delete `~/.hex/packages/hexpm` & `_build` and executed `mix deps.get`. But still it failed to compile when I used `iex -S phoenix.server`

Note: When I rollback to one previous commit https://github.com/elixir-lang/elixir/commit/47dcba9e1f790fd328d7bf5ad856a8f593f0e9e4 , it works fine.

### Expected behavior
Upgrading to the latest elixir version should not stop compiling the dependency **ecto**. The error is caused by this https://github.com/elixir-lang/elixir/commit/4b930b0a0 particular version onwards. The Phoenix app compiles prior to this revision without stop compiling though there are few warnings.

**Comment by OvermindDL1** [comment] 2017-10-26 23:01
Duplicate of https://github.com/elixir-lang/elixir/issues/6980#event-1312969177
And closed (just now) by josevalim in:  https://github.com/elixir-lang/elixir/commit/ba19fc8e50263199e75b0131714e1f65bb9ea427

:-)

**Closed** 2017-10-26 23:03 UTC

**Comment by josevalim** [comment] 2017-10-26 23:07
Btw, if you are new to Elixir, you should probably use a stable release instead of master. :)

**Comment by kishorevaishnav** [comment] 2017-10-26 23:22
@josevalim thanks for fixing this immediately. I tested with the https://github.com/elixir-lang/elixir/commit/ba19fc8e50263199e75b0131714e1f65bb9ea427 and **ITS WORKING**.
I like the formatting feature and hence I was in the `master`.
