### ISSUE TITLE
`mix deps.tree` hangs

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#13702] opened 2024-07-02 08:35 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

Mac OS

### Current behavior

After installing 1.17.1 (from 1.17.0) I ran `mix deps.tree` immediatelly. It just hang. Running `mix` then asked me to install hex and compiled the project. Running `mix deps.tree` afterwards worked as expected.

### Expected behavior

The mix task detecting what made it hang and either reporting that to the user or solving it.

**Comment by josevalim** [comment] 2024-07-06 21:04
I could not reproduce it. Can you reproduce it by running `mix archive.uninstall hex` and then `mix deps.tree` in the same project?

**Comment by LostKobrakai** [comment] 2024-07-07 20:54
It doesn't seem to reproduce that way. It asks me to install hex after uninstalling the archive.

**Comment by josevalim** [comment] 2024-07-07 23:28
Thanks for the reply. Can you provide any consistent way of reproducing it?

**Comment by LostKobrakai** [comment] 2024-07-08 06:59
I tried with uninstalling and reinstalling 1.17.1 completely. That worked as expected as well. I don't think I have any more details to improve my chances at reproducing this.

**Comment by josevalim** [comment] 2024-09-18 10:06
I will close this. If someone can reproduce it, I will gladly take a look at it. :)

**Closed by josevalim** 2024-09-18 10:06 UTC
Labels: Kind:Bug, App:Mix
