### ISSUE TITLE
Elixir v1.1.0-dev Build fails on MacOSX 10.10.2 - unit test system_test failed

### ISSUE THREAD

**Issue by schaary** [elixir-lang/elixir#3044] opened 2015-02-02 19:57 UTC
This ist the first time I've tried to compile Elixir. So there is nothing left from earlier experiments. I copy&pasted the commands from github README.md:

1. git clone https://github.com/elixir-lang/elixir.git
2. cd elixir
3. make clean test

Here is the result:

[...]
Generated iex.app
==> elixir (eunit)
  All 198 tests passed.

==> elixir (exunit)
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test cmd/1 (SystemTest)
     test/elixir/system_test.exs:62
     Expected to catch error, got nothing
     stacktrace:
       test/elixir/system_test.exs:76

.............................................................

Finished in 9.4 seconds (6.7s on load, 2.7s on tests)
1830 tests, 1 failures

Randomized with seed 612885
make: *** [test_stdlib] Error 1
schaary@solaris ~/t/elixir [master]> erl --version
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V6.3  (abort with ^G)

**Comment by jw2013** [comment] 2015-02-03 09:18
I think the cause is probably relative_to_cwd gives the original full path back somehow according to the spec:
https://github.com/elixir-lang/elixir/blob/ea31bc3b30b32757182155047f1d5abf58bc17f9/lib/elixir/lib/path.ex#L305

Since `echo2 = tmp_path("echo2")` is in absolute path, in the case I described above relative_to_cwd can give back the original path so we have variable `relative` also the original absolute path, and thus (System.cmd(relative, ["hello"]) runs fine without throwing error.

I think depending on whether variable `relative` is an absolute path or not, we should test these two cases separately (`relative` is an absolute path -> {"hello\n", 0}; else -> :enoent).

**Comment by schaary** [comment] 2015-02-03 19:36
Sorry - the fix does not solve the problem:

1. clone from github
2. cd elixir
3. make clean test 

[...]

Generated iex.app
==> elixir (eunit)
  All 198 tests passed.

==> elixir (exunit)
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test cmd/1 (SystemTest)
     test/elixir/system_test.exs:62
     Expected to catch error, got nothing
     stacktrace:
       test/elixir/system_test.exs:80

..........................................................................................................................................................................................

Finished in 9.3 seconds (6.6s on load, 2.7s on tests)
1830 tests, 1 failures

Randomized with seed 709201
make: *** [test_stdlib] Error 1
schaary@solaris ~/t/elixir [master]> erl --version
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V6.3  (abort with ^G)
1>

**Comment by josevalim** [comment] 2015-02-03 19:44
What does `pwd hello` returns in your machine? Maybe you have a script in your path named hello? We should probably name it to something more unlikely to match anyway. :D

**Comment by schaary** [comment] 2015-02-03 20:26
schaary@solaris ~/t/elixir [master]> pwd hello
/Users/schaary/tmp/elixir

**Comment by josevalim** [comment] 2015-02-03 20:27
That's the issue. I think we aborted in the middle of the test (or the test failed) and the original hello command was not cleaned up. :S

**Comment by josevalim** [comment] 2015-02-05 01:47
Can you please remove the hello file from the elixir directory and check if your tests pass?

**Comment by schaary** [comment] 2015-02-05 10:27
There is no file called 'hello' on my whole computer ;)

Honestly - the command `pwd hello' delivers always the the current working directory. I've tested this on macosx, ubuntu 14.04.01 LTS, openSuSE and SLES.

**Comment by josevalim** [comment] 2015-02-05 11:45
Ah, yes. I have no idea why this is happening then. :S

**Comment by josevalim** [comment] 2015-02-05 11:48
Can you please run `bin/iex` and type `System.find_executable("hello")` and let us know what it returns?

**Comment by schaary** [comment] 2015-02-05 11:59
schaary@solaris ~> cd tmp/elixir/
total 424
-rw-r--r--   1 schaary  staff   2,8K  3 Feb 21:30 CHANGELOG.md
-rw-r--r--   1 schaary  staff   8,8K  3 Feb 21:30 CONTRIBUTING.md
-rw-r--r--   1 schaary  staff   309B  3 Feb 21:30 LEGAL
-rw-r--r--   1 schaary  staff   571B  3 Feb 21:30 LICENSE
-rw-r--r--   1 schaary  staff   7,5K  3 Feb 21:30 Makefile
-rw-r--r--   1 schaary  staff   2,8K  3 Feb 21:30 README.md
-rw-r--r--   1 schaary  staff   1,3K  3 Feb 21:30 RELEASE.md
-rw-r--r--   1 schaary  staff     9B  3 Feb 21:30 VERSION
drwxr-xr-x  11 schaary  staff   374B  3 Feb 21:30 bin
drwxr-xr-x   8 schaary  staff   272B  3 Feb 21:30 lib
-rwxr-xr-x   1 schaary  staff   161K  3 Feb 21:30 rebar
-rw-r--r--   1 schaary  staff   671B  3 Feb 21:30 rebar.config
drwxr-xr-x   3 schaary  staff   102B  3 Feb 21:30 src
schaary@solaris ~/t/elixir [master]> iex
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.find_executable("hello")
nil
iex(2)>

**Comment by josevalim** [comment] 2015-03-10 09:24
I am not sure how to proceed here. I have played with this yesterday and I cannot reproduce it, so I am unable to fix the issue. I am closing this, if someone has specific steps to reproduce this, it would be appreciated. Thank you.

**Closed by josevalim** 2015-03-10 09:24 UTC
