### ISSUE TITLE
Task.async_stream with timeout: :infinity

### ISSUE THREAD

**Issue by Gringill** [elixir-lang/elixir#6388] opened 2017-07-26 17:38 UTC
### Environment

osx Sierra 10.12.5

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0
```

### Current behavior

```
Task.async_stream([1], fn x -> x end, [timeout: :infinity]) |> Enum.to_list
** (EXIT from #PID<0.87.0>) evaluator process exited with reason: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.send_after(:infinity, #PID<0.89.0>, {:timeout, {#Reference<0.838740286.2719219716.152843>, #Reference<0.838740286.2719219716.152848>}})
        (elixir) lib/task/supervised.ex:408: Task.Supervised.stream_monitor_loop/2


12:34:23.984 [error] Process #PID<0.89.0> raised an exception
** (ArgumentError) argument error
    :erlang.send_after(:infinity, #PID<0.89.0>, {:timeout, {#Reference<0.838740286.2719219716.152843>, #Reference<0.838740286.2719219716.152848>}})
    (elixir) lib/task/supervised.ex:408: Task.Supervised.stream_monitor_loop/2
```

### Expected behavior

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.5
```

```
Task.async_stream([1], fn x -> x end, [timeout: :infinity]) |> Enum.to_list
[ok: 1]
```

I would imagine that the send_after should not occur when timeout is `:infinity`, seems like a regression.

Hopefully I am not missing something here, like intentional dropping of support for `:infinity`, but I did not catch anything in the changelog.

**Comment by michalmuskala** [comment] 2017-07-26 17:40
Duplicate of https://github.com/elixir-lang/elixir/pull/6382

**Comment by Gringill** [comment] 2017-07-26 17:41
Drat, searched the bugs in issues not the forums :). Thanks!

**Closed** 2017-07-26 17:41 UTC
