### ISSUE TITLE
Compiler crashes when using a macro before its definition

### ISSUE THREAD

**Issue by pdobacz** [elixir-lang/elixir#8939] opened 2019-04-05 15:35 UTC
Hello, I recently stumbled upon what looks like a compiler crash. Reporting in case its of interest:

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

I'm getting the same result on both:

```
$ elixir --version
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 20)
```

and

```
$ elixir --version
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

* Operating system: Ubuntu 18.04

### Current behavior

The following code seems to crash the compiler:

```elixir
defmodule MyModule do
  def f(), do: m()

  defmacro m do
    quote do
      []
    end
  end
end
```

Then:

```
$ mix compile application
==> application
Compiling 1 file (.ex)
Function f/0 refers to undefined label 15

== Compilation error in file lib/module.ex ==
** (CompileError) lib/module.ex: internal error in beam_dead;
crash reason: {case_clause,{'EXIT',{undefined_label,15}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 439)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Expected behavior

Either a successful compile or a compilation error telling me what I did wrong (I suspect that the "did wrong" part is the order of `f` and `m` - reverse the order and it compiles)

**Comment by wojtekmach** [comment] 2019-04-05 15:39
I believe it's a duplicate of https://github.com/elixir-lang/elixir/issues/8626 and it's already fixed on master!

**Comment by josevalim** [comment] 2019-04-05 15:39
Yup, it has been fixed in master and it should be out in the next release!

**Closed by josevalim** 2019-04-05 15:39 UTC
