### ISSUE TITLE
Add Logger.capture_log(backend, opts, fn)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3313] opened 2015-05-08 11:27 UTC
See discussion here: https://groups.google.com/forum/#!topic/elixir-lang-talk/cEWHayk45cw

**Comment by lexmag** [comment] 2015-05-17 15:36
Hey @MSch, I've seen you have done some work on this issue (gisted in the mailing list), I'd like to give it a shot if you are not planning to proceed.

**Comment by MSch** [comment] 2015-05-18 09:39
I was hoping to convince @josevalim / @fishcakez that `Logger.capture_log(backend, opts, fn)` is the wrong API, because replacing a specific backend (though most of the time `:console`) is not what people actually want in their tests.

There are two use cases I see:

1. Suppressing log messages to keep the output of test runs "clean": IMO the right approach here would be to remove the `:console` backend and have a hook into ExUnit that makes it capture all logs for each test, discarding them if the test succeeds and printing them if the test fails along with the rest of the failure message.

2. Checking if certain messages are logged: If this is implemented by replacing the `:console` backend then the test case can no longer be async if there's another async test case that also uses `capture_log`. I also don't see the advantage of implementing this by replacing `:console` instead of just adding a "capturing backend", if log messages from successful tests are suppressed anyhow like in 1 (which we've done in our code base and which is IMO awesome).

**Comment by josevalim** [comment] 2015-05-18 09:47
We can't implement 1, concurrently, can we? You will still have multiple tests running AND they will be triggering other servers that are writing to logger. It would be impossible to know which one is each.

**Comment by MSch** [comment] 2015-05-18 09:52
We can, it'll just capture log messages from the other concurrently running tests as well. Which is IMO good enough for the first error message (say from Travis), once you then locally run only the one test (case) that fails to reproduce and fix the issue it'll just be the log messages for that test.

**Comment by josevalim** [comment] 2015-05-18 09:59
@MSch hrm, I am not confident but we can wait feedback from other folks. I can see though that choosing a particular backend wouldn't allow 1 to be implemented. Maybe we can have two functions: capture_log and replace_log? capture_log just adds a new backend for that particular moment and replace_log is a tiny function on top of it that replaces the given log (usually console).

The other topic is if we should keep the same level as the replaced by backend. I would say no, because we don't provide an unified way to retrieve the level, but we could discuss it.

**Comment by MSch** [comment] 2015-05-18 10:14
@josevalim I'd be ok with that, because it lets me do my thing. Thanks! (Of course I believe everyone would profit from "opportunistic debug logging" :) )

The way I see it it's strictly better to implement 1, even if it intersperses log messages from other concurrent tests:

1. If you don't need the (debug) log messages to figure out the failing test, it clutters the failure message but doesn't hurt otherwise.

2. If you need the (debug) log messages to figure out the failing test, then not having them when a test fails on Travis/Jenkins (because the log level is all or nothing for the whole test run, so setting it to `:debug` just makes the output hard to read) is making diagnosing what went wrong impossible or at least requires (even more) guesswork. If you're dealing with intermittent errors (e.g. two concurrent tests that sometimes get in each others way or any other race) then not having the log messages when the failure happens is annoying.

That is what happened to us and why we implemented 1. At first we just added a `Logger.debug "starting test #{test[:name]}"` / `Logger.debug "finished test #{test[:name]}"` and set the log level to `:debug`, which already helped but produced a lot of test output and was really annoying. From there to "opportunistic debug logging" was an easy step.

I also think we should not keep the same level as the replaced backend, IMO `capture_log` should default to `:debug` and have an option to choose a different level.

**Comment by fishcakez** [comment] 2015-05-18 12:12
> Suppressing log messages to keep the output of test runs "clean": IMO the right approach here would be to remove the :console backend and have a hook into ExUnit that makes it capture all log messages for each test, discarding them if the test succeeds and printing them if the test fails along with the rest of the failure message.

This could be handled in a different manor by using a combination of an ExUnit formatter and Logger backends. An ExUnit formatter (http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Formatter.html) can remove `:console` (and/or other Logger backend) on a `suite_started` event and re-add on `suite_finished` or `terminate/2`.

This formatter can then add/remove a capturing backend per test. On receiving a test failure it can call `Logger.flush/0` and then call the backend for that test to print the captured logs. This will mean the formatting of logs is much clearer on the screen because the log messages will be printed together as a batch and (if no other io) immediately before or after next the failure messages printed by normal CLI formatter even with asynchronous tests.

For this is to work it would require that events sent to `ExUnit.EventManager` use `sync_notify` rather than `notify` so that the backend is added before beginning the test. Similar race conditions may already be present with custom or the built in CLI formatters.

This could be made more advanced by adding a group leader per suite, case and test that forwards IO to its group leader. If the group leader was included in the case/test struct the capturing Logger backend could identify all log messages sent by its test or processes spawned by its test because the group leader is included in a Logger event.

I can imagine this being used by other custom formatters. For example `:stdio` I/O and logs could be written to one file per case or test. `common_test` has a similar feature and I assume this is how it works.

**Comment by MSch** [comment] 2015-05-18 12:17
> For this is to work it would require that events sent to ExUnit.EventManager use sync_notify rather than notify so that the backend is added before beginning the test.

I hacked around this by having the log capturing server wait on a call in `setup`/`on_exit` but changing `ExUnit.EventManager` would indeed be nicer :)

@fishcakez So do you think this is a good thing to have?

**Comment by fishcakez** [comment] 2015-05-18 12:32
For displaying logs in `ex_unit` I think this would be a good feature. It doesn't help for comparing logs though. However it should be possible to implement `capture_log` using the same backend.

**Comment by fishcakez** [comment] 2015-06-01 15:48
I have assigned to myself but @lexmag is probably going to do most of the work.

**Closed** 2015-06-30 10:28 UTC
Labels: App:Logger, Kind:Feature, Level:Advanced
