### ISSUE TITLE
Lack of warning(s) when application in umbrella has a higher Elixir version specified

### ISSUE THREAD

**Issue by blaketan** [elixir-lang/elixir#7236] opened 2018-01-20 00:01 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  1.5.2, OTP 20.1
* Operating system:  Mac OSX

### Current behavior
I'm upgrading my umbrella application from 1.5.2 to 1.6.0, and 1 of more applications in the umbrella will rely on new features in 1.6. I'd like to enforce the constraint that Elixir 1.6 needs to be installed.

While on 1.5.2, I tried changing an application's `mix.exs` to this:
```
defmodule NestedApp.Mixfile do
  use Mix.Project

  def project do
    [
      app: :nested_app,
      version: "0.1.0",
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      elixir: "~> 1.6",
      start_permanent: Mix.env == :prod,
      deps: deps()]
  end
...
end
```
This is the project's root mixfile, generated using `mix new my_umbrella --umbrella`
```
defmodule MyUmbrella.Mixfile do
  use Mix.Project

  def project do
    [apps_path: "apps",
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end
...
end
```
When calling `iex -S mix` from the project's root folder, all applications start up properly.

I verified that when I included `elixir: "~> 1.6"` in the root mixfile, I received a proper warning.

`** (Mix) You're trying to run MyUmbrella.Mixfile on Elixir v1.5.1 but it has declared in its mix.exs file it supports only Elixir ~> 1.6`

### Expected behavior
If a nested application in an umbrella has a higher elixir version requirement than what is currently installed, prevent startup.

Or `mix new <APP> --umbrella` should always generate an umbrella project's mixfile with `elixir: "<CURRENT_VERSION>`to prevent confusion.

**Comment by josevalim** [comment] 2018-01-20 22:47
This is tricky. Today we have it inside "loadpaths" but that task is only invoked for the current application. We could move it inside "compile.elixir" but then it won't be invoked if you are not compiling the project, such as in production under the --no-compile flag. So I am more inclined to mark it as won't fix because there is nowhere else to move it without drawbacks.

Thanks for the report!

**Comment by blaketan** [comment] 2018-01-22 23:37
I understand. Maybe an easy workaround would be for the `mix new <APP> --umbrella` task to generate the root `mix.exs` project with a `elixir: <VERSION>` line?

**Comment by josevalim** [comment] 2018-01-23 08:41
@blaketan I know some applications do it but I don't want to add yet another place for adding configuration in an umbrella. :(

**Comment by josevalim** [comment] 2018-06-28 17:10
So after a deeper look we actually emit this warnings when compiling a dependency in deps.compile. The issue is that the `compile` task is made recursive, so we never invoke deps.compile for deps. We can't really check for umbrella inside the `compile` task (we have made it on purpose so a project doesn't know it is inside an umbrella to avoid special casing behaviour), so I am afraid we will be unable to fix this issue.

In any case, thanks for the report @blaketan!

**Closed by josevalim** 2018-06-28 17:10 UTC
Labels: App:Mix, Kind:Bug
