### ISSUE TITLE
No compilation failure unless you release

### ISSUE THREAD

**Issue by MTheProgrammer** [elixir-lang/elixir#11389] opened 2021-11-13 05:29 UTC
### Precheck

Hello, I'm using [Quantum lib](https://github.com/quantum-elixir/quantum-core) for my project and while app compiles without any issue, there is a problem with building release. I've figured out that different syntax in Quantum config does work and the problem lays in generated `sys.config` file (I've replaced app name with my_app and MyApp).

Failing sys.config
```
{my_app,[{'Elixir.MyApp.Scheduler',[{jobs,[{<<48,32,42,32,42,32,42,32,42>>,#Fun<erl_eval.45.79398840>}]}]}
```
Valid sys.config
```
{my_app,[{'Elixir.MyApp.Scheduler',[{jobs,[{reset_password_token_cleaner,[{schedule,<<48,32,42,32,42,32,42,32,42>>},{task,{'Elixir.MyApp.Users',clear_expired_reset_password_tokens,[1000]}}]}]}]}
```

I've validated this file with `:file.consult/1` function:
```
{:error, {3, :erl_parse, ['syntax error before: ', 'Fun']}}
```

Quantum scheduler config that is passing the compilation, but fails during release:
```
config :my_app, MyApp.Scheduler,
  jobs: [
    {"0 * * * *", fn -> MyApp.Users.clear_expired_reset_password_tokens(1000) end}
  ]
```
Quantum scheduler config that passes both compilation and release:
```
config :my_app, MyApp.Scheduler,
  jobs: [
    reset_password_token_cleaner: [
      schedule: "0 * * * *",
      task: {MyApp.Users, :clear_expired_reset_password_tokens, [1000]}
    ]
  ]
```
As you can see, the difference is that the first config uses anonymous function and the second is a [named job](https://hexdocs.pm/quantum/configuration.html#named-jobs).

### Environment

* Elixir 1.12.3
* Phoenix 
* Operating system: 

### Current behavior
Release fails in the last stage with hard to debug exception.
```
* assembling prod-0.7.4 on MIX_ENV=prod
* using config/runtime.exs to configure the release at runtime
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Config.Provider{config_path: {:system, "RELEASE_SYS_CONFIG", ".config"}, extra_config: [], providers: [{Config.Reader, {{:system, "RELEASE_ROOT", "/releases/0.7.4/runtime.exs"}, [env: :prod, target: :host, imports: :disabled]}}], prune_runtime_sys_config_after_boot: false, reboot_system_after_config: false, validate_compile_env: false} of type Config.Provider (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, IO.Stream, Map, Stream, File.Stream, MapSet, HashDict, Date.Range, List, GenEvent.Stream, Range, Function, HashSet
    (elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.12.3) lib/enum.ex:342: Enum.all?/2
    (mix 1.12.3) lib/mix/release.ex:424: anonymous fn/3 in Mix.Release.make_sys_config/3
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.12.3) lib/mix/release.ex:422: Mix.Release.make_sys_config/3
    (mix 1.12.3) lib/mix/tasks/release.ex:1189: Mix.Tasks.Release.build_rel/2
    (mix 1.12.3) lib/mix/tasks/release.ex:1087: Mix.Tasks.Release.assemble/1
```
File sys.config
```
%% coding: utf-8
%% RUNTIME_CONFIG=false
[{esbuild,[{version,<<48,46,49,50,46,49,56>>},{default,[{args,[<<106,115,47,97,112,112,46,106,115>>,<<45,45,98,117,110,100,108,101>>,<<45,45,116,97,114,103,101,116,61,101,115,50,48,49,54>>,<<45,45,111,117,116,100,105,114,61,46,46,47,112,114,105,118,47,115,116,97,116,105,99,47,97,115,115,101,116,115>>,<<45,45,101,120,116,101,114,110,97,108,58,47,102,111,110,116,115,47,42>>,<<45,45,101,120,116,101,114,110,97,108,58,47,105,109,97,103,101,115,47,42>>]},{cd,<<47,104,111,109,101,47,109,97,99,105,101,106,47,80,114,111,106,101,99,116,115,47,101,108,105,120,105,114,47,103,111,117,45,103,111,117,45,101,108,120,47,97,115,115,101,116,115>>},{env,#{<<78,79,68,69,95,80,65,84,72>> => <<47,104,111,109,101,47,109,97,99,105,101,106,47,80,114,111,106,101,99,116,115,47,101,108,105,120,105,114,47,103,111,117,45,103,111,117,45,101,108,120,47,100,101,112,115>>}}]}]},{dart_sass,[{version,<<49,46,51,57,46,48>>},{default,[{args,[<<99,115,115,47,97,112,112,46,115,99,115,115>>,<<46,46,47,112,114,105,118,47,115,116,97,116,105,99,47,97,115,115,101,116,115,47,97,112,112,46,99,115,115>>]},{cd,<<47,104,111,109,101,47,109,97,99,105,101,106,47,80,114,111,106,101,99,116,115,47,101,108,105,120,105,114,47,103,111,117,45,103,111,117,45,101,108,120,47,97,115,115,101,116,115>>}]}]},{event_bus,[{topics,[user_created]},{ttl,30000000},{time_unit,microsecond},{id_generator,'Elixir.EventBus.Util.Base62'}]},{money,[{default_currency,twd}]},{phoenix,[{json_library,'Elixir.Jason'}]},{my_app,[{'Elixir.MyApp.Scheduler',[{jobs,[{<<48,32,42,32,42,32,42,32,42>>,#Fun<erl_eval.45.79398840>}]}]},{'Elixir.MyApp.Mailer',[{adapter,'Elixir.Bamboo.LocalAdapter'},{hackney_opts,[{recv_timeout,60000},{connect_timeout,60000}]}]},{ecto_repos,['Elixir.MyApp.Repo']},{system_host,<<104,116,116,112,115,58,47,47,103,111,117,103,111,117,46,99,97,115,104>>},{system_email_from,<<110,111,45,114,101,112,108,121,64,103,111,117,103,111,117,46,99,97,115,104>>},{system_media_dir,<<47,104,111,109,101,47,109,97,99,105,101,106,47,80,114,111,106,101,99,116,115,47,101,108,105,120,105,114,47,103,111,117,45,103,111,117,45,101,108,120,47,97,115,115,101,116,115,47,109,101,100,105,97>>},{'Elixir.MyApp.Repo',[{migration_primary_key,[{type,uuid}]},{migration_timestamps,[{type,utc_datetime_usec}]}]},{'Elixir.MyAppWeb.AdminGuardian',[{issuer,<<103,111,117,95,119,101,98,95,97,100,109,105,110>>},{secret_key,<<105,76,78,99,67,103,66,53,50,121,57,73,121,114,97,100,68,103,115,57,71,121,115,69,49,110,87,104,107,110,82,47,76,98,104,81,121,118,51,52,78,70,114,117,73,89,79,67,51,89,98,53,68,52,101,78,68,66,54,82,51,56,118,90>>}]},{'Elixir.MyAppWeb.Guardian',[{allowed_algos,[<<72,83,53,49,50>>]},{verify_module,'Elixir.Guardian.JWT'},{issuer,<<103,111,117,95,119,101,98>>},{token_ttl,#{<<97,99,99,101,115,115>> => {15,minutes},<<114,101,102,114,101,115,104>> => {4,weeks}}},{allowed_drift,2000},{verify_issuer,true},{secret_key,<<49,55,54,102,48,51,54,102,100,50,53,57,49,97,52,97,49,52,100,55,50,57,55,53,51,53,99,51,98,49,99,51,98,97,98,52,57,51,50,57,56,100,52,100,51,50,53,102,97,54,101,48,97,54,55,99,48,56,48,98,100,97,49,52,50,102,101,53,98,57,55,52,99,55,102,49,53,51,56,51,52,52,57,97,52,57,99,98,49,48,97,56,99,97,52,51,54,55,52,100,50,51,54,98,99,48,53,57,99,56,99,49,57,49,57,51,53,97,49,53,98,100,99,99,55,100,54,53>>},{serializer,'Elixir.MyAppWeb.Guardian'}]},{'Elixir.MyAppWeb.Endpoint',[{secret_key_base,<<55,68,99,52,121,74,112,73,105,68,68,77,112,119,65,57,99,68,100,65,76,116,72,113,57,74,70,107,84,73,89,122,56,87,52,103,108,51,79,84,75,48,104,111,50,108,114,49,43,98,79,110,86,70,76,72,88,113,78,79,74,50,102,119>>},{render_errors,[{view,'Elixir.MyAppWeb.ErrorView'},{accepts,[<<106,115,111,110>>]},{layout,false}]},{pubsub_server,'Elixir.MyApp.PubSub'},{live_view,[{signing_salt,<<70,54,119,69,83,53,49,83>>}]},{url,[{host,<<97,112,105,46,103,111,117,103,111,117,46,99,97,115,104>>},{port,443}]},{cache_static_manifest,<<112,114,105,118,47,115,116,97,116,105,99,47,99,97,99,104,101,95,109,97,110,105,102,101,115,116,46,106,115,111,110>>}]}]},{logger,[{console,[{format,<<36,116,105,109,101,32,36,109,101,116,97,100,97,116,97,91,36,108,101,118,101,108,93,32,36,109,101,115,115,97,103,101,10>>},{metadata,[request_id]}]},{level,info}]},{elixir,[{config_provider_init,#{'__struct__' => 'Elixir.Config.Provider',config_path => {system,<<82,69,76,69,65,83,69,95,83,89,83,95,67,79,78,70,73,71>>,<<46,99,111,110,102,105,103>>},extra_config => [],providers => [{'Elixir.Config.Reader',{{system,<<82,69,76,69,65,83,69,95,82,79,79,84>>,<<47,114,101,108,101,97,115,101,115,47,48,46,55,46,52,47,114,117,110,116,105,109,101,46,101,120,115>>},[{env,prod},{target,host},{imports,disabled}]}}],prune_runtime_sys_config_after_boot => false,reboot_system_after_config => false,validate_compile_env => false}}]}].
```
### Expected behavior
Compiler displays more verbose error.

**Comment by josevalim** [comment] 2021-11-13 08:07
This has been fixed in the main/v1.13 branches! The issue is that we indeed do not support anonymous functions in the release configuration, and we were detecting such case, but we were failing to show a proper error message. So going with the MFA is the way to go!

**Closed by josevalim** 2021-11-13 08:07 UTC
