### ISSUE TITLE
1.17.3 two failing tests

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#13849] opened 2024-09-21 12:56 UTC
### Elixir and Erlang/OTP versions

1.17.3

### Operating system

Mac OS, Ubuntu 22

### Current behavior

Currently, the following two tests are failing on my mac, as well as on github ci:

```
==> logger (ex_unit)
Running ExUnit with seed: 754626, max_cases: 20

.............................

  1) test translates Supervisor progress (Logger.TranslatorTest)
     test/logger/translator_test.exs:948
     Assertion with =~ failed
     code:  assert capture_log(:info, fn ->
              ref = Process.monitor(pid)
              Supervisor.start_child(pid, worker(Task, [__MODULE__, :sleep, [self()]]))
              Process.exit(pid, :normal)

              receive do
                {:DOWN, ^ref, _, _, _} -> :ok
              end
            end) =~ ~r"\[info\] Child Task of Supervisor #PID<\d+\.\d+\.\d+> \(Supervisor\.Default\) started
            Pid: #PID<\d+\.\d+\.\d+>
            Start Call: Task.start_link\(Logger.TranslatorTest, :sleep, \[#PID<\d+\.\d+\.\d+>\]\)
            "
     left:  ""
     right: ~r/\[info\] Child Task of Supervisor #PID<\d+\.\d+\.\d+> \(Supervisor\.Default\) started\nPid: #PID<\d+\.\d+\.\d+>\nStart Call: Task.start_link\(Logger.TranslatorTest, :sleep, \[#PID<\d+\.\d+\.\d+>\]\)\n/
     stacktrace:
       test/logger/translator_test.exs:951: (test)

......

  2) test translates Supervisor progress with name (Logger.TranslatorTest)
     test/logger/translator_test.exs:963
     Assertion with =~ failed
     code:  assert capture_log(:info, fn ->
              ref = Process.monitor(pid)
              Supervisor.start_child(pid, worker(Task, [__MODULE__, :sleep, [self()]]))
              Process.exit(pid, :normal)

              receive do
                {:DOWN, ^ref, _, _, _} -> :ok
              end
            end) =~ ~r"\[info\] Child Task of Supervisor Logger.TranslatorTest started
            "
     left:  ""
     right: ~r/\[info\] Child Task of Supervisor Logger.TranslatorTest started\n/
     stacktrace:
       test/logger/translator_test.exs:966: (test)

...........................................................................................................................
Finished in 1.0 seconds (0.5s on load, 0.00s async, 0.4s sync)
3 doctests, 157 tests, 2 failures
make: *** [test_logger] Error 2
```

Does anyone have a clue why?

### Expected behavior

No failing tests

**Comment by dvic** [comment] 2024-09-21 12:56
I should mention here it happens both when installing with mise as well as manually running `make clean, make, make test`

**Comment by sabiwara** [comment] 2024-09-21 12:58
Closing as duplicate of https://github.com/elixir-lang/elixir/issues/13848

**Closed by sabiwara** 2024-09-21 12:58 UTC
