### ISSUE TITLE
Incorrect (?) incompatible types warning

### ISSUE THREAD

**Issue by juanperi** [elixir-lang/elixir#11204] opened 2021-08-24 11:53 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
  Elixir 1.13.0-dev (5296ec3) (compiled with Erlang/OTP 24)

### Current behavior

While testing elixir master, I got the following warning:
```
warning: incompatible types:

    map() !~ %{binary() => var2 | var3, optional(dynamic()) => dynamic()} | %{binary() => var2 | var3, optional(dynamic()) => dynamic()}

in expression:

    # lib/sylar_web/controllers/category_controller.ex:52
    conn.assigns

where "conn" was given the type map() | map() in:

    # lib/sylar_web/controllers/category_controller.ex:1
    [conn, params] = [conn, params]

where "conn" was given the type map() (due to calling var.field) in:

    # lib/sylar_web/controllers/category_controller.ex:52
    conn.assigns

HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()

Conflict found at
  lib/sylar_web/controllers/category_controller.ex:52: SylarWeb.CategoryController.show_facet/2
```
There is a bit of metaprogramming around this, I'll add some code later. But if i'm not reading this wrong, the compiler complains that there is a mismatch, but I'm seeing the variable as `map()` in both code snippets.
Is there an error in the warning, or am I reading this wrong?

The code comes from a controller, with a bit of metaprogramming around the function. It is a convenience to wrap around controllers for cases where I might want to "recover" from an error (for example a product changed slug, so I catch that exception, find the right one and redirect the user. The decoration itself is done through https://github.com/arjan/decorator

```
  @decorate fallback(
              target: Sylar.UrlGenerator.category_route(:show),
              recover_from: [SylarWeb.Exception.NotSeoFacet]
            )
  def show_facet(conn, params) do
    %{visitor: visitor} = conn.assigns
```
and the decorator code is
```
  def fallback(
        configuration,
        body,
        context
      ) do
    %{args: controller_args} = context

    recover_from =
      configuration
      |> Keyword.get(:recover_from, [Ecto.NoResultsError, Ecto.Query.CastError])
      |> List.wrap()

    quote do
      [conn, params] = unquote(controller_args)

      try do
        unquote(body)
      rescue
        e in unquote(recover_from) ->
```

The code actually works, and has been like this for quite some time, so I would venture that the compiler warning is incorrect.

### Expected behavior

I do not expect a compiler warning, as the parameter is in both cases a conn struct

**Comment by ericmj** [comment] 2021-08-24 12:59
Can you provide a way for us to reproduce the error?

**Comment by juanperi** [comment] 2021-08-24 13:00
ha, I expected it to be something that would jump up at you, without having to build a repro.
I'll give it a try :)

**Comment by ericmj** [comment] 2021-08-24 13:13
> ha, I expected it to be something that would jump up at you, without having to build a repro.
I'll give it a try :)

I can see what the issue is, but not sure yet how it happens, so it would be good to have a way to reproduce to verify the fix.

Thank you!

**Comment by juanperi** [comment] 2021-08-24 13:37
There you go.
https://github.com/juanperi/mix_app/tree/bug/elixir-11204

Sorry for being lazy at first. :)

**Comment by wojtekmach** [comment] 2021-08-24 13:43
pro-tip:

```
# bug_11204.exs
Mix.install([
  {:decorator, "~> 1.2"}
])

defmodule TheBug.Decorator do
  use Decorator.Define, fallback: 0

  def fallback(
        body,
        context
      ) do
    %{args: controller_args} = context

    quote do
      [conn, params] = unquote(controller_args)

      unquote(body)
    end
  end
end

defmodule TheBug.PageController do
  use TheBug.Decorator

  @decorate fallback()
  def index(conn, params) do
    %{} = params
    %{} = conn.assigns

    conn
  end
end
```

```
$ elixir bug_11204.exs
warning: incompatible types:

    map() !~ %{optional(dynamic()) => dynamic()} | %{optional(dynamic()) => dynamic()}

in expression:

    # bug_11204.exs:28
    conn.assigns

where "conn" was given the type map() | map() in:

    # bug_11204.exs:22
    [conn, params] = [conn, params]

where "conn" was given the type map() (due to calling var.field) in:

    # bug_11204.exs:28
    conn.assigns

HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()

Conflict found at
  bug_11204.exs:28: TheBug.PageController.index/2
```

:D

**Comment by juanperi** [comment] 2021-08-24 13:47
haha, I actually tried to do it that way, but it failed saying "TheBugWeb.Decorator is not loaded and could not be found"
I thought it was one of those cases of defining things at the same level where you are using it and didn't think it twice.

Now that you made it work, i went back to the logs, and I had an error in the module name when I copy pasted 🤦 
It should have been "TheBug.Decorator", not "TheBugWeb.Decorator"

**Comment by juanperi** [comment] 2021-08-24 13:50
(btw, mix install is awesome, i'm using it more and more!! thank you @wojtekmach !!!)

**Comment by wojtekmach** [comment] 2021-08-24 13:51
(apologies for hijacking the thread!)

> (btw, mix install is awesome, i'm using it more and more!! thank you @wojtekmach !!!)

thank you for the kind words! <3

> I thought it was one of those cases of defining things at the same level where you are using it and didn't think it twice

yeah, most commonly it is when you have:

```elixir
defmodule Foo do
  defstruct []
end

%Foo{}
```

fyi, my preferred solution is:

```elixir
defmodule Foo do
  defstruct []
end

defmodule Main do
  def main do
    %Foo{}
  end
end

Main.main()
```

**Comment by juanperi** [comment] 2021-08-24 13:57
btw, if you comment out the line 
`    %{} = params`
in the PageController, the warning disappears

**Comment by gliboc** [comment] 2021-09-16 08:44
Hi @juanperi,

After looking into the issue, it seems that the bug stems from the line `[conn, params] = unquote(controller_args)` in the decorator definition, that translates to `[conn, param] = [conn, params]`.

The compiler infers the type of the list on the right side by collapsing the types of its elements, into this union

`optional(dynamic()) => dynamic()} | optional(dynamic()) => dynamic()}`

Then, it attemps to unify this type with `map()`, the type inferred for `conn` from to `conn.assigns`, but fails at doing so.

It might be that the compiler should simply handle this better, however there is a straightforward solution: use tuples instead of lists, because there is a type for each field of a tuple in Elixir, and it does not get collapsed.

e.g. replace

`[conn, params] = unquote(controller_args)`

with

`{conn, params} = {unquote_splicing(controller_args)}`

and it will work without warning.

**Comment by juanperi** [comment] 2021-09-16 09:05
hey @gliboc you are totally correct. After doing the change to unquote_splicing, the warning disappears.
I'm happy with doing that in my codebase. Thank you for the pointer!

As if this needs a "fix", or it is working as intended, I'll leave it for the maintainers to decide :)
thank you all for your support!!!

**Comment by josevalim** [comment] 2021-11-01 08:59
Closing in favor of #11351.

**Closed by josevalim** 2021-11-01 08:59 UTC
Labels: Kind:Bug, App:Elixir (checker)
