### ISSUE TITLE
plug_cowboy logger translator stopped working after upgrading to elixir version 1.15

### ISSUE THREAD

**Issue by jviudes** [elixir-lang/elixir#13510] opened 2024-04-23 19:00 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.15.0 (compiled with Erlang/OTP 24)

### Operating system

Sonoma 14.0

### Current behavior

Logger translator doesn't seem to be sticking in plug_cowboy.

Inside Plug.Cowboy:
```
:logger.get_primary_config()

%{
  level: :debug,
  filters: [
    logger_process_level: {&Logger.Utils.process_level/2, []},
    logger_translator: {&Logger.Utils.translator/2,
     %{
       otp: true,
       sasl: false,
       translators: [
         {Plug.Cowboy.Translator, :translate},
         {Logger.Translator, :translate}
       ]
     }}
  ],
  filter_default: :log,
  metadata: %{}
}

```
Inside my Application:
```
:logger.get_primary_config()
%{
  level: :debug,
  filters: [
    logger_translator: {&Logger.Utils.translator/2,
     %{otp: true, sasl: false, translators: [{Logger.Translator, :translate}]}},
    logger_process_level: {&Logger.Utils.process_level/2, []}
  ],
  filter_default: :log,
  metadata: %{}
}
```

### Expected behavior

Plug cowboy translator should be sticking out to the config. Application logger config should be:
```
:logger.get_primary_config()

%{
  level: :debug,
  filters: [
    logger_process_level: {&Logger.Utils.process_level/2, []},
    logger_translator: {&Logger.Utils.translator/2,
     %{
       otp: true,
       sasl: false,
       translators: [
         {Plug.Cowboy.Translator, :translate},
         {Logger.Translator, :translate}
       ]
     }}
  ],
  filter_default: :log,
  metadata: %{}
}

```

Plug cowboy translator works on Elixir version 1.14

**Comment by josevalim** [comment] 2024-04-23 19:08
I cannot reproduce it on Elixir v1.16, so I suggest trying the latest Elixir v1.15 or latest Elixir v1.16.

**Comment by jviudes** [comment] 2024-04-23 19:18
I still get the {Plug.Cowboy.Translator, :translate} on my logger config on version:
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.16.2 (compiled with Erlang/OTP 24)

**Comment by jviudes** [comment] 2024-04-23 19:20
I don't know if that's the right place to be looking at, but logs started looking weird and leaking information that it shouldn't after I upgrade to elixir version 1.15. Just like plug_cowboy config isn't sticking.

**Comment by josevalim** [comment] 2024-04-24 07:58
Can you provide steps to precisely reproduce this issue then? If I run `iex -S mix` inside `plug_cowboy`, I can see the translator. I can also see it in my apps.

**Comment by jviudes** [comment] 2024-04-29 13:23
Hey @josevalim , I just wanted to follow up and check if you had a chance to look at the above or had any idea on what might be happening. Thank you for your time

**Comment by josevalim** [comment] 2024-05-01 09:36
Thank you, this has been fixed in Elixir and it will be part of the upcoming v1.16.x patch release as well.

**Comment by josevalim** [comment] 2024-05-01 09:37
Fixed in b378a2d560bf8ed255ac58e5b69fbeb893f4e594.

**Closed by josevalim** 2024-05-01 09:36 UTC

**Comment by jviudes** [comment] 2024-05-01 14:21
Awesome, thanks a lot for looking into this!

**Comment by epinault** [comment] 2024-05-01 14:59
@josevalim any chance we can get a 1.15 release? this is likely a risk for security concerns as they are a lot of stuff in the conn struct... And upgrading to 1.16 require fixing some hard deprecation for some of us. Feels like enough securityish concerns maybe to get a 1.15 patch too? what do you think?

**Comment by josevalim** [comment] 2024-05-01 15:05
Assuming folks are using releases in production, I don’t believe the issue manifests inside a release, does it?

**Comment by epinault** [comment] 2024-05-01 15:09
let s say not everyone uses mix release 😭 sometime people inherit things prior to use release and is a big undertaking but I am can see on a service that uses it maybe if that s an issue

**Comment by epinault** [comment] 2024-05-01 21:55
@josevalim so the few we have are not yet in 1.15 :/ this feels still security patch related because other people may have translator that think that works . the patch is only few line and might be easy to add to 1.15 ?
