### ISSUE TITLE
FunctionCompileError without function name or stack trace present

### ISSUE THREAD

**Issue by lauraannwilliams** [elixir-lang/elixir#10081] opened 2020-06-05 00:19 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Operating system:  Docker (ubuntu:xenial)

### Current behavior

When running unit tests, I'm getting an empty FunctionCompileError on a bunch of tests. I'm having trouble debugging this as obviously there's no real info to go by

```
380) test list_calculations/1 returns record matching slug (Structure.CalculationTest)
     apps/test/structure/calculation_test.exs:44
     ** (FunctionClauseError) no function clause matches


```
All the tests that are failing are ones that access the test database. These tests were previously working on 1.6.6, but i've been trying to update to v1.9.4. I'm assuming there's some change to ecto / postgres that i'm missing.. but i can't find it without knowing which function it's dying on. 

I'm attaching my mix files
[mix.lock.txt](https://github.com/elixir-lang/elixir/files/4733250/mix.lock.txt)
[mix.exs.txt](https://github.com/elixir-lang/elixir/files/4733251/mix.exs.txt)

### Expected behavior

I'd expect to see more information

```
** (FunctionClauseError) no function clause matching in Count._to/2
count.exs:6: Count._to(5, 6)
```

**Comment by lauraannwilliams** [comment] 2020-06-05 03:44
Update: after some further testing this issue only happens within a docker container. When I compile the project on my local (Mac OS Sierra ) I see the full trace. I'm guessing this is a Docker issue, not an elixir one.

**Comment by josevalim** [comment] 2020-06-05 07:13
Hi @lauraannwilliams, thanks for the report.

This can also be caused because the debug information was removed from chunks or because the processes are listed as sensitive. We would need a way to reproduce the issue to be sure. :)

**Comment by lauraannwilliams** [comment] 2020-06-05 16:44
If i can figure out how to reproduce in a simpler version i'll post. Thanks for the reply :)

**Comment by josevalim** [comment] 2020-06-25 18:57
Ping @lauraannwilliams. Do you have by any chance a mechanism to reproduce this? Thank you. :)

**Comment by josevalim** [comment] 2020-06-30 11:44
I will go ahead and close this for now but we will be glad to reopen this at any time if we have a way to reproduce it. Thanks!

**Closed by josevalim** 2020-06-30 11:44 UTC
Labels: Note:Needs more info
