### ISSUE TITLE
Mix cannot fetch dependencies when running in Docker container with Wireguard connection active

### ISSUE THREAD

**Issue by juulSme** [elixir-lang/elixir#10239] opened 2020-07-29 07:40 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): multiple, currently 1.10.4 / 22
* Operating system: Ubuntu 20.04
* Docker: 19.03.12

### Current behavior

I've observed this behavior over the past few months. It's more of a nuisance. For my company we use a wireguard VPN-setup to connect to the office network. The wireguard client redirects all traffic over the wireguard interface (`AllowedIPs = 0.0.0.0/0, ::/0`) and this works just fine. To be clear; the wireguard client runs directly on the host, not inside of a Docker container. With the connection active, connecting to the internet from inside a container works as expected:

```bash
juul@theincrediblemachine:~$ docker run --rm -ti elixir:1.10-alpine /bin/sh
/ # ping google.com
PING google.com (172.217.20.110): 56 data bytes
64 bytes from 172.217.20.110: seq=0 ttl=116 time=18.852 ms
64 bytes from 172.217.20.110: seq=1 ttl=116 time=19.719 ms
/ # apk add --update --no-cache bash
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing bash (5.0.11-r1)
Executing bash-5.0.11-r1.post-install
Executing busybox-1.31.1-r9.trigger
OK: 9 MiB in 23 packages
```

However Mix cannot connect to the internet, install Hex, fetch dependencies etc:
```bash
/ # mix local.hex --force
** (Mix) request timed out after 60000ms

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.signed.

Alternatively, you can compile and install Hex directly with this command:

    mix archive.install github hexpm/hex branch latest

# this is weird because this DOES work:
/ # ping repo.hex.pm
PING repo.hex.pm (151.101.38.2): 56 data bytes
64 bytes from 151.101.38.2: seq=0 ttl=57 time=20.861 ms
64 bytes from 151.101.38.2: seq=1 ttl=57 time=22.007 ms
```

The same goes for `deps.get`, `archive.install hex` etc (`archive.install github` does work, I guess because it uses the git executable). Also, the issue does not resolve by disconnecting Wireguard; the entire container has te be started again.

Some network command output:
```bash
/ # ip route list
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 scope link  src 172.17.0.2 
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2969 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2089 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:12786065 (12.1 MiB)  TX bytes:140917 (137.6 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

So nothing unexpected, just some bog-standard default-Docker-bridge networking stuff.

### Expected behavior

I expect mix to be able to fetch dependencies inside a Docker container with a Wireguard tunnel up and running on the host.

**Comment by ericmj** [comment] 2020-07-29 21:42
VPN works on a network level above what we can affect from elixir so there's unfortunately nothing we can do inside Elixir itself to fix this issue. If it doesn't work with your VPN but works without your VPN on the same machine then it's likely an issue with your VPN or VPN configuration.

**Comment by juulSme** [comment] 2020-07-30 10:31
But surely if there was a problem with the networking configuration then all of the other internet-connecting programs - ping, apk, git - wouldn't work either?

**Comment by juulSme** [comment] 2020-07-30 10:33
Well, "exclusively" - I haven't tested every other program of course, but still.

**Comment by ericmj** [comment] 2020-07-30 12:23
I can't explain why it works for other programs but not mix. On IRC it was suggested it could be an issue where DNS is not resolved through the VPN, then it would work for some services but not others.

There is nothing we can configure specifically for VPNs on our end and since we cannot reproduce this issue there is not much we can do. I will close this issue for now because there is nothing actionable for us to do right now, if you find more information please post it here and if we learn that it's an Elixir issue we will reopen.

**Closed by ericmj** 2020-07-30 12:23 UTC
