### ISSUE TITLE
user_drv_reader terminating

### ISSUE THREAD

**Issue by discobob07** [elixir-lang/elixir#13016] opened 2023-10-18 08:59 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

windows 10

### Current behavior

Process :user_drv_reader (#PID<0.68.0>) terminating
** (CaseClauseError) no case clause matching: {:error, {:GetOverlappedResult, :"ÓÉÓÚÏß³ÌÍË³ö»òÓ¦ÓÃ³ÌÐòÇëÇó£¬ÒÑÖÐÖ¹ I/O ²Ù×÷¡£\r\n"}}
    (kernel 9.1) prim_tty.erl:476: :prim_tty.reader_loop/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Initial Call: :prim_tty.reader/1
Ancestors: [:user_drv, #PID<0.64.0>, :kernel_sup, #PID<0.47.0>]
Message Queue Length: 0
Messages: []
Links: [#PID<0.66.0>]
Dictionary: []
Trapping Exits: false
Status: :running
Heap Size: 376
Stack Size: 28
Reductions: 5124

### Expected behavior

When using 'iex -S mix' to run a project, if there is an error, the iex shell can no longer be used

**Comment by josevalim** [comment] 2023-10-18 09:53
Can you please provide a mechanism to reproduce it? This error is coming from Erlang, so we need to isolate it and report it upstream. My suspicion is that it may be encoding related. How are you running Elixir? Terminal? Powershell? WSL? Does it work if you only start "iex.bat"? Thank you.

**Comment by discobob07** [comment] 2023-10-20 05:45
the running environment is cmder, using powershell, the problem with iex.bat persists, and there is no problem in git bash shell and linux environment

**Comment by josevalim** [comment] 2023-10-20 06:14
Thank you. Does it happen with only `iex`? Or you need `iex -S mix`? Does it happen if you run `erl`?

**Comment by discobob07** [comment] 2023-10-20 06:23
If it is a Windows environment, it will happen

**Comment by josevalim** [comment] 2023-10-20 06:47
So if it fails on `erl`, then it is an issue with Erlang, can you please file an issue on github.com/erlang/otp? But they will likely need more information about your environment to reproduce it. I cannot reproduce it on a Windows machine in powershell. It may also be encoding related (i.e. you are using your terminal with a different encoding than UTF8).

**Comment by josevalim** [comment] 2023-10-24 18:39
Hi @discobob07, I will go ahead and close this one. You mention it happens with `erl`, so this should be reported to github.com/erlang/otp with more information, as per the previous reply.

**Closed by josevalim** 2023-10-24 18:39 UTC
