### ISSUE TITLE
Improved Logger behaviour

### ISSUE THREAD

**Issue by orestis** [elixir-lang/elixir#7192] opened 2018-01-09 16:47 UTC
As discussed on the Elixir Forum and also on a blog post I wrote, the current Logger behaviour of switching to sync mode in order to try and put some back-pressure to the log producers can break some systems entirely.

When a system comes under unexpected load and the logging code might generate a huge amount of logs, a more safe behaviour is to drop log messages entirely (perhaps logging the fact!) — it seems that [Lager](https://github.com/erlang-lager/lager) is doing that for Erlang.

I am opening this issue at the request of @josevalim. I'd be happy to help but I'd require some guidance.

**Comment by josevalim** [comment] 2018-01-09 18:33
Thank you!

Btw, are you using a custom log handler in your app?

I have spent most of the day today getting the Logger to crash and I couldn't. At some point I spawned hundreds of thousand of processing logging at the same time and the Logger was able to go along just fine - even after introducing a fake handler that sleeps for 0.1 seconds.

Another theory is that your system was overloaded doing other activities and that did not give the Logger time to run. I will have to try to simulate this with busy wait or try on a machine with limited resources.

**Comment by orestis** [comment] 2018-01-09 18:36
This was just the stock Logger from Elixir 1.5.3, logging to stdout, which was then taken care of using systemd, on CentOS. I'm not sure if the problem came from slow I/O or even I/O stopping entirely due to log rotation? I've no idea how systemd handles this.

I will try to make a reproduction in a VM...

**Comment by josevalim** [comment] 2018-01-09 18:38
@orestis if you could make a reproduction VM that would be great and I will send some apps for you to try out. Does anyone know how I could simulate slow I/O from the OS side?

**Comment by OvermindDL1** [comment] 2018-01-09 19:01
> Does anyone know how I could simulate slow I/O from the OS side?

Hmm, maybe make stdout be an unbuffered pipe to another program that throttles it as it wishes (or set the buffer very low)?

**Comment by josevalim** [comment] 2018-01-09 19:34
@OvermindDL1 good idea. It probably can't be written in Elixir though because the VM is a bit peculiar on how it reads stdin (iirc it buffers everything).

**Comment by orestis** [comment] 2018-01-09 19:41
I have setup a simple Vagrant VM; I will keep the investigation going tomorrow where I will try to recreate my architecture with a do-nothing app. Meanwhile, if there are other apps I can try, please share.

**Comment by OvermindDL1** [comment] 2018-01-09 19:52
> It probably can't be written in Elixir though because the VM is a bit peculiar on how it reads stdin (iirc it buffers everything).

Heh, I definitely don't think it could yeah, but a bash script or something would probably be enough all things considered.  ^.^;

**Comment by josevalim** [comment] 2018-01-09 22:02
And #7193 should fix those issues.

**Comment by josevalim** [comment] 2018-01-10 08:42
Closing in favor of the PR. :) @orestis if you could try the app above and the VM on top of the PR as well, it would be very appreciated. Thanks!

**Closed by josevalim** 2018-01-10 08:42 UTC
