### ISSUE TITLE
Float.parse/1 returns wrong result

### ISSUE THREAD

**Issue by zipme** [elixir-lang/elixir#3303] opened 2015-05-03 15:41 UTC
I am using
```
> iex

Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
```

Seems parsing "0.29" gives wrong result...

```
iex(1)> Float.parse("0.29")
{0.28, ""}
 
```

**Comment by zipme** [comment] 2015-05-03 16:14
Another one I found is 

```
iex(8)> Float.parse("0.58")
{0.57, ""}
```

**Comment by oneeman** [comment] 2015-05-03 16:17
This seems to already have been fixed on master:

```
Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Float.parse("0.58")
{0.58, ""}
```

A duplicate of https://github.com/elixir-lang/elixir/issues/2867?

**Comment by josevalim** [comment] 2015-05-03 16:24
This is fixed in master indeed. :)

**Closed by josevalim** 2015-05-03 16:24 UTC

**Comment by zipme** [comment] 2015-05-04 01:22
@josevalim Cool thanks! And will this fix be included in the next release which I assume is 1.0.5?

**Comment by josevalim** [comment] 2015-05-04 06:17
Next release is likely 1.1.0.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by zipme** [comment] 2015-05-04 06:20
@josevalim I see, thanks for the update! if 1.1.0 is not coming anytime soon I might need to find some workaround for now.

**Comment by josevalim** [comment] 2015-05-04 07:19
You maybe be able to use :erlang.binary_to_float wrapped in a try/catch:

    try do
      {:ok :erlang.binary_to_float(bin)}
    rescue
      ArgumentError -> :error
    end

Not the prettiest thing but it may suffice.

**Comment by zipme** [comment] 2015-05-04 07:20
@josevalim 💜💜💜 thanks so much!
