### ISSUE TITLE
False positive for warning: found quoted atom, but the quotes are not required

### ISSUE THREAD

**Issue by blatyo** [elixir-lang/elixir#8442] opened 2018-11-30 16:04 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:12:12] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.7.4 (compiled with Erlang/OTP 19)

* Operating system: 

OS X High Sierra 10.13.6

### Current behavior

When compiling, we receive the following warning:

```
warning: found quoted atom "enum_users_companySize" but the quotes are not required. Quotes should only be used to introduce atoms with foreign characters in them
```

It happens on this atom: `:"\"enum_users_companySize\""`

### Expected behavior

It should not warn, because the atom has double quotes in it, which could not be represented without the quoted atom.

**Comment by josevalim** [comment] 2018-11-30 16:20
I cannot reproduce this on master nor on v1.7.4:

```elixir
defmodule Foo do
  def bar do
    :"\"enum_users_companySize\""
  end
end
```

What am I missing? :)

**Comment by josevalim** [comment] 2018-11-30 21:16
Oh, it is a bug because of Erlang/OTP 19. That's why I couldn't reproduce it. This is fixed in master then. :) Thanks for the report!

**Closed by josevalim** 2018-11-30 21:16 UTC
Labels: Note:Needs more info
