### ISSUE TITLE
Error in a test for mix

### ISSUE THREAD

**Issue by alg** [elixir-lang/elixir#2836] opened 2014-10-21 04:04 UTC
Here's what I get when compiling and running tests in v1.0.1 and master branches:

```
  1) test get and compile dependencies for rebar (Mix.RebarTest)
     /Users/alg/tmp/elixir/lib/mix/test/mix/rebar_test.exs:101
     ** (UndefinedFunctionError) undefined function: :rebar_dep.any_function/0 (module :rebar_dep is not available)
     stacktrace:
       :rebar_dep.any_function()
       test/mix/rebar_test.exs:114: anonymous fn/0 in Mix.RebarTest.test get and compile dependencies for rebar/1
       (elixir) lib/file.ex:1067: File.cd!/2
       test/mix/rebar_test.exs:106
```

**Comment by josevalim** [comment] 2015-01-03 19:16
Do you have more info? I gave another try and I could not reproduce it :S Thanks!

**Comment by josevalim** [comment] 2015-01-04 22:59
Closing for now. I will gladly reopen once we have steps to reproduce this! :D Thank you!

**Closed by josevalim** 2015-01-04 22:59 UTC
