### ISSUE TITLE
Redefining a modules function when using __before_compile__.

### ISSUE THREAD

**Issue by daveli** [elixir-lang/elixir#12198] opened 2022-10-13 18:41 UTC
### Elixir and Erlang/OTP versions

Elixir 1.14.1
OTP 25.1.1

### Operating system

Linux

### Current behavior

👋 I'm currently running into the following issue when using __before_compile__ in a macro.

```
defmodule Foo do
  defmacro __using__(_) do
    quote do
      @before_compile unquote(__MODULE__)
      import unquote(__MODULE__)
      def bar(self), do: Foo.bar(self)
    end
  end

  defmacro __before_compile__(_) do
    quote do
      require Foo.Struct
      Foo.Struct.for_struct()
    end
  end
end

defmodule Foo.Struct do
  defmacro for_struct do
    quote do
      defimpl Foo.Baz, for: __MODULE__ do
        def baz(struct), do: struct |> Map.from_struct() |> map_size == 0
      end
    end
  end
end
```

This return with Elixir 1.14.1 the following type of error `cannot define module Foo.Baz.Kernel because it is currently being defined in {other file that uses the macro}`.

### Expected behavior

To only have the function to be defined once.

FYI: The code I'm working on seems to based on https://github.com/CargoSense/vex and that library also seems to experience the same issue testing it locally. Both macros work on Elixir < 1.14.

**Comment by josevalim** [comment] 2022-10-13 20:14
Duplicate of #12186. :)

**Closed by josevalim** 2022-10-13 20:14 UTC
