### ISSUE TITLE
In config/config.exs, only config values defined in root scope are visible while calling Application.get_all_env()

### ISSUE THREAD

**Issue by caizongchao** [elixir-lang/elixir#3243] opened 2015-04-06 01:45 UTC
In the code below, expected visible config values are: :repo_all, :repo_count, CC.Repo.S0, CC.Repo.S1.

But while calling Application.get_all_env(CC) to retrive config values, only :repo_all and :repo_count are visible.

```elixir
__repo_all__ =  [
  [ hostname: "192.168.0.100",
    database: "postgres",
    username: "postgres",
    password: "12345678" ],

  [ hostname: "192.168.0.101",
    database: "postgres",
    username: "postgres",
    password: "12345678" ]]

__repo_count__ = Enum.count(__repo_all__)

config CC, :repo_all, __repo_all__

config CC, :repo_count, __repo_count__

Enum.reduce(__repo_all__, 0, fn(opts, n) ->
  config CC, String.to_atom(Enum.join([CC.Repo, ".S", n])), 
        [{:adapter, Ecto.Adapters.Postgres} | opts]

  n + 1
end)
```

**Comment by whatyouhide** [comment] 2015-05-02 10:11
I figured out the problem, and it's kind of a nasty one. As you can see reading the [source for `Mix.Config.config/3`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/config.ex#L96), the configuration mechanism works by keeping a `config` variable scoped to the `Mix.Config` module and by always modifying that variable. You can imagine (actually, that's exactly what happens) that every time you write something like

```elixir
config CC, :foo, :bar
```

that gets translated to something like

```elixir
config = merge(config, ...)
```

The problem is that anonymous functions cannot modify their outer environment:

```elixir
iex> a = 1
iex> f = fn ->
...>   IO.puts "I can read a and it's #{a}"
...>   a = 2
...> end
iex> f.()
I can read a and it's 1
2
iex> a
1
```

and that's why changing the config inside the function you pass to `Enum.reduce/3` doesn't "persist" the modifications to the config. Same goes for `for` comprehensions (which you could have used as well here).

I'm not sure what I would to to solve this, maybe @josevalim will come up with something nice (I can only think of using the pdict or an ETS table or something stateful during compilation).

For now, you will have to manually call `config` for each repo here :disappointed:

**Comment by josevalim** [comment] 2015-05-02 10:52
My idea was to use an Agent. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by whatyouhide** [comment] 2015-05-02 10:56
May I give this a try then? :)

On Saturday, May 2, 2015, José Valim <notifications@github.com> wrote:

> My idea was to use an Agent. :)
>
> --
>
>
> *José Valimwww.plataformatec.com.br
> <http://www.plataformatec.com.br/>Founder and Lead Developer*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3243#issuecomment-98347347>.
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by josevalim** [comment] 2015-05-02 13:19
Please do!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by whatyouhide** [comment] 2015-05-03 09:38
Hey there @caizongchao, #3302 was just merged and it solves this. Give it a try :)

**Closed** 2015-05-03 09:37 UTC

**Comment by caizongchao** [comment] 2015-05-09 12:49
The fix works like a charm, thanks!
