### ISSUE TITLE
Alpine Linux: intermittent test failure on package build (v1.11.2)

### ISSUE THREAD

**Issue by schrodervictor** [elixir-lang/elixir#10492] opened 2020-11-12 14:37 UTC
Hello, I'm adding Elixir v1.11.2 to the Alpine Linux aports. It seems there is a race condition that makes the tests fail sometimes. Running the CI pipeline multiple times eventually makes the tests pass. See details below.

### Environment

```
$ elixir --version
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.11.2 (compiled with Erlang/OTP 23)

$ uname --all
Linux be743a8ce0fa 4.6.0-1-amd64 #1 SMP Debian 4.6.3-1 (2016-07-04) x86_64 Linux

$ cat /etc/alpine-release
3.12.1
```

The environment information above is about the host machine where the testing build happened (fresh Alpine container). However, the failure was observed in other architectures:

- x86 arch: https://gitlab.alpinelinux.org/schrodervictor/aports/-/jobs/246372. System specs:
    ```
    >>> Host system information (arch: x86, release: edge) <<<
    - Number of Cores: 48
    - Memory: 62.6387 Gb
    - Free space: 146.6G
    ```

- x86_64 arch: https://gitlab.alpinelinux.org/schrodervictor/aports/-/jobs/246371. System specs:
    ```
    >>> Host system information (arch: x86_64, release: edge) <<<
    - Number of Cores: 128
    - Memory: 62.6357 Gb
    - Free space: 165.3G
    ```

### Current behavior

This is an intermittent failure. Running the tests multiple times lead to presence or absence of the error below:

```
==> mix (ex_unit)
Excluding tags: [windows: true]
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  1) test --partitions splits tests into partitions (Mix.Tasks.TestTest)
     test/mix/tasks/test_test.exs:293
     Assertion with == failed
     code:  assert mix(["test.coverage"]) == "Importing cover results: cover/1.coverdata\nImporting cover results: cover/2.coverdata\n\nPercentage | Module\n-----------|--------------------------\n   100.00% | A\n   100.00% | B\n-----------|--------------------------\n   100.00% | Total\n\nGenerated HTML coverage results in \"cover\" directory\n"
     left:  "warning: the archive archive-0.1.0 requires Elixir \"~> 0.1.0\" but you are running on v1.11.2\nImporting cover results: cover/1.coverdata\nImporting cover results: cover/2.coverdata\n\nPercentage | Module\n-----------|--------------------------\n   100.00% | A\n   100.00% | B\n-----------|--------------------------\n   100.00% | Total\n\nGenerated HTML coverage results in \"cover\" directory\n"
     right: "Importing cover results: cover/1.coverdata\nImporting cover results: cover/2.coverdata\n\nPercentage | Module\n-----------|--------------------------\n   100.00% | A\n   100.00% | B\n-----------|--------------------------\n   100.00% | Total\n\nGenerated HTML coverage results in \"cover\" directory\n"
     stacktrace:
       (elixir 1.11.2) lib/file.ex:1552: File.cd!/2
       test/test_helper.exs:126: MixTest.Case.in_fixture/3
       test/mix/tasks/test_test.exs:294: (test)
................................................................................................................................................................................................................
Finished in 162.8 seconds (5.4s on load, 157.4s on tests)
9 doctests, 651 tests, 1 failure
```

Relevant detail: `make` is run using `-j` to set the number of parallel jobs up to the number of available cores.

### Expected behavior

The test results should be consistent and not lead to intermittent failures.

**Comment by ericmj** [comment] 2020-11-12 15:10
Thanks for the report @schrodervictor. I have pushed a branch with a potential fix for the test error: https://github.com/elixir-lang/elixir/compare/emj/archive-test. Can you test this branch on your machines since I cannot reproduce the issue myself?

**Comment by schrodervictor** [comment] 2020-11-12 16:10
Hi @ericmj, thanks for the quick patch! I'll try, by simulating an merge request to the main repo of the aports and running the build/check jobs a couple of times to check if we get a failure. As I said, this issue is intermittent, so it is hard to tell 100% for sure that it is gone for good, but we can try to have a higher level of certainty.

Would you mind to explain briefly what is the cause of the issue? 

However, I can see that Elixir's CI is failing for your commit. Could you please take a look in the meanwhile? I just want to make sure our tests here will be meaningful.

**Comment by ericmj** [comment] 2020-11-12 16:34
> Would you mind to explain briefly what is the cause of the issue?

In another test we test warnings when loading code so we change the path we load code from, but until my fix we did not reset it, so when another test also triggers code to load we get the same warning again.

> However, I can see that Elixir's CI is failing for your commit. Could you please take a look in the meanwhile? I just want to make sure our tests here will be meaningful.

That seems to be another intermittent test failure but unfortunately I don't know what is causing it.

**Comment by josevalim** [comment] 2020-11-15 17:26
All issues should be fixed. For the OTP master one, it may fail from time to time, as we are tracking a moving target. Unfortunately GitHub actions does not allow us to declare something as `allow_failures: true`.

**Closed by josevalim** 2020-11-15 17:26 UTC
