### ISSUE TITLE
Enum Cheatsheet page not found

### ISSUE THREAD

**Issue by mneumann** [elixir-lang/elixir#13315] opened 2024-02-03 06:19 UTC
### Elixir and Erlang/OTP versions

Homepage, docs v1.16.1

### Operating system

n/a

### Current behavior

Go to 

https://hexdocs.pm/elixir/enumerable-and-streams.html

and follow the link to `Enum cheatsheet` leads to a non-existing page: https://hexdocs.pm/elixir/enum-cheat.cheatmd

It works for recent versions, likely because the versions is in the URL:

https://hexdocs.pm/elixir/1.16.0/enum-cheat.html

### Expected behavior

The link should point to the Enum cheatsheet.

**Comment by sabiwara** [comment] 2024-02-03 06:39
Thank you for reporting @mneumann.
The problem is in ex_doc, will send a PR there.

**Comment by josevalim** [comment] 2024-02-03 08:26
Fixed in ExDoc. Will be part of next release. Thanks!

**Closed by josevalim** 2024-02-03 08:26 UTC
