### ISSUE TITLE
Rebar test failure compiling Elixir from source

### ISSUE THREAD

**Issue by derek-at-alto** [elixir-lang/elixir#11131] opened 2021-07-21 15:06 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.2, OTP 24.0.3
* Operating system: Centos 7 on Docker on Big Sur

### Current behavior

When running `make test` from the root directory of commit `58ca6524f88bfe7e963deafe0e7d6aa07a568003` (release 1.12.2), `rebar_test.exs` fails with the following stack trace. See attached [base.Dockerfile.txt](https://github.com/elixir-lang/elixir/files/6856767/base.Dockerfile.txt) to reproduce.

```
#25 262.2   1) test integration with Mix handles Rebar overrides (Mix.RebarTest)
#25 262.2      test/mix/rebar_test.exs:210
#25 262.2      ** (Mix.Error) Command "git --git-dir=.git remote set-head origin -a" failed with reason: error: Multiple remote HEAD branches. Please choose one explicitly with:
#25 262.2        git remote set-head origin main
#25 262.2        git remote set-head origin master
#25 262.2      
#25 262.2      code: in_tmp("Rebar overrides", fn ->
#25 262.2      stacktrace:
#25 262.2        (mix 1.12.2) lib/mix.ex:454: Mix.raise/2
#25 262.2        (mix 1.12.2) lib/mix/scm/git.ex:262: Mix.SCM.Git.default_branch/0
#25 262.2        (mix 1.12.2) lib/mix/scm/git.ex:127: Mix.SCM.Git.checkout/2
#25 262.2        (elixir 1.12.2) lib/file.ex:1560: File.cd!/2
#25 262.2        (mix 1.12.2) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
#25 262.2        (mix 1.12.2) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
#25 262.2        (mix 1.12.2) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
#25 262.2        (mix 1.12.2) lib/mix/dep/converger.ex:72: Mix.Dep.Converger.all/4
#25 262.2        (mix 1.12.2) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
#25 262.2        (mix 1.12.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
#25 262.2        (mix 1.12.2) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
#25 262.2        test/mix/rebar_test.exs:214: anonymous fn/0 in Mix.RebarTest."test integration with Mix handles Rebar overrides"/1
#25 262.2        (elixir 1.12.2) lib/file.ex:1560: File.cd!/2
#25 262.2        test/mix/rebar_test.exs:213: (test)
```

It appears that the rebar project has added a `main` branch in addition to its `master` branch, which is causing an ambiguity that the git CLI can't handle, causing this test to fail.

### Expected behavior

The ambiguity should be resolvable and the test should pass.

**Comment by josevalim** [comment] 2021-07-21 18:07
Can you please try master, @derek-at-alto? This is not about the rebar repository but a repository we create specifically for tests: https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/test_helper.exs#L374 and we improved the default git branch handling on master in this commit: https://github.com/elixir-lang/elixir/commit/501a7ccc2728f17af28e23d3e4b4cfd9ab20ee60

**Comment by ericmj** [comment] 2021-07-21 18:19
The problem is that CentOS 7 was released 2014 and uses git v1.8.3.1 released in 2013.

We need to support multiple git versions for developers working on Elixir. Recently we made some changes, @josevalim linked one of them, to support git versions that set the default branch to either `master` or `main`. Unfortunately these changes seems to be incompatible with git v1.8.3.1, but I don't see an easy fix for it.

If you want to contribute a fix for this we would be happy to accept it, but generally I don't think we need to support a git version that is 8 years old.

**Closed** 2021-07-21 18:22 UTC
Labels: Note:Unresolved

**Comment by derek-at-alto** [comment] 2021-07-21 19:54
@ericmj Makes perfect sense. I'll update the dockerfile to get the latest git.

**Comment by coldneverdie** [comment] 2021-08-02 07:49
thanks bro, it's the version of git too old.
i've fix it.

**Comment by coldneverdie** [comment] 2021-08-02 07:50
but -bash: /usr/bin/mix: 没有那个文件或目录
why is this error ? omg.

**Comment by coldneverdie** [comment] 2021-08-02 07:50
then i  run "mix do deps.get, local.rebar --force, deps.compile, compile" this command
