### ISSUE TITLE
Crash in :elixir_erl_pass.extract_bit_type/2

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12394] opened 2023-02-13 08:28 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

I cannot reproduce it but somehow elixir compiler called via elixir-LS produced a broken beam file for one of the deps (`Elixir.HtmlEntities.beam` from `html_entities`)

Calling `:dialyzer_utils.get_core_from_beam(to_charlist(file))` on that beam resulted in
```
** (FunctionClauseError) no function clause matching in :elixir_erl_pass.extract_bit_type/2
    (elixir 1.14.3) src/elixir_erl_pass.erl:559: :elixir_erl_pass.extract_bit_type({:integer, [line: 78, column: 11], nil}, [])
    (elixir 1.14.3) src/elixir_erl_pass.erl:553: :elixir_erl_pass.extract_bit_info/3
    (elixir 1.14.3) src/elixir_erl_pass.erl:522: :elixir_erl_pass.build_bitstr/4
    (elixir 1.14.3) src/elixir_erl_clauses.erl:20: :elixir_erl_clauses.match/4
    (elixir 1.14.3) src/elixir_erl_for.erl:65: :elixir_erl_for.translate_gen/5
    (elixir 1.14.3) src/elixir_erl_for.erl:55: :elixir_erl_for.translate_gen/4
    (elixir 1.14.3) src/elixir_erl_for.erl:37: :elixir_erl_for.translate_into/5
    (elixir 1.14.3) src/elixir_erl_clauses.erl:31: :elixir_erl_clauses.clause/6
```

### Expected behavior

I'm not sure if this is a bug worth looking into

**Comment by josevalim** [comment] 2023-02-13 08:59
Yes, this looks suspicious. Especially because we do have a clause where the line above would match:

```
extract_bit_type({'-', _, [L, R]}, Acc) ->
  extract_bit_type(L, extract_bit_type(R, Acc));
extract_bit_type({unit, _, [Arg]}, Acc) ->
  [{unit, Arg} | Acc];
extract_bit_type({Other, _, nil}, Acc) ->
  [Other | Acc].
```

Given we can't reproduce it, there isn't much we can do, so I wil close it. But feel free to drop a comment if you have more info!

**Closed by josevalim** 2023-02-13 08:59 UTC

**Comment by lukaszsamson** [comment] 2023-10-25 22:42
@josevalim I've started seeing very high number of those stacktraces all coming from the same `:dialyzer_utils.get_core_from_beam(to_charlist(file))`. This happens on 1.13-1.15. Probably the beams get corrupted somehow but the rate this happens is worrying

```
{:function_clause, [{:elixir_erl_pass, :extract_bit_type, [{:binary, [], []}, []], [file: ~c"<REDACTED: user-file-path>", line: 559]}, {:elixir_erl_pass, :extract_bit_info, 3, [file: ~c"<REDACTED: user-file-path>", line: 553]}, {:elixir_erl_pass, :build_bitstr, 4, [file: ~c"<REDACTED: user-file-path>", line: 522]}, {:lists, :mapfoldl_1, 3, [file: ~c"lists.erl", line: 1706]}, {:elixir_erl_pass, :translate_remote, 5, [file: ~c"<REDACTED: user-file-path>", line: 616]}, {:elixir_erl_clauses, :clause, 6, [file: ~c"<REDACTED: user-file-path>", line: 31]}, {:elixir_erl, :translate_clause, 4, [file: ~c"<REDACTED: user-file-path>", line: 213]}, {:elixir_erl, :"-translate_definition_5-lc$^0_1-0-", 3, [file: ~c"<REDACTED: user-file-path>", line: 194]}]}

{:function_clause, [{:elixir_erl_pass, :extract_bit_type, [{:integer, [closing: [line: 515, column: 25], line: 515, column: 16], []}, []], [file: ~c"<REDACTED: user-file-path>", line: 559]}, {:elixir_erl_pass, :extract_bit_info, 3, [file: ~c"<REDACTED: user-file-path>", line: 553]}, {:elixir_erl_pass, :build_bitstr, 4, [file: ~c"<REDACTED: user-file-path>", line: 522]}, {:lists, :mapfoldl_1, 3, [file: ~c"lists.erl", line: 1706]}, {:elixir_erl_clauses, :match, 4, [file: ~c"<REDACTED: user-file-path>", line: 20]}, {:elixir_erl_clauses, :clause, 6, [file: ~c"<REDACTED: user-file-path>", line: 28]}, {:elixir_erl, :translate_clause, 4, [file: ~c"<REDACTED: user-file-path>", line: 213]}, {:elixir_erl, :"-translate_definition_5-lc$^0_1-0-", 3, [file: ~c"<REDACTED: user-file-path>", line: 194]}]}

{:function_clause, [{:elixir_erl_pass, :extract_bit_type, [{:binary, [delimiter: "\"", line: 368, column: 25], []}, []], [file: ~c"<REDACTED: user-file-path>", line: 559]}, {:elixir_erl_pass, :extract_bit_info, 3, [file: ~c"<REDACTED: user-file-path>", line: 553]}, {:elixir_erl_pass, :build_bitstr, 4, [file: ~c"<REDACTED: user-file-path>", line: 522]}, {:lists, :mapfoldl_1, 3, [file: ~c"lists.erl", line: 1706]}, {:lists, :mapfoldl_1, 3, [file: ~c"lists.erl", line: 1707]}, {:elixir_erl_pass, :translate_remote, 5, [file: ~c"<REDACTED: user-file-path>", line: 616]}, {:elixir_erl_clauses, :clause, 6, [file: ~c"<REDACTED: user-file-path>", line: 31]}, {:elixir_erl, :translate_clause, 4, [file: ~c"<REDACTED: user-file-path>", line: 213]}]}

{:function_clause, [{:elixir_erl_pass, :extract_bit_type, [{:unsigned, [], []}, []], [file: ~c"<REDACTED: user-file-path>", line: 559]}, {:elixir_erl_pass, :extract_bit_type, 2, [file: ~c"<REDACTED: user-file-path>", line: 560]}, {:elixir_erl_pass, :extract_bit_info, 3, [file: ~c"<REDACTED: user-file-path>", line: 549]}, {:elixir_erl_pass, :build_bitstr, 4, [file: ~c"<REDACTED: user-file-path>", line: 522]}, {:elixir_erl_pass, :translate_list, 4, [file: ~c"<REDACTED: user-file-path>", line: 307]}, {:elixir_erl_pass, :translate, 3, [file: ~c"<REDACTED: user-file-path>", line: 15]}, {:elixir_erl_pass, :translate_block, 4, [file: ~c"<REDACTED: user-file-path>", line: 352]}, {:elixir_erl_pass, :translate, 3, [file: ~c"<REDACTED: user-file-path>", line: 64]}]}
```

**Comment by josevalim** [comment] 2023-10-25 22:46
This is happening because the Elixir version used to generate the .beam file does not match the Elixir version currently running. Can you please make sure they match?

**Comment by lukaszsamson** [comment] 2023-10-25 22:59
I'll try that. If that does not help it's always possible to `rm -rf` and start from scratch
