### ISSUE TITLE
Improve error message when variables are undefined

### ISSUE THREAD

**Issue by rs86** [elixir-lang/elixir#3985] opened 2015-11-24 18:47 UTC
If I try to use an undefined variable, the compiler will give out an error saying there is no function/0 defined. It is trying to parse the variable as a 0-arity function.

== Compilation error on file lib/x.ex ==
** (CompileError) lib/x.ex:36: function somevariable/0 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

This makes the programmer think at first that there is a problem with a function.

Is there any way to give a friendlier error message? Suggestion: if the compiler can't find a null-arity function, add to the message:

"This might be an undefined variable called xxxx".

**Comment by ericmj** [comment] 2015-11-24 18:52
I agree, the error message can be confusing and should be improved to also include that an undefined variable can be the cause.

**Comment by pdilyard** [comment] 2015-11-24 20:02
Where might the code for this be found? I've found the definition of `CompileError` in `lib/elixir/lib`, but I can't seem to find where this is being raised with the given message. I'm assuming it's in Erlang code somewhere?

I also notice that this error is slightly different in iex:
```
** (CompileError) iex:1: undefined function abc/0
```
as opposed to:
```
** (CompileError) undefined.exs:3: function abc/0 undefined
```

If someone could give me a little pointer, I'd love to get started contributing and figured this would be a good issue to begin with.

**Comment by josevalim** [comment] 2015-11-24 20:10
The error is coming from within Erlang, so we need to investigate what is the format and wrap it in the elixir_errors.erl file.

**Comment by josevalim** [comment] 2015-11-24 20:40
Good point @pdilyard. our error messages are inconsistent here. Are you ok if I take this issue and fix this and other error messages?

**Comment by pdilyard** [comment] 2015-11-24 20:43
Go ahead, thanks!

**Comment by josevalim** [comment] 2015-11-24 20:59
Actually, we can't fix this. Since the error is coming from Erlang, we no longer have a distinction between a variable and a function call, which means changing this would mean we would change the message for both `x` and `x()`. This will be a won't fix for now. Sorry.

**Closed by josevalim** 2015-11-24 20:59 UTC
Labels: Kind:Bug, Level:Starter
