### ISSUE TITLE
Path.wildcard unexpected results if file name contains square brackets

### ISSUE THREAD

**Issue by wstucco** [elixir-lang/elixir#4618] opened 2016-05-13 12:07 UTC
`Path.wildcard` (`:filelib.wildcard` as well) has a problem with file names with square brackets. 
You get an empty list, even after quoting the brackets.   

* Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Elixir 1.2.5
* OS X 10.11.4

```elixir
iex(10) > Path.wildcard "abc[def]*" 
[]
iex(10) > Path.wildcard "abc\[def\]*" 
[]
iex(10) > Path.wildcard "abc\\[def\\]*" 
[]

# this one actually works
iex(10) > Path.wildcard "abc[[]def[]]*" 
["abc[def].txt", "abc[def].md"]
```

Is this the official behaviour?   
I haven't found documentation about this.

**Comment by josevalim** [comment] 2016-05-13 12:09
Please try:

    Path.wildcard "abc\\[def\\]*"

But yes, it is expected behaviour. You can see in the docs for filelib:

http://erlang.org/doc/man/filelib.html#wildcard-1

Patches to improve the docs in Elixir are always welcome :D

**Comment by wstucco** [comment] 2016-05-13 12:16
Thanks for the super quick answer! :)  
My bad, sorry, I edited the previous comment to make it more clear. 

It doesn't work (for me) anyway, even after double quoting the brackets. 
I read the documentation on the Erlang page and I thought that being special characters I just needed to quote them, but it does not work.   
Is the solution to use `[]`?

**Comment by josevalim** [comment] 2016-05-13 14:15
It seems to be so as apparently you can't escape []. When you write `[[]` and `[]]`, you are basically saying that you are only allowing `[` and `]` respectively, which makes sense and works. Anyway, a PR for the docs is welcome. I am closing this for now as it is not a code issue. :) Thank you!

**Closed by josevalim** 2016-05-13 14:15 UTC
