### ISSUE TITLE
Elixir 1.17 crushes when ran with OTP-27 on Windows

### ISSUE THREAD

**Issue by Iftakharpy** [elixir-lang/elixir#13949] opened 2024-11-01 16:55 UTC
### Elixir and Erlang/OTP versions

When I try to run `elixir --version` the command produces `erl_crash.dump` file

![image](https://github.com/user-attachments/assets/1cc87356-4dfe-40f0-ad53-3c0bba6827ca)

I have the following `erts` versions installed
![image](https://github.com/user-attachments/assets/4cb730a8-5703-458c-8afc-3e520e5341fb)

### Operating system

Windows 11 Home Version 23H2 ( OS Build 22631.4317 )

### Current behavior

I installed OTP-27 with Elixir 1.17. When I try to run iex from the command line it crushes the same happens with other binaries like elixir.

### Expected behavior

Run `iex`, `elixir`, `elixirc` and `mix` without any errors.

**Comment by Iftakharpy** [comment] 2024-11-01 16:59
https://filebin.net/01mon199o08wftjo this is where I uploaded the `erl_crash.dump`

**Comment by Iftakharpy** [comment] 2024-11-01 22:22
```PS
PS C:\Users\iftak> erl
The code server called the unloaded module `erl_prim_loader'

Crash dump is being written to: erl_crash.dump...done
PS C:\Users\iftak> elixir --short-version
1.17.3
```

**Comment by josevalim** [comment] 2024-11-02 08:25
If you cannot start `erl`, then that's an Erlang issue, not an Elixir one. I'd recommend uninstall Erlang and installing it again.

**Comment by Iftakharpy** [comment] 2024-11-02 09:01
Tried that several times. Didn't fix anything. Then I installed erlang version 26 and elixir version 1.6 which worked.

```ps
PS C:\Users\iftak> elixir --version
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.16.3 (compiled with Erlang/OTP 26)
```

Here I don't know why it's using `erts-14.0.2` when I have later versions of those in the `Erlang OTP` installation directory. Is that something I should worry about?

**Comment by josevalim** [comment] 2024-11-02 09:08
erts-14.0.2 is fine. Erlang is made of several libraries, one of them being erts-14.0.2.

I will close this issue, because the issue is with the Erlang installation, in particular, OTP 27. Once there is a new OTP 27 release (or OTP 28), you can migrate to latest. For now, rolling with OTP 26 is fine!

**Closed by josevalim** 2024-11-02 09:08 UTC

**Comment by Iftakharpy** [comment] 2024-11-02 09:12
Thank you very much!

**Comment by Iftakharpy** [comment] 2024-11-02 15:08
Turns out the problem was I had forgotten I installed elixir with `choco`.  Which didn't remove executables like `erl`, `erlc` and others. I had to manually remove those from `C:\ProgramData\chocolatey\bin` directory. Then I installed the elixir and erlang which finally works.
