### ISSUE TITLE
On Windows, make test leaves Erlang process running even after "make.exe" terminates

### ISSUE THREAD

**Issue by xiamx** [elixir-lang/elixir#6149] opened 2017-05-25 00:27 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Erlang 18.3 and 18.2. Elixir master branch
* Operating system: Windows 10 x64

### Current behavior

On Windows, `make test` leaves erlang process running even after make.exe terminates.

### Expected behavior

`make test` terminates all child erlang process when it exits.

See https://github.com/elixir-lang/elixir/pull/6143#issuecomment-303875508

**Comment by robi-wan** [comment] 2017-05-27 20:23
As @josevalim [mentioned](https://github.com/elixir-lang/elixir/pull/6154#issuecomment-304256432) the hanging `erl` processes are created during `make test_mix`. I think the cause are the tests [`"--listen-on-stdin: runs tests after input"`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/test_test.exs#L119-L129) and[ ` "--listen-on-stdin: does not exit on compilation failure"`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/test_test.exs#L131-L181) in [`lib/mix/test/mix/tasks/test_test.exs`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/test_test.exs).

These tests use the `mix test` option `--listen-on-stdin` introduced in https://github.com/elixir-lang/elixir/issues/4919.

**Comment by josevalim** [comment] 2017-05-27 20:34
There is also EPMD, which also had to be closed by hand.

Both EPMD and the VMs spawned by `mix test` listen on the standard input and terminates once stdin is closed. It seems the OS is not closing the stdin once the parent process is dead.

**Comment by xiamx** [comment] 2017-05-30 14:54
Could it be that the msys make.exe does not know how to send the right kill signal to erl and epmd upon termination?

**Comment by josevalim** [comment] 2017-09-03 14:53
We are explicitly terminating the linked processes for now. Since the root issue seems to be the CI server, we are closing this one for now. If someone can reproduce this locally, please let us know.

**Closed by josevalim** 2017-09-03 14:53 UTC
Labels: Kind:Chore, Note:Windows
