### ISSUE TITLE
Compiling is very slow on filesystems with slow directory access

### ISSUE THREAD

**Issue by martin-langhoff** [elixir-lang/elixir#4993] opened 2016-07-11 14:49 UTC
When compiling over a FS that has slow `open()`, `stat()` and company, builds are painfully slow. This affects builds over NFS and `vboxsf` (VirtualBox, often under Vagrant).

An initial rookie diagnosis: stracing the build (with `-e trace=file`) shows each directory and file path is hit many times with `open()`, `openat()`, `stat()`, etc. A quick read of `lib/compilers/elixir.ex` and `mix/utils.ex` leads me to suspect initially of `Mix.Utils.extract_*`. The logic flow leads to many queries to the OS about the same file path.

**Comment by ericmj** [comment] 2016-07-11 14:58
It would be great if you could provide an elixir project where this happens and the commands you run.

**Comment by josevalim** [comment] 2016-07-11 16:35
A project would be great. If an open source project like Plug is enough to reproduce this, even better. But in general, yes, let's see if we can do less queries because it will benefit everyone.

**Comment by martin-langhoff** [comment] 2016-07-12 17:46
I'll try. I made a stab yesterday with Plug. It shows 3 or 6 attempts at opening each path, because:

* paths are tried as `./foo/doo.ex` and then again as 'foo/doo.ex`. At first blush, these are equivalent.
* paths are first opened as directories, then as files

```
mix compile 
strace -f -e trace=file -o /tmp/mytrace mix compile 
```

I have a (private) project which shows other aspects of very slow compile; unsure why; working on diagnosing further and getting a repro case I can share.

**Comment by antipax** [comment] 2016-07-17 17:42
Not sure if we have a good example yet, but I'd like to take a shot at improving the situation here. What does everyone think about providing some kind of cache for Mix file operation? I'm thinking of something like `Mix.File` which wraps the read-related operations of the `File` API and provides cached operations for mix tasks. 

If we took this approach, the question of course would be when that cache is invalidated. We could cache over the entire mix invocation, which might work well assuming that input files are never modified by mix tasks. Another option would be to cache over each individual mix task, which would perhaps be safer, but might result in multiple reads for the same information as we currently are running into. Finally, it could be entirely opt-in, using some kind of reference which a process which wishes to cache operations must maintain in its state to refer to a cache of previous operations.

Thoughts?

**Comment by ericmj** [comment] 2016-07-17 17:46
We have discussed using a cache for the file stat operations and I even made an implementation for it. But like you said the issue is invalidation. I would rather try to look at if we can refactor the code to only stat a file once.

**Comment by antipax** [comment] 2016-07-17 17:48
@ericmj that's very fair, and I think certainly attempting to reduce operations would be a great start in any event.

Would anyone be opposed to me taking a shot at reducing the FS op count in `Mix.Compilers.Elixir`?

**Comment by josevalim** [comment] 2016-07-17 19:57
@antipax I would like first to see which stat operations are happening in access. For example, it is very likely we are stat-ing the `Mix.Project.config_files` multiple times through the compilers and those are straight-forward to cache in "compile" and then delete the cache after the compilers ran. However, for the other ones, different solutions may be required. Sometimes the cache can be a map in the task itself, which is easy because we don't need to worry about invalidation.

**Comment by antipax** [comment] 2016-07-17 21:07
Ok cool. I'm going to try to combine some instrumentation in `File` with
dtruss to figure out exactly where the ops are coming from.

**Comment by antipax** [comment] 2016-07-18 02:05
Here's the output from my instrumented build with strace trace=file outputting to the terminal. The instrumentation I added prints "lib/blah/file.ex:12: File.read/1", if, for instance, File.read/1 was called at lib/blah/file.ex line 12.

https://gist.github.com/antipax/67ffad57831b314bff4533f0e39dac04

You can search for "Compiling 44 files (.ex)" in the log to see when the elixir compilation starts.

One interesting thing to note is that any mix FS operations seem to be massively dwarfed by `stat`s for .beam loads, which (as one would expect if you think about it) check every directory in the load paths for each module which needs to be loaded. `File.regular?/1` seems to *maybe* be doing more work than it should, but I'm not 100% sure, since the strace logging may be occurring at any time after the `File` instrumentation log.

Given that any mix-related FS activity seems to be completely irrelevant in relation to the activity of Erlang itself in loading beams, I'm not sure how much it is possible to improve the situation from the Elixir end. However, if potentially we are loading beams more than once during compilation, this may be an area to look at for a quick win in terms of FS ops during compilation.

**Comment by josevalim** [comment] 2016-07-18 15:03
> However, if potentially we are loading beams more than once during compilation, this may be an area to look at for a quick win in terms of FS ops during compilation.

I would only expect this to happen during protocol consolidation.

@martin-langhoff can you please set: `consolidate_protocols: false` in your `mix.exs` file and let us know if it impacts the performance of compiling your code in any considerably way when you run `mix compile` afterwards?

**Comment by josevalim** [comment] 2016-07-18 15:03
Btw, great job @antipax !

**Comment by josevalim** [comment] 2016-07-24 07:44
@martin-langhoff ping?

Unless we find out that consolidation is slow, I believe we can close this one.

**Comment by josevalim** [comment] 2016-08-04 18:25
Closing. Let us know if you have more info @martin-langhoff.

**Closed by josevalim** 2016-08-04 18:25 UTC
Labels: App:Mix, Kind:Bug

**Comment by martin-langhoff** [comment] 2016-08-04 21:14
Hi folks! Getting back on deck after a couple weeks of holiday. Will report on this soon (tomorrow or monday). Apologies for the blackout.
