### ISSUE TITLE
Trouble defining struct in dynamically named module

### ISSUE THREAD

**Issue by ijcd** [elixir-lang/elixir#4894] opened 2016-06-26 21:04 UTC
### Environment

This happens in 1.2.5 and 1.3.0. It seems this only fails in the interpreted mode. It works under compilation.

% elixir --version
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
### Current behavior

% cat foo.ex
```
defmodule Module.concat(["Foo"]) do
  defstruct name: nil, age: 5

  def whostruct do
    %__MODULE__{}
  end
end
```

```
% elixir foo.ex
** (CompileError) foo.ex:5: Foo.__struct__/0 is undefined, cannot expand struct Foo
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4

% iex
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> import_file "foo.ex"
** (CompileError) iex:5: Foo.__struct__/0 is undefined, cannot expand struct Foo
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
iex(1)> c "foo.ex"
[Foo]
iex(2)> Foo.whostruct
%Foo{age: 5, name: nil}
```

### Expected behavior

I would expect `__struct__/0` to be defined whether this was compiled or not. This works fine if the module is statically named.

**Comment by whatyouhide** [comment] 2016-06-27 08:09
Looking into this.

**Comment by josevalim** [comment] 2016-06-28 09:27
I have a fix for this. :)

**Comment by whatyouhide** [comment] 2016-06-28 09:28
@josevalim yep, I think I found the cause yesterday (we don't put the module in `:context_modules`) and would have fixed during lunch, but go ahead if you have a fix now :)

**Closed** 2016-06-28 09:30 UTC
Labels: App:IEx, Kind:Bug, Level:Advanced
