### ISSUE TITLE
Doctest of a Map with a MapSet value fails

### ISSUE THREAD

**Issue by atelles** [elixir-lang/elixir#8523] opened 2018-12-14 23:45 UTC
### Environment

Erlang/OTP 21 [erts-10.1.3]
Elixir 1.7.4 (compiled with Erlang/OTP 21)

### Current behavior
The following Doctest fails
```
  @doc """
  ## Examples

      iex> TestMapSet.test_map_set()
      %{set: #MapSet<["a"]>}
  """
  def test_map_set() do
    %{set: MapSet.new(["a"])}
  end
```
with the error:
```
Doctest did not compile, got: (TokenMissingError) lib/test_map_set.ex:9: missing terminator: } (for "{"starting at line 9)
     code: %{set: #MapSet<["a"]>}
     stacktrace:
       lib/test_map_set.ex:9: TestMapSet (module)
```

**Comment by josevalim** [comment] 2018-12-15 07:38
We talk about those cases here: https://hexdocs.pm/ex_unit/ExUnit.DocTest.html#module-opaque-types

I.e. some types do not have a valid Elixir printable representation, so you have to break them apart.

**Comment by atelles** [comment] 2018-12-15 10:00
Thanks for the clarification.

Should we add this information to the MapSet docs? Adding that it is an **opaque type** with a link to the Doctest documentation for more information?

My rationale is that there are doctests examples on MapSet, so I thought they would work.

**Comment by josevalim** [comment] 2018-12-15 13:59
@atelles the problem is that this information can  be confusing if your intent is to learn about MapSet. However, we can probably improve the error message here. Maybe if the input has a `TokenMissingError`, maybe we can check if it has a `#...<`inside of it and, if so, augment the error message.

**Comment by joaothallis** [comment] 2018-12-26 11:54
You can leave so its documentation
```elixir
  @doc """
  ## Examples

      iex> TestMapSet.test_map_set()
      %{set: MapSet.new(["a"])}
  """

**Comment by fertapric** [comment] 2019-01-20 16:32
I'm currently working on this one :)

**Comment by josevalim** [comment] 2019-01-20 18:50
Closed in favor of PR.

**Closed by josevalim** 2019-01-20 18:50 UTC
Labels: App:ExUnit, Kind:Bug, Note:Discussion
