### ISSUE TITLE
Crash on elixir-LS testsuite and broken test output

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11371] opened 2021-11-07 09:33 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.0-rc.0 (48b838a) (compiled with Erlang/OTP 24)
* Operating system: macOS

### Current behavior

When running tests in elixir-LS debugger app an error is reported.
```
(Debugger) Initialization failed because an exception was raised:
10:18:20.359 [error] Process #PID<0.655.0> raised an exception
** (Mix.Error) Could not find an SCM for dependency :excoveralls from ElixirSense.Mixfile
    (mix 1.13.0-rc.0) lib/mix.ex:515: Mix.raise/2
    (mix 1.13.0-rc.0) lib/mix/dep/loader.ex:201: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.13.0-rc.0) lib/mix/dep/loader.ex:147: Mix.Dep.Loader.to_dep/3
    (elixir 1.13.0-rc.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.13.0-rc.0) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/2
    (mix 1.13.0-rc.0) lib/mix/dep/loader.ex:322: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.13.0-rc.0) lib/mix/project.ex:396: Mix.Project.in_project/4
    (elixir 1.13.0-rc.0) lib/file.ex:1560: File.cd!/2
    (mix 1.13.0-rc.0) lib/mix/dep.ex:268: Mix.Dep.in_dependency/3
    (mix 1.13.0-rc.0) lib/mix/dep/loader.ex:101: Mix.Dep.Loader.load/2
    (mix 1.13.0-rc.0) lib/mix/dep/converger.ex:196: anonymous fn/4 in Mix.Dep.Converger.all/9
    (mix 1.13.0-rc.0) lib/mix/dep/converger.ex:192: Mix.Dep.Converger.all/9
    (mix 1.13.0-rc.0) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
    (mix 1.13.0-rc.0) lib/mix/dep/converger.ex:72: Mix.Dep.Converger.all/4
    (mix 1.13.0-rc.0) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix 1.13.0-rc.0) lib/mix/dep.ex:193: Mix.Dep.converge/1
    (mix 1.13.0-rc.0) lib/mix/dep.ex:114: Mix.Dep.load_and_cache/0
    (mix 1.13.0-rc.0) lib/mix/tasks/deps.loadpaths.ex:26: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.13.0-rc.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0-rc.0) lib/mix/tasks/loadpaths.ex:40: Mix.Tasks.Loadpaths.run/1
```
To reproduce
1. clone https://github.com/elixir-lsp/elixir-ls
2. mix deps.get
3. mix deps.update elixir_sense (needed as the version used on master is crashing with 1.13)
4. cd apps/elixir_ls_debugger
5. mix test

The error does not happen on every run but even if doesn't the test output is strange. It looks like some reporting server is crashing and restarting a few times.

```
mix test
warning: use Mix.Config is deprecated. Use the Config module instead
  /Users/lukaszsamson/vscode-elixir-ls/elixir-ls/config/config.exs:3

==> elixir_sense
Compiling 53 files (.ex)
Generated elixir_sense app
==> elixir_ls_debugger
Compiling 8 files (.ex)
Generated elixir_ls_debugger app
Excluding tags: [pending: true]

warning: use Mix.Config is deprecated. Use the Config module instead
  /Users/lukaszsamson/vscode-elixir-ls/elixir-ls/config/config.exs:3

...warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated mix_project app
Excluding tags: [:test]
Including tags: [:quadruple]

.

Finished in 0.04 seconds (0.00s async, 0.04s sync)
2 tests, 0 failures, 1 excluded

Randomized with seed 489589
...warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated mix_project app
Excluding tags: [:test]
Including tags: [:quadruple]

.

Finished in 0.03 seconds (0.00s async, 0.03s sync)
2 tests, 0 failures, 1 excluded

Randomized with seed 489589
.warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated mix_project app
..warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated mix_project app
.warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated mix_project app
.....

Finished in 8.5 seconds (0.00s async, 8.5s sync)
15 tests, 0 failures

Randomized with seed 489589
```

### Expected behavior

No error as on earlier versions

**Comment by josevalim** [comment] 2021-11-07 12:01
You are stopping the Mix application and then starting it:

https://github.com/elixir-lsp/elixir-ls/blob/master/apps/elixir_ls_utils/test/support/mix_test.case.ex#L77-L78

This means the Mix.SCM state is reset and, because Hex is still started, it never restarts and the Hex SCM is never added back. You could stop Hex as well, and that will fix the issue, but ideally you want to find public APIs to reset the desired Mix state. The nondeterminism is due to test ordering (tests using fixtures are the ones resetting the state).

The reason why it worked before is because something was restarting Hex before. I am trying to pinpoint what was it.

**Comment by josevalim** [comment] 2021-11-07 12:03
> The reason why it worked before is because something was restarting Hex before. I am trying to pinpoint what was it.

Actually, I can consistently reproduce the failure on v1.12 too. I forgot to remove the fix when I switched Elixir branches. :) Closing this as it doesn't appear to be a regression. Thanks!

**Closed by josevalim** 2021-11-07 12:03 UTC

**Comment by lukaszsamson** [comment] 2021-11-08 14:43
Thanks for looking into @josevalim
