### ISSUE TITLE
Elixir / absinthe not expanding description and @desc in query results

### ISSUE THREAD

**Issue by FloatingFront** [elixir-lang/elixir#8876] opened 2019-03-11 14:00 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
$ elixir -v
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 21)

* Operating system: 
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

### Current behaviour
[ sorry, but this is a lengthy entry ]

I am completely new to the fascinating elixir, absinthe and erlang ecosystem, but I think I might be onto something in the regard of why description and @desc don't show up in query results (see the original message https://github.com/absinthe-graphql/absinthe/issues/650 and my regrettably inadvertanly slightly offensive/impolite message header https://github.com/absinthe-graphql/absinthe/issues/695 )

My elbow grease can only get me so far, but providing you with this trace might allow you to quickly tap into your brainpower to see the solution.

Maybe I am on the completely wrong path, it could be located somewhere else but my gut instinct would suggest argument expansion somewhere not happening as it should (expand_arg/expand_args ???).

```
From:elixir_expand.erl
 
15 %% Literal operators
16 
17 expand({'{}', Meta, Args}, E) ->
18   {EArgs, EA} = expand_args(Args, E),
19   {{'{}', Meta, EArgs}, EA};
20
21 expand({'%{}', Meta, Args}, E) ->
22   elixir_map:expand_map(Meta, Args, E);
23
24 expand({'%', Meta, [Left, Right]}, E) ->
25   elixir_map:expand_struct(Meta, Left, Right, E);
26
27 expand({'<<>>', Meta, Args}, E) ->
28   elixir_bitstring:expand(Meta, Args, E, false); <-- does changing last argument to true fix this?
29
30 expand({'->', Meta, _Args}, E) ->
31   form_error(Meta, ?key(E, file), ?MODULE, unhandled_arrow_op); 
```

 ==== changed last argument in line 28 above from false to true, did a recompile, and got the following error (sorry, but I am giving you the full, raw output for overall clarity purposes):

```
$ make clean test
 rm -rf ebin
 rm -rf lib/*/ebin
 rm -rf lib/elixir/src/elixir_parser.erl
 rm -rf lib/*/_build/
 rm -rf lib/*/tmp/
 rm -rf lib/elixir/test/ebin/
 rm -rf lib/mix/test/fixtures/deps_on_git_repo/
 rm -rf lib/mix/test/fixtures/git_rebar/
 rm -rf lib/mix/test/fixtures/git_repo/
 rm -rf lib/mix/test/fixtures/git_sparse_repo/
 rm -f erl_crash.dump
 rm -f man/elixir.1
 rm -f man/elixir.1.bak
 rm -f man/iex.1
 rm -f man/iex.1.bak
 Recompile: src/elixir_utils
 Recompile: src/elixir_tokenizer
 Recompile: src/elixir_sup
 Recompile: src/elixir_rewrite
 Recompile: src/elixir_quote
 Recompile: src/elixir_parser
 Recompile: src/elixir_overridable
 Recompile: src/elixir_module
 Recompile: src/elixir_map
 Recompile: src/elixir_locals
 Recompile: src/elixir_lexical
 Recompile: src/elixir_interpolation
 Recompile: src/elixir_import
 Recompile: src/elixir_fn
 Recompile: src/elixir_expand
 Recompile: src/elixir_errors
 Recompile: src/elixir_erl_var
 Recompile: src/elixir_erl_try
 Recompile: src/elixir_erl_pass
 Recompile: src/elixir_erl_for
 Recompile: src/elixir_erl_compiler
 Recompile: src/elixir_erl_clauses
 Recompile: src/elixir_erl
 Recompile: src/elixir_env
 Recompile: src/elixir_dispatch
 Recompile: src/elixir_def
 Recompile: src/elixir_config
 Recompile: src/elixir_compiler
 Recompile: src/elixir_code_server
 Recompile: src/elixir_clauses
 Recompile: src/elixir_bootstrap
 Recompile: src/elixir_bitstring
 Recompile: src/elixir_aliases
 Recompile: src/elixir
 Generated elixir.app
 ==> bootstrap (compile)
 error: undef
 stacktrace: [{'Elixir.CompileError',exception,
                  [[{description,
                        <<"a binary field without size is only allowed at the end of a binary pattern and never allowed in binary generators">>},
                    {file,
                        <<"/Users/Friddev/dev/FloatingFront/elixir/elixir/lib/elixir/lib/kernel.ex">>},
                    {line,1769}]],
                  []},
              {elixir_errors,raise,4,
                  [{file,"src/elixir_errors.erl"},{line,149}]},
              {elixir_bitstring,expand_specs,6,
                  [{file,"src/elixir_bitstring.erl"},{line,170}]},
              {elixir_bitstring,expand,8,
                  [{file,"src/elixir_bitstring.erl"},{line,41}]},
              {elixir_bitstring,expand,4,
                  [{file,"src/elixir_bitstring.erl"},{line,20}]},
              {elixir_expand,expand_args,2,
                  [{file,"src/elixir_expand.erl"},{line,599}]},
              {elixir_expand,expand_remote,7,
                  [{file,"src/elixir_expand.erl"},{line,783}]},
              {elixir_expand,expand_args,2,
                  [{file,"src/elixir_expand.erl"},{line,599}]}]
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 1
```
==== and followed where it led me: ====

```
elixir_expand.erl:

579 %% Variables in arguments are not propagated from one
580 %% argument to the other. For instance:
581 %%
582 %%   x = 1
583 %%   foo(x = x + 2, x)
584 %%   x
585 %%
586 %% Should be the same as:
587 %%
588 %%   foo(3, 1)
589 %%   3
590 %%
591 %% However, lexical information is.
592 expand_arg(Arg, Acc) when is_number(Arg); is_atom(Arg); is_binary(Arg); is_pid(Arg) ->
593   {Arg, Acc};
594 expand_arg(Arg, {Acc1, Acc2}) ->
595   {EArg, EAcc} = expand(Arg, Acc1),
596   {EArg, {elixir_env:mergea(Acc1, EAcc), elixir_env:mergev(Acc2, EAcc)}}. <-- mergea mand mergev look interesting?
597
```

==== elixir_env:mergea(Acc1, EAcc) and elixir_env:mergev(Acc2, EAcc) in elixir_expand.erl: (line 596) looked interesting, dug a little deeper...

```
 elixir_env.erl:
 51 %% SCOPE MERGING
 52
 53 %% Receives two scopes and return a new scope based on the second
 54 %% with their variables merged.
 55 %% Unrolled for performance reasons.
 56 mergev(#{unused_vars := U1, current_vars := C1},
 57        #{unused_vars := U2, current_vars := C2} = E2) ->
 58   if
 59     C1 =/= C2 ->
 60       if
 61         U1 =/= U2 ->
 62           C = merge_vars(C1, C2),
 63           E2#{vars := maps:keys(C), unused_vars := merge_vars(U1, U2), current_vars := C};
 64         true ->
 65           C = merge_vars(C1, C2),
 66           E2#{vars := maps:keys(C), current_vars := C}
 67       end;
 68
 69     U1 =/= U2 ->
 70       E2#{unused_vars := merge_vars(U1, U2)};
 71
 72     true ->
 73       E2
 74   end.
 75
 76 %% Receives two scopes and return the later scope
 77 %% keeping the variables from the first (imports
 78 %% and everything else are passed forward).
 79 %% Unrolled for performance reasons.
 80 mergea(#{unused_vars := U1, current_vars := C1, vars := V1},
 81        #{unused_vars := U2, current_vars := C2} = E2) ->
 82   if
 83     C1 =/= C2 ->
 84       if
 85         U1 =/= U2 ->
 86           E2#{vars := V1, unused_vars := U1, current_vars := C1}; <-- change to maps:keys(V1) ?
 87         true ->
 88           E2#{vars := V1, current_vars := C1} <-- change to maps:keys(V1) ?
 89       end;
 90     U1 =/= U2 ->
 91       E2#{unused_vars := U1};
 92     true ->
 93       E2
 94   end.
```

==== in elixir_env.erl: in mergea lines 86 and 88 : did the following changes (I am simply mirroring lines 63 and 66 in mergev :-) ): 

```
---- from this:

 82   if
 83     C1 =/= C2 ->
 84       if
 85         U1 =/= U2 ->
 86           E2#{vars := V1, unused_vars := U1, current_vars := C1}; <-- change to maps:keys(V1) ?
 87         true ->
 88           E2#{vars := V1, current_vars := C1} <-- change to maps:keys(V1) ?
 89       end;
 90     U1 =/= U2 ->
 91       E2#{unused_vars := U1};
 92     true ->
 93       E2
 94   end.

---- to this:

 82   if
 83     C1 =/= C2 ->
 84       if
 85         U1 =/= U2 ->
 86           E2#{vars := maps:keys(V1), unused_vars := U1, current_vars := C1};
 87         true ->
 88           E2#{vars := maps:keys(V1), current_vars := C1}
 89       end;
 90     U1 =/= U2 ->
 91       E2#{unused_vars := U1};
 92     true ->
 93       E2
 94   end.
```

==== recompiled, and got the same error as at the start (see top of this listing):
==== changed last argument in line 28 in elixir_expand.erl back to false, did a recompile, which got me the following:

```
$ make clean test
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/src/elixir_parser.erl
rm -rf lib/*/_build/
rm -rf lib/*/tmp/
rm -rf lib/elixir/test/ebin/
rm -rf lib/mix/test/fixtures/deps_on_git_repo/
rm -rf lib/mix/test/fixtures/git_rebar/
rm -rf lib/mix/test/fixtures/git_repo/
rm -rf lib/mix/test/fixtures/git_sparse_repo/
rm -f erl_crash.dump
rm -f man/elixir.1
rm -f man/elixir.1.bak
rm -f man/iex.1
rm -f man/iex.1.bak
Recompile: src/elixir_utils
Recompile: src/elixir_tokenizer
Recompile: src/elixir_sup
Recompile: src/elixir_rewrite
Recompile: src/elixir_quote
Recompile: src/elixir_parser
Recompile: src/elixir_overridable
Recompile: src/elixir_module
Recompile: src/elixir_map
Recompile: src/elixir_locals
Recompile: src/elixir_lexical
Recompile: src/elixir_interpolation
Recompile: src/elixir_import
Recompile: src/elixir_fn
Recompile: src/elixir_expand
Recompile: src/elixir_errors
Recompile: src/elixir_erl_var
Recompile: src/elixir_erl_try
Recompile: src/elixir_erl_pass
Recompile: src/elixir_erl_for
Recompile: src/elixir_erl_compiler
Recompile: src/elixir_erl_clauses
Recompile: src/elixir_erl
Recompile: src/elixir_env
Recompile: src/elixir_dispatch
Recompile: src/elixir_def
Recompile: src/elixir_config
Recompile: src/elixir_compiler
Recompile: src/elixir_code_server
Recompile: src/elixir_clauses
Recompile: src/elixir_bootstrap
Recompile: src/elixir_bitstring
Recompile: src/elixir_aliases
Recompile: src/elixir
Generated elixir.app
==> bootstrap (compile)
Compiled lib/elixir/lib/kernel.ex
Compiled lib/elixir/lib/macro/env.ex
Compiled lib/elixir/lib/keyword.ex
error: {badmap,[{module,nil}]}
stacktrace: [{maps,keys,[[{module,nil}]],[]},
             {elixir_env,mergea,2,[{file,"src/elixir_env.erl"},{line,86}]},
             {elixir_expand,expand_arg,2,
                            [{file,"src/elixir_expand.erl"},{line,596}]},
             {lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},
             {lists,mapfoldl,3,[{file,"lists.erl"},{line,1355}]},
             {elixir_expand,expand_args,2,
                            [{file,"src/elixir_expand.erl"},{line,604}]},
             {elixir_expand,expand_local,4,
                            [{file,"src/elixir_expand.erl"},{line,771}]},
             {elixir_clauses,def,2,
                             [{file,"src/elixir_clauses.erl"},{line,19}]}]
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 1
```
 
And now I admit defeat 8=)

Over to you?

**Comment by josevalim** [comment] 2019-03-11 14:17
Hi @FloatingFront,

The changes you are proposing to Elixir are incorrect. We do not require_size on regular <<>> expansion. Similarly, we don't want to get keys of V1, we want to pass V1 as is.

Unfortunately the Elixir team does not have the bandwidth to debug community projects. Therefore I will close this issue unless the issue is minimized to a point that shows it is an Elixir bug.

I cannot speak for the absinthe team, but as a maintainer, I can give the following feedback:

1. Close the duplicated issue. If there is already an existing issue, it is best to consolidate all information in one place.

2. It is unlikely the issue is being ignored. Projects are often maintained by developers in their free time, so it is likely they did not have the time to get to it. Remember most projects have a large community of users and few maintainers.

3. If you want to help the issue be addressed faster, you can contribute a solution! Maybe figuring out the full solution is hard but if you can provide a pull request with a failing test, that will likely speed up the process. I would estimate most of time as a maintainer is actually spent on reproducing bugs rather than fixing them.

4. Get involved! Maybe you can't fix that issue but you can fix and contribute to other ones, and that will help them get to your issue faster. Maybe you are already doing this, but I thought I would mention it for completeness.

**Closed by josevalim** 2019-03-11 14:17 UTC
