### ISSUE TITLE
warning msg misdirects

### ISSUE THREAD

**Issue by frpaulas** [elixir-lang/elixir#4465] opened 2016-04-01 16:16 UTC
### Environment

* Elixir version (elixir -v): 1.2.0
* Operating system: os x 10.11.4

### Current behavior
iex -S mix gives the following warning

> mix.exs:12: warning: undefined module attribute @version, please remove access to @version or explicitly set it before access

for mix.exs at https://gist.github.com/frpaulas/771d87084bad800a56442f4360467556
when the issue is:  @version is undefined in deps/mock/mix.exs

defining @version in deps/mock/mix.exs clears the warning

### Expected behavior

It would be good if the warning said something like "deps/mock/exs:12 warning etc."

Thanks for the help
paul

**Comment by josevalim** [comment] 2016-04-01 16:29
Yes, the issue is that we have CDed into that directory, which causes the warning to be out of place. I am not sure if we have a reasonable fix for this, unfortuntely.

**Comment by frpaulas** [comment] 2016-04-01 16:37
understand

**Comment by michalmuskala** [comment] 2016-04-01 17:01
A solution could be to print CWD with such errors in mix, if we know we'll be moving around.

**Comment by lexmag** [comment] 2016-04-01 18:19
> A solution could be to print CWD with such errors in mix, if we know we'll be moving around.

Maybe we can do something like this when `MIX_DEBUG` is set to `1`.

**Comment by ericmj** [comment] 2016-04-01 18:20
We should wrap errors when loading the mix.exs file of dependencies.

**Comment by josevalim** [comment] 2016-04-01 18:21
They are not errors though, they are warnings. That's the problem.


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by oarrabi** [comment] 2016-04-03 10:34
I would like to take this one if no one has started it

**Comment by josevalim** [comment] 2016-04-03 10:43
I don't think anybody is tackling it but we also haven't agreed on a
solution. What do you have in mind Omar? :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by oarrabi** [comment] 2016-04-03 10:47
Honestly, I dont have a solution in mind, I am trying to get any easy, starter level, task to work on :S.
I am still not experienced in implementing features in Elixir itself.
If you know of another starter level task then point me to it please :)

**Comment by josevalim** [comment] 2016-04-03 10:55
That's alright, @oarrabi, thanks for the interet! Because we don't have a solution yet, I will remove the Starter label for now. :)

**Comment by ericmj** [comment] 2016-04-03 14:13
We can capture any output from loading the file and then print it with `Mix.Shell` which will print print the app name.

**Comment by josevalim** [comment] 2016-04-03 18:33
That's a lot of code for this feature. We would need to capture both stdio and stderr. There is a chance for introducing bugs and I don't think the amount of code is worth it.

**Comment by michalmuskala** [comment] 2016-04-03 18:54
I'd say that having errors or warnings originating at a location that can't be easily identified is pretty bad, so some solution to this is needed - we can't leave it like this.

**Comment by josevalim** [comment] 2016-04-03 19:56
Let's also remember that Mix will show something like `==> deps name` when doing something inside a dependency.

**Comment by ericmj** [comment] 2016-04-03 19:58
@josevalim That's the issue actually. We don't show that when loading the mixfile of a dependency because the output doesn't go through Mix.Shell, hence we need to route stdout and stderr through Mix.Shell.

**Comment by josevalim** [comment] 2016-04-03 20:03
If there was an error, it would show the dep info. And if you compiled anything afterwards, it would also show it. I think a bit more info with MIX_DEBUG=1 would be enough to settle this.

Again, routing the stdout and stderr is a lot of work and very error prone because even if we start routing, we would need to somehow match on paths being printed, like "mix.exs:9" and convert them to the full path. Then there are paths without line numbers that may happen from to time, paths in stacktraces and so forth. Routing and changing all paths we see going through is just too risky and we will never get it right.

**Comment by ericmj** [comment] 2016-04-03 20:57
> Again, routing the stdout and stderr is a lot of work and very error prone because even if we start routing, we would need to somehow match on paths being printed, like "mix.exs:9" and convert them to the full path.

I am not suggesting rewriting paths inside strings, that's very error prone and fragile. I am simply saying that we should print `==> app name` for all output from dependencies. We do not rewrite paths or stacktraces for any errors from dependencies, we just write `==> app name` before so we should do the same here.

**Comment by josevalim** [comment] 2016-05-13 07:43
@ericmj it still comes from stderr and it is much harder to redirect from stderr than from stdout because we can't rely on the group leader. It is also not safe to do in terms of concurrency because it is registered locally. :(

**Closed** 2016-06-12 16:55 UTC
Labels: App:Mix, Kind:Bug, Level:Advanced
