### ISSUE TITLE
mix release fails with no erts-10.4.4 enoent

### ISSUE THREAD

**Issue by ulfa** [elixir-lang/elixir#9672] opened 2019-12-28 06:05 UTC
### Environment

* Erlang 22
* Elixir 1.9.4
* OSX

### Current behavior

I want to create a release without the erts, because i build the program on a Mac and want to deploy the tar file to a linux box. 

In my mix.exs I use the 

> steps: [:assemble, :tar]

When I run `MIX_ENV=prod mix release --version 0.0.1` then I get the following error:

> ** (MatchError) no match of right hand side value: {:error, {'...../erts-10.4.4', :enoent}}
>     (mix) lib/mix/tasks/release.ex:1039: Mix.Tasks.Release.make_tar/1
>     (mix) lib/mix/tasks/release.ex:959: Mix.Tasks.Release.run_steps/1
>     (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
>     (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
> make: *** [release] Error 1
> 

Include code samples, errors and stacktraces if appropriate.

### Expected behavior

When ich run mix release, i expect to get a tar file without erts and with my program inside, but I get the error above.

**Comment by josevalim** [comment] 2019-12-28 09:11
Thanks! This is a duplicate of #9570 which has been fixed in master.

**Closed by josevalim** 2019-12-28 09:11 UTC
