### ISSUE TITLE
elixir-websetup.exe error on Windows 7

### ISSUE THREAD

**Issue by BrandenSchwartz** [elixir-lang/elixir#4167] opened 2016-01-06 15:54 UTC
Once Erlang has been installed and immediately after clicking the elixir-websetup.exe to begin the install on Win7, I consistently receive the error "Runtime Error (at 114:542): List index out of bounds(1)" .  The install proceeds as expected on Win10.  

![elixir-websetup-error](https://cloud.githubusercontent.com/assets/4411865/12146760/6a87b130-b463-11e5-8a51-30ca4430c7b4.jpg)

**Comment by josevalim** [comment] 2016-01-06 15:58
Does it happen consistently?

**Comment by BrandenSchwartz** [comment] 2016-01-06 16:05
Yes, I first downloaded the web installer in November and have downloaded fresh copies a few times since (most recently an hour ago) in case there have been updates to the installer or a Win7 update addressed the error but the behavior hasn't changed.

**Comment by josevalim** [comment] 2016-01-06 16:09
@BrandenSchwartz we haven't changed the installer for a long time. I have no idea why this is happening, if it can be any of help, here is the source: https://github.com/elixir-lang/elixir-windows-setup. I would love if you could help debug it in anyway and help us further.

**Comment by bendennis** [comment] 2016-01-11 21:58
@BrandenSchwartz I was having a weird issue with the windows installer a couple weeks ago, and a ccleaner run fixed the issue. My installer was just hanging though, no error message. Huge shot in the dark, but maybe worth a try.

**Comment by josevalim** [comment] 2016-01-14 18:33
Closing this as there isn't much we can do without effectively reproducing it. Thank you

**Closed by josevalim** 2016-01-14 18:33 UTC

**Comment by JohnLunzer** [comment] 2016-05-05 12:51
This error message still occurs on windows 7. Writing this issue off as a "can't reproduce" and then giving an empty "thank you" leaves me feeling excluded and unimportant. It also gives an unfortunate first impression.

From a PR standpoint the appropriate thing to do would be to leave this issue open indefinitely (6 months to a year) while soliciting details about the setup of users who experience the issue. You'll find this approach requires the same amount of effort as closing an unfixed issue after considering it for 8 days, but without dismissing an entire user demographic.

**Comment by josevalim** [comment] 2016-05-05 13:13
Hi @JohnLunzer!

> leaves me feeling excluded and unimportant

That was certainly not our intention, sorry.

There are two things to consider here: Windows support is important for us. That's why we provide a installer in the first place.

It is also important for us to have *actionable* issues in the issues tracker. That's why we attempt to label and tag most opened issues. There is a very high cost in leaving a ticket that cannot be acted on open. Every time a maintainer needs to retag issues for release, every developer that decides to do some triage, will spend time on something that cannot be acted on. I have worked on issues tracker for OSS projects with more than 1000 opened issues to the point they had to declare "issue bankruptcy" and just close everything, which is the worst situation for both users and contributors.

I am outlining our "policy" so it becomes clearer that we didn't close because it did not matter, we closed because we cannot act on. A consequence of this policy is that we are also responsive on closed issues, because we understand someone, later on, can add more information.

That said, I remember trying to reproduce this on a Windows 7 computer and being unable to. If you have more information on this, we are all ears, otherwise, as previously said, there is nothing much we can do.

**Comment by josevalim** [comment] 2016-05-05 13:14
Alternatively, you can also try installing Elixir via Chocolatey: https://chocolatey.org/

**Comment by JohnLunzer** [comment] 2016-05-05 13:53
I understand your position. Being confined to only "open" and "closed" can cause misinterpretation. It is true those two statuses are not permanent but they each carry a connotation. Open confers a connotation of "present and unresolved" while Closed connotes "past and resolved". 

It appears that you're interpreting "Closed" more broadly to also include "unactionable but unresolved". Given this interpretation I recommend that if you close an unactionable issue without resolving it that it be labelled "unresolved". Otherwise your intent can be misinterpreted, as I am guilty of.

**Comment by JohnLunzer** [comment] 2016-05-05 13:56
As for providing more information. Usually not a lot to say about the installation itself as windows installs do not vary greatly. However, I can say that I am attempting the install from a corporate environment which entails all sorts of restrictions on access, specifically writing to certain locations. Even "run as admin" does not provide relief. But this could be a place to start.

Additionally it looks like the message "List index out of bounds" is generated in this file: https://github.com/jrsoftware/issrc/blob/master/Projects/Compile.pas . Which could provide further insight.

**Comment by josevalim** [comment] 2016-05-05 14:03
@JohnLunzer that's great feedback, thank you. Do you think the "Note:Needs more info" is enough or should we add a more explicit label?

**Comment by JohnLunzer** [comment] 2016-05-05 14:12
"Needs more info" implies an unresolved status but still lacks an explicitness that would prevent the status of the issue being misinterpreted. Stealing some zen: "Explicit is better than implicit". "Unresolved", while big and ugly can never be misinterpreted.

**Comment by josevalim** [comment] 2016-05-05 15:21
@JohnLunzer I have changed the label to Unresolved and made it red. :) Thank you!

**Comment by JohnLunzer** [comment] 2016-05-06 12:05
After stinking things up I think I've come close to the conclusion. By pure chance I was disconnected from my VPN and attempted to run the installer and it worked! The VPN I connect to disallows most SSL connections. A guess is that there is an https access issue, this has thwarted my installation of many things.

**Comment by josevalim** [comment] 2016-05-06 14:52
@JohnLunzer thank you! We can probably check those in the installer and maybe raise better error messages? Let's page @chyndman in case he has an idea. :)

**Comment by BrandenSchwartz** [comment] 2016-05-06 15:00
Interestingly, I've never been on a VPN from the machine where I initially experienced the issue because I'm inside my organisation's firewall, but I downloaded a fresh copy of the elixir-websetup.exe this morning when I saw this comment and with no other changes to my machine or network environment (that I'm aware of) it worked for me as well.

**Comment by chyndman** [comment] 2016-05-06 15:59
Sounds like downloading .csv release information files was failing for you guys; perhaps the issue went away after [this commit](https://github.com/elixir-lang/elixir-lang.github.com/commit/9b232db38fcee35ca07b41b0fbc753294c7d38ee).  Still strange given that I'm catching download errors [here](https://github.com/elixir-lang/elixir-windows-setup/blob/master/ElixirWeb.iss#L223).  At any rate, new versions of Inno Setup and the Inno Download plugin are out, so maybe recompiling on those versions might help.

In general though, would a way to generate offline installers be beneficial to those of you behind firewalls?  Currently the web installer literally compiles an offline installer and runs it; would it be helpful if we documented how to get this offline installer from the temp files, or even provided an option to save it to a custom location instead of running it?

**Comment by JohnLunzer** [comment] 2016-05-06 16:47
I think that an offline installer would be a great idea.

**Comment by steflef** [comment] 2016-06-03 13:28
Same problem here: Runtime Error (at 113:542): List index out of bounds(1)" . 
Win 7 behind firewalls in a large corporation.

We have the same problem with npm (proxy, ports, etc.), but at least the main node.js is a complete install.
Without an offline installer, it's very difficult to even try elixir.
Thanks!

Will try from home  ;)

**Comment by josevalim** [comment] 2016-06-03 16:17
Hi @steflef, don't forget you can use the precompiled package: http://elixir-lang.org/install.html#precompiled-package

Maybe we should ship with an offline installer but I am really concerned about having to build a new installer for new releases. @chyndman already said he could take care of it, and it is really appreciated, but preferably we want less process in Elixir releases. Maybe one option is to allow developers to download the zips manually and allow a local path to be given to the installer?

So for example, when selecting the Elixir version, we could have a "Choose from disk" option. When you click it, we say:

> In case this installer cannot download Elixir over the network, you may also give the path to an Elixir release in your file system. Go to https://github.com/elixir-lang/elixir/releases and download Precompile.zip for the desired version to your machine and select it on the input below:
>
> [...........................] Find Elixir release

Is this an OK experience? What do you think?

**Comment by chyndman** [comment] 2016-06-03 18:34
@steflef @BrandenSchwartz see [v1.11](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v1.11) of the installer which should at least provide a friendlier error message in your circumstances.

@josevalim there are a couple issues with this.  First, I would need to implement some way to validate the contents of Precompiled.zip so the installer doesn't install any arbitrary ZIP file on to the system.  Second, the installer doesn't provide much utility to the user in that scenario anyway; they could just extract the ZIP file and add Path entries themselves at that point, since that's all the installer does.

One solution I've thought of is to provide an option in the web installer to save the compiled offline installer to a location chosen by the user rather than running it directly.  I'm thinking of implementing it as a command line parameter (as opposed to a checkbox in the UI, so that the experience doesn't get too noisy), and then we can add documentation to the website.

**Comment by josevalim** [comment] 2016-06-03 19:13
> One solution I've thought of is to provide an option in the web installer to save the compiled offline installer to a location chosen by the user rather than running it directly.

That sounds like a great option too, definitely!

**Comment by chyndman** [comment] 2016-06-09 17:24
I've released [v2.0](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v2.0) of the installer which supports creating offline installers.  See the [readme](https://github.com/elixir-lang/elixir-windows-setup#offline-installation) on how to do so.  Please let me know if the process is unclear.

**Comment by josevalim** [comment] 2016-06-09 22:22
This is fantastic work, thank you @chyndman! :D

**Comment by hdpinto** [comment] 2017-03-27 17:55
I might have some useful information regarding this issue. I was getting the exact same error message while behind a corporate VPN that requires authentication, but when I tried to run the executable outside the VPN, the install proceeded as normal.

Hope this helps in tracking down the issue, and this is a problem all online installers have from my experience (they're just more verbose about _why_ the install failed).
