### ISSUE TITLE
Cannot compile from source on macOS catalina with erlang 22

### ISSUE THREAD

**Issue by blisssan** [elixir-lang/elixir#10026] opened 2020-05-09 13:26 UTC
### Environment
* Elixir & Erlang/OTP versions (elixir --version): Erlang OTP 22
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
elixir -v terminated when installed using brew install elixir
and iex threw an error saying recompile with OTP 21.
 
* Operating system: macOS catalina

### Current behavior
This is a fresh install after brew install elixir was not working. Decided to do a compile from source, following the docs.

>  $ git clone https://github.com/elixir-lang/elixir.git
  $ cd elixir
  $ make clean test

But the same

> ==> unicode (compile)
Compiling lib/elixir/unicode/unicode.ex (it's taking more than 15s)
==> elixir (compile)
Generated elixir app
==> eex (compile)
==> mix (compile)
Generated mix app
==> ex_unit (compile)
Generated ex_unit app
==> logger (compile)
Generated logger app
Generated eex app
==> iex (compile)
Generated iex app
==> elixir (eunit)
undefined
=ERROR REPORT==== 9-May-2020::18:51:14.499853 ===
beam/beam_load.c(1878): Error loading module atom_test:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)
*** test module not found ***
**atom_test
=======================================================
=ERROR REPORT==== 9-May-2020::18:51:14.499876 ===
Loading of /Volumes/Wizard/Library/elixir/lib/elixir/test/ebin/atom_test.beam failed: badfile
  Failed: 0.  Skipped: 0.  Passed: 0.
 One or more tests were cancelled.
  make: *** [test_erlang] Error 1

### Expected behavior

Expected a successful build.

**Comment by josevalim** [comment] 2020-05-09 14:09
There is definitely something suspicious going wrong. Do you perhaps have two Erlang installed in your system? Then perhaps one is being picked over the other? If you have two, then we need to understand why different ones are being picked.

**Comment by blisssan** [comment] 2020-05-09 14:44
@josevalim Hey, I initially suspected that. I ran 

> brew uninstall erlang 

and tried running erl, it threw erl command not found as expected. After posting this issue. I again installed erlang OTP 21. with **_brew install erlang@21_** and then ran **_make clean test_**. It compiled successfully. Here is the output of elixir -v

> Erlang/OTP 21 [erts-10.3.5.11] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.11.0-dev (181c38f) (compiled with Erlang/OTP 21)

**Comment by josevalim** [comment] 2020-05-09 14:55
This is weird indeed. 

Oh, what does `which erl` and `which erlc` return? Compiling Erlang and running Erlang are two different commands, so maybe that's where the conflict comes from?

**Comment by blisssan** [comment] 2020-05-09 16:15
Honestly I forgot to check **which erlc** before installing otp 21. 
but after installing 21, which erl is

> /usr/local/opt/erlang@21/bin/erl

which elrc

> /usr/local/opt/erlang@21/bin/erlc

brew didnot symlink erlang@21 so i had to export path manually

**Comment by josevalim** [comment] 2020-05-09 16:46
Yes, right now everything is in place and it is probably best if you keep it like this instead of trying to reproduce the broken state. :) I will leave this open for a week or two to see if you or anyone else can reproduce it once more. Thanks!

**Comment by josevalim** [comment] 2020-05-18 08:08
I will close this one for now, since it seems to be an installation issue but not Elixir issue. If anyone runs into this, they are welcome to open up a new issue or drop a comment on this one!

**Closed by josevalim** 2020-05-18 08:08 UTC
