### ISSUE TITLE
Enum.to_list

### ISSUE THREAD

**Issue by dzc944262316** [elixir-lang/elixir#6871] opened 2017-10-11 06:24 UTC
```
iex(7)> Enum.to_list(35..44)
'#$%&\'()*+,'
```

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.2

* Operating system: 
Ubuntu 16.04

**Comment by sger** [comment] 2017-10-11 06:57
same thing on macOS

```
Erlang/OTP 20 [erts-9.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Enum.to_list(35..44)
'#$%&\'()*+,'
```

**Comment by josevalim** [comment] 2017-10-11 07:12
When you don't know what a result is, put an `i` before it:

    iex>i Enum.to_list(31..44)

and it will explain the data structure. :)

**Comment by josevalim** [comment] 2017-10-11 07:12
Closing as it is working as intended and you are getting a charlist.

**Closed by josevalim** 2017-10-11 07:12 UTC

**Comment by OvermindDL1** [comment] 2017-10-11 15:55
We need a github bot (perhaps made in elixir) that looks for keywords and posts some FAQ entries as just-in-case helpers.  ^.^
