### ISSUE TITLE
Mix compile always recompile all Elixir files

### ISSUE THREAD

**Issue by mremond** [elixir-lang/elixir#3658] opened 2015-09-02 16:15 UTC
I am using mix to build an Erlang application (ejabberd), that contains Elixir code. Each time I change an Erlang module, all Elixir code is rebuild. This also this to confuse exrm, which in turn reload all Elixir module on platform upgrade.

The mix file is available here: https://github.com/processone/ejabberd/blob/master/mix.exs

Am I missing something ?

**Comment by josevalim** [comment] 2015-09-02 16:50
That's how it works right now because the erlang code can affect how the elixir code is compiled. I don't know though why exrm is marking the code on platform upgrade. /cc @bitwalker?

We could change the mechanism to not compile the Elixir code on Erlang change but users will need to be wary that if they are relying on the Erlang code for meta-programming, they need to use `mix compile --force`. We could make this change but I am not convinced yet.

I would rather investigate why exrm is upgrading modules that were not supposed to have changed.

**Comment by ericmj** [comment] 2015-09-02 21:59
You can run `mix compile.erlang` to only compile erlang code.

**Comment by mremond** [comment] 2015-09-03 10:22
@josevalim @ericmj Thanks.
It think the issue is not really the compile time but the fact that it trigger a module reload during release management deployment that are not necessary. I will investigate with @bitwalker why this is the case but I suspect this is due to timestamp change of the resulting beam.

**Comment by josevalim** [comment] 2015-09-03 10:40
@mremond shouldn't release be built based on the @vsn attribute instead of the timestamp?

**Comment by mremond** [comment] 2015-09-03 10:57
@josevalim It seems comparison / check for changed file is more complex than timestamp or vsn check: https://github.com/erlang/otp/blob/maint/lib/stdlib/src/beam_lib.erl#L337

**Comment by mremond** [comment] 2015-09-03 11:14
So, I do not think this is a bug in Elixir / Mix. I confirm that @vsn and md5 is the same for the newly generated file, but some are still added in relup file with brutal reload instruction. I will investigate deeper and report.

**Comment by josevalim** [comment] 2015-10-14 23:33
Any news here? :)

**Comment by josevalim** [comment] 2015-11-25 12:52
I am closing this one as I can't reproduce it and there are more news. :) Please open a new issue if there is new input. :D Thank you!

**Closed by josevalim** 2015-11-25 12:52 UTC
Labels: App:Elixir, Note:Needs more info
