### ISSUE TITLE
Issue with "clauses with the same name and arity should be grouped together"

### ISSUE THREAD

**Issue by speeddragon** [elixir-lang/elixir#8261] opened 2018-10-09 17:47 UTC
I've been developing an application in Elixir since past year, and until recently I've used version 1.6 without any issues. Today I've changed to another computer and started using the 1.7.3 version and I'm having this annoying error with the clauses with the same name and arity not being grouped together when they are.

The strange thing is that I have similar code on other parts of this code base, and that don't give any warning. 

I've notice that there was a [PR](https://github.com/elixir-lang/elixir/pull/7630/files) that changed this code, might be related to that ? Not sure if I can replicate this in a demo repo.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 20)

* Operating system: 
Ubuntu 17.04

### Current behavior

```
warning: clauses with the same name and arity (number of arguments) should be grouped together, "def search_all_by/2" was previously defined (lib/ketchup/restaurant/restaurant_helper.ex:315)
  lib/ketchup/restaurant/restaurant_helper.ex:324
```

Code Sample:

```
...
  defp search_all() do
  ...
  end

  @doc """
  Search by name
  """
  def search_all_by(nil, title_start_with) do
    search_all()
    |> where([r], ilike(r.name, ^title_start_with))
    |> Repo.all()
  end

  @doc """
  Search by name on a language item translated
  """
  def search_all_by(language, title_start_with) do
    search_all()
    |> where([r], ilike(translated(Restaurant, r.name, language), ^title_start_with))
    |> Repo.all()
  end

  def search_all_names_by(language, title_start_with) do
  ...
  end
...
```
### Expected behavior

It shouldn't give a warning.

**Comment by josevalim** [comment] 2018-10-09 17:50
Can you please provide a full snippet that reproduces the error? Because the snippet above does not reproduce it as the module below compiles without warnings:

```elixir
defmodule Foo do
  def search_all() do
    :ok
  end

  @doc """
  Search by name
  """
  def search_all_by(nil, _title_start_with) do
    :bar
  end

  @doc """
  Search by name on a language item translated
  """
  def search_all_by(_language, _title_start_with) do
    :baz
  end

  def search_all_names_by(_language, _title_start_with) do
    :bat
  end
end
```

**Comment by speeddragon** [comment] 2018-10-09 18:12
Some how the following line is causing this:

```
translated(Restaurant, r.name, language)
```
I will continue my investigation later.

**Comment by josevalim** [comment] 2018-10-09 18:15
We would need to know how `translated` is implemented. Maybe it is trying to define modules and functions behind the scenes, causing the warning.

**Comment by josevalim** [comment] 2018-10-09 18:30
Thanks, that seems ok. We will be waiting for a mechanism to reproduce the issue then.

**Comment by speeddragon** [comment] 2018-10-09 18:33
This should replicate the issue, https://github.com/speeddragon/elixir_arity.

```
mix compile
Compiling 2 files (.ex)
warning: clauses with the same name and arity (number of arguments) should be grouped together, "def search_all_by/2" was previously defined (lib/issue.ex:30)
  lib/issue.ex:40
```

**Comment by josevalim** [comment] 2018-10-09 18:51
Beautiful, fixed in master and backported to v1.7. Note that we have also sent a PR to the trans project to improve there (they are not doing anything wrong but the fix we sent is semantically correct and also fix it). Once we do a new release we should be good to go!

**Comment by josevalim** [comment] 2018-10-09 18:51
Btw, thanks for the app that reproduces it. It makes our job much much much easier!

**Closed** 2018-10-09 18:51 UTC
Labels: Note:Needs more info

**Comment by speeddragon** [comment] 2018-10-09 18:54
Thanks for the fix, this issue got me for a couple of hours.
