### ISSUE TITLE
NIF loading errors during mix compile after mix clean

### ISSUE THREAD

**Issue by tsutsu** [elixir-lang/elixir#10080] opened 2020-06-04 18:37 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

  * Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

  * Elixir 1.10.3 (compiled with Erlang/OTP 23)

* Operating system: macOS 10.15.5

### Current behavior

Clean builds (i.e. starting with no `_build` or `deps` folder, with `mix compile` run right after `mix deps.get`) work fine, and produce no errors. Any NIF-embedding dependencies compile fine and load silently.

But after a `mix clean` on such a built project, another invocation of `mix compile` will produce errors like the following, during the compile (note that these are the compilations of umbrella-apps in an umbrella project):

```
==> castle
Compiling 15 files (.ex)
warning: :crypto.hash/2 is undefined (module :crypto is not available or is yet to be defined)
  lib/castle/hashable.ex:6: CAStle.Hashable.BitString.hash/1


17:59:01.811 [error] Process #PID<0.694.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    (crypto 4.7) crypto.erl:2579: :crypto.on_load/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5

17:59:01.808 [warn]  The on_load function for module crypto returned:
{:badarg, [{:erlang, :load_nif, [:erlang, :apply], []}, {:crypto, :on_load, 0, [file: 'crypto.erl', line: 2579]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', ...]}]}
Generated castle app
```

```
==> ingestor
Compiling 110 files (.ex)

17:59:09.865 [error] Process #PID<0.2123.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    /Users/tsutsu/Work/covalent/deps/keccakf1600/src/keccakf1600_nif.erl:155: :keccakf1600_nif.init/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5

17:59:09.871 [warn]  The on_load function for module keccakf1600_nif returned:
{:badarg, [{:erlang, :load_nif, [:erlang, :apply], []}, {:keccakf1600_nif, :init, 0, [file: '/Users/tsutsu/Work/covalent/deps/keccakf1600/src/keccakf1600_nif.erl', line: 155]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', ...]}]}


17:59:09.887 [error] Process #PID<0.2126.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    /Users/tsutsu/Work/covalent/deps/keccakf1600/src/keccakf1600_nif.erl:155: :keccakf1600_nif.init/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5

17:59:09.887 [error] Process #PID<0.2128.0> raised an exception
** (ArgumentError) argument error
    :erlang.load_nif(:erlang, :apply)
    /Users/tsutsu/Work/covalent/deps/keccakf1600/src/keccakf1600_nif.erl:155: :keccakf1600_nif.init/0
    (kernel 7.0) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5
```

Additionally, after these errors, the resulting NIF modules will be seemingly unavailable, causing the compilation of whatever code was relying on them to stall, producing a set of messages like these:

```
Compiling lib/ingestor/pg_dumper/event_source/originprotocol.ex (it's taking more than 15s)
Compiling lib/ingestor/pg_dumper/event_source/foam.ex (it's taking more than 15s)
Compiling lib/ingestor/pg_dumper/event_source/0x.ex (it's taking more than 15s)
```

...followed by no further output, even given minutes of waiting.

This doesn't seem to be a problem with the NIF libraries themselves; they build (and rebuild) fine in isolation, when their upstream projects are separately cloned. As well, as can be observed above, even OTP-internal NIFs, like the one associated with the `crypto` module, are affected. (Whether `crypto` is included as an `extra_applications` dep of the relevant umbrella-app doesn't seem to matter; the errors happen either way.)

Seemingly, the wrong arguments (maybe an AST fragment?) are being passed to `erlang:load_nif/2` when a NIF module becomes loaded during compilation (through e.g. a call to the module made in module-body code, or in a macro outside of a quote, or by invoking `Code.ensure_loaded` on the NIF module to check for its presence.)

My code might be a bit unusual, in that it relies on calling into these NIF modules at compile time. In the above, both the OTP `crypto` module, and the `keccakf1600` library, are being used to hash input values at compile time, to make the hashes available as compile-time constants for the generation of fast pattern-matching code. (I could embed the pre-calculated hashes in the module source code, but it makes more sense to me for the source code to contain the "source" of the hash, as well.)

I'm not sure whether using heavy functionality like NIFs at compile time is an anti-pattern or not, but I *am* sure that this used to work. I'm not clear on whether it was the upgrade to Erlang 23 or some regression in a newer version of Elixir that is to blame. I haven't touched this codebase since early January, so the regression could have been caused by any change in either Erlang or Elixir since that time.

I've tried to create a reproducer for this problem, but on its own, a module like the following *does not* trigger the problem:

```elixir
defmodule Baz do
  a = :crypto.hash(:sha256, "baz")
  @static a

  def value do
    @static
  end
end
```

If needed, I can try to instead pare our large codebase down to a minimum reproducer.

### Expected behavior

I wouldn't expect these errors, nor would I expect a compiler stall.

I would expect to be able to use NIFs at compile-time, but maybe that's just me. :smile:

**Comment by josevalim** [comment] 2020-06-04 18:51
Hi @tsutsu! From your description, it doesn't look like you are doing anything unnatural. So there is something fishy going on here.

The weirdest thing is that it is calling :erlang/:apply on `load_nif`. We would definitely need a way to reproduce the error so we can take a deeper look at it.

**Comment by tsutsu** [comment] 2020-06-04 20:26
[This repo](https://github.com/tsutsu/castle) seems to trigger the behavior, but only inconsistently. For me, it happens about half the time. It might come down to order of parallel compilation. Just keep running `mix clean; mix compile` and it'll happen.

It seems codebase size / number of compilation units has some effect here; when I trim away clearly irrelevant files, at some point I'm left with code that will never trigger the error. Thus, I've left in some of these irrelevant files, as they help make the error appear more often.

(Also, I apologize for forcing you to compile the huge `rocksdb` NIF here. The reproduction is very "fragile"—I'm afraid of trying to replace it with a different NIF dependency.)

One interesting thing is that there are no compile-time calls to the NIF module in this code. What there *is*, is a `@behaviour` annotation on the module that calls into the NIF, with functions that call on NIF-module functions being marked as `@impl`. Removing the annotations seemingly make the problem unable to be reproduced.

**Comment by lukaszsamson** [comment] 2020-06-04 21:13
Lately I've been working a lot with erlzmq NIF and since I switched to otp 23 (or macos 10.15.5) I see it sometimes fails to load. At first I thought I made some errors in the NIF implementation. Then other NIFs like appsignal and comeonin that used to  be rock solid also started to fail.

**Comment by dmorneau** [comment] 2020-06-05 07:19
See: https://github.com/erlang/otp/pull/2649

**Comment by josevalim** [comment] 2020-06-05 07:25
Thank you @dmorneau for the reference!

**Comment by josevalim** [comment] 2020-06-11 07:29
This has been merged and fixed in Erlang/OTP. So watch out for a new Erlang/OTP  release. Thanks!

**Closed by josevalim** 2020-06-11 07:29 UTC
Labels: Note:Erlang bug
