### ISSUE TITLE
Elixir (1.5.1) recompiles the deps code everytime after I edited my code

### ISSUE THREAD

**Issue by neroishero** [elixir-lang/elixir#6428] opened 2017-08-03 03:29 UTC
### Environment

* Elixir & Erlang versions (elixir 1.5.1)， opt 20 
* win7 64

### Current behavior

 step:

1. "iex -S mix debug_client"
2. change some code of server.ex
3. try "iex -S mix debug_client" again,
then you can sell the console recompile the chronos app, logger_file_backend app,  decimal app

Here is the bug test repository: https://github.com/neroishero/elixir_test

**Comment by josevalim** [comment] 2017-08-03 06:28
I could not reproduce it locally. @overminddl1 @OnorioCatenacci could one of you please give it a try on Windows? thank you!

**Comment by OnorioCatenacci** [comment] 2017-08-03 11:53
I'll see if I can get to it. I don't have Win 7; have Win 10 but I'll see if I can repro it on that platform.

**Comment by OnorioCatenacci** [comment] 2017-08-03 12:18
I checked this on Windows 10.  Cannot reproduce the behavior.  Couple of thoughts for @neroishero:

How do you exit iex (step 1)?  I do a System.halt() in iex to insure everything is shut down.  

What sort of change do you make in server.ex?  Can you specifically tell us what kind of change you make?  I just added a comment which did trigger recompilation but not of every file.  

Are you sure that everything compiled correctly for step 1?  If something didn't get compiled in step 1 that would cause the behavior you're seeing.

As I say, I know this is Win 10 not Win 7 and that may make a difference so we need someone with Win 7 to try to reproduce this but it'd also help if you could provide those details I spelled out.

**Comment by OnorioCatenacci** [comment] 2017-08-03 12:21
Just to double check, I also tried modifying server.ex without shutting down iex.  I then did a recompile inside iex.  Same behavior--it only recompiled the proper files.

**Comment by OvermindDL1** [comment] 2017-08-03 14:27
> I checked this on Windows 10. Cannot reproduce the behavior. Couple of thoughts for @neroishero:

Similar here, which again makes me think it is something system specific like a file syncher or antivirus or so.

**Comment by vans163** [comment] 2017-08-04 08:13
Would it be possible to add a compiler option to mix that would make it hash every file instead of checking the utime + file_size?

**Comment by robi-wan** [comment] 2017-08-09 09:08
I could not reproduce it under Windows 7 Pro 64bit.
Between the two `iex` sessions I edited this line: https://github.com/neroishero/elixir_test/blob/master/lib/service/server.ex#L75 (I increased the time).
I ended the first `iex` session with `CTRL+C`.
Session log is [here](https://gist.github.com/robi-wan/305e464f38243e6d5d4c882a7b749752).

**Comment by vans163** [comment] 2017-08-09 12:26
@robi-wan its likely neroishero has an antivirus or some filesystem that messes with the files utimes. Hence why reproducing it outside their environment is unlikely.

**Comment by josevalim** [comment] 2017-09-03 14:51
Since multiple users have reported they could not reproduce the issue, I will go ahead and close this issue. Thank you for reporting and please follow up on the suggestions mentioned here. Thanks everyone who investigated and followed up. :+1:

**Closed by josevalim** 2017-09-03 14:51 UTC
Labels: App:Mix, Kind:Bug, Note:Needs more info, Note:Windows

**Comment by vans163** [comment] 2017-09-03 17:09
Using utimes is clearly problematic for deciding whether to recompile deps, its funny how no one wants to admit this.

**Comment by josevalim** [comment] 2017-09-03 17:31
At the same time mtimes+size is by far the fastest approach to this. I believe someone was working on file hashing and we are definitely open to such contributions. But even if added hashing to Mix, I don't think it would replace mtimes+size as the default choice for projects.

**Comment by vans163** [comment] 2017-09-03 17:40
It might be the fastest but whats faster 1ms ping or 2ms ping, at this level of speed it really does not matter.  The only problem I can see is if your project has thousands of source files (most users would have under 100),  even then on an SSD it should be quite speedy.  HDD's might/would suffer.

**Comment by josevalim** [comment] 2017-09-03 17:56
Sure, if we can validate the assumption that the slowdown is not significant, then we can consider completely moving away from mtimes. But until then, someone needs to provide the hash-based implementation and perform the relevant benchmarks.
