### ISSUE TITLE
Cannot fetch dependencies with mix deps.get, seeing :failed_connect error, :honor_cipher_order

### ISSUE THREAD

**Issue by dopatraman** [elixir-lang/elixir#9374] opened 2019-10-01 06:58 UTC
### Environment
* Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 21)

* Ubuntu 16.04

### Current behavior
When I run `mix deps.get` I get the following error for each dependency:
```
Failed to fetch record for 'hexpm/telemetry' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/plug_cowboy' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/plug' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/ranch' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
```
and so on. Is Hex down? Why can't I fetch anything?

Something that looks peculiar is this error:
```
* Getting telemetry (Hex package)
** (FunctionClauseError) no function clause matching in Regex.safe_run/3    
    
    The following arguments were given to Regex.safe_run/3:
    
        # 1
        ~r/\/\/([^:]*):[^@]+@/
    
        # 2
        "https://repo.hex.pm/tarballs/telemetry-0.4.0.tar"
    
        # 3
        [{:capture, :all, :index}, :global]
    
    Attempted function clauses (showing 1 out of 1):
    
        defp safe_run(%Regex{re_pattern: compiled, source: source, re_version: version}, string, options)
    
    (elixir) lib/regex.ex:463: Regex.safe_run/3
    (elixir) lib/regex.ex:663: Regex.do_replace/4
    (hex) lib/hex/scm.ex:103: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:163: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:201: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
```
This looks related to the hex failure though (as it cannot fetch the telemetry library). What is going on with Hex?

I've tried uninstalling and reinstalling Erlang and Elixir, hasn't worked.

**Comment by fertapric** [comment] 2019-10-01 07:23
Related: https://github.com/hexpm/hex/commit/f34518e143a59118589d65494ab4dc5181e782db

**Comment by dopatraman** [comment] 2019-10-01 07:25
@fertapric what do you think is causing the problem?

**Comment by wojtekmach** [comment] 2019-10-01 08:18
@dopatraman update your Hex with `mix local.hex --force` and you should be good to go.

We've fixed it on Elixir master by requiring newer Hex versions: https://github.com/elixir-lang/elixir/pull/9357.

The issue is in OTP 22.1 passing this option `honor_cipher_order` started erroring. This also broke hackney: https://github.com/benoitc/hackney/issues/591.

**Comment by josevalim** [comment] 2019-10-01 10:23
Closing in favor of the Hex one.

**Closed by josevalim** 2019-10-01 10:23 UTC

**Comment by dopatraman** [comment] 2019-10-01 16:56
Rebuilt Elixir from source, that seems to have fixed the problem 🤔
