### ISSUE TITLE
Mix fails on IPv6-only host

### ISSUE THREAD

**Issue by PrestonL** [elixir-lang/elixir#13902] opened 2024-10-13 22:00 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Linux 6.1.0-26-amd64 #- Debian 6.1.112-1 (2024-09-30) x86_64

### Current behavior

Attempting to run "mix phx.server" on an IPv6 only host (With DNS64/NAT64) will cause the application to fail.  It appears to only try IPv4 addresses when IPv6 is available with no IPv4 default route installed.  curl/wget and other utilities will work even on IPv4-only hosts on IPv6-only hosts with NAT64/DNS64 enabled.  registry.npmjs.org is dual-stacked and will also fail.

```
[info] Running MyProjectWeb.Endpoint with Bandit 1.5.7 at 127.0.0.1:4000 (http)
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64
[info] Access MyProjectWeb.Endpoint at http://localhost:4000
[debug] Downloading esbuild from https://registry.npmjs.org/@esbuild/linux-x64/0.17.11
[error] Task #PID<0.5893.0> started from Esbuild.Supervisor terminating
** (RuntimeError) couldn't fetch https://registry.npmjs.org/@esbuild/linux-x64/0.17.11: {:error, {:failed_connect, [{:to_address, {~c"registry.npmjs.org", 443}}, {:inet, [:inet], :enetunreach}]}}
```

### Expected behavior

mix should utilize happy eyeballs and try IPv6 first and then revert to IPv4-only.

**Comment by josevalim** [comment] 2024-10-13 22:25
Hi @PrestonL. This is not an issue with Mix, Mix is only the entry point, but most likely with esbuild. Although installing esbuild works fine on my machine, so I wonder if there is something else going on?

**Comment by PrestonL** [comment] 2024-10-13 23:15
It doesn't just fail downloading esbuild, it fails downloading other dependencies too when running mix:

[info] Running MyProjectWeb.Endpoint with Bandit 1.5.7 at 127.0.0.1:4000 (http)
[info] Access MyProjectWeb.Endpoint at http://localhost:4000
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64
[error] Task #PID<0.929.0> started from MyProjectWeb.Endpoint terminating
** (stop) exited in: GenServer.call(Esbuild.Supervisor, {:start_child, %{id: Esbuild.Installer, restart: :transient, start: {Task, :start_link, [#Function<0.86449943/0 in Esbuild.install>]}}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.17.3) lib/gen_server.ex:1121: GenServer.call/3
    (esbuild 0.8.1) lib/esbuild.ex:188: Esbuild.start_unique_install_worker/0
    (esbuild 0.8.1) lib/esbuild.ex:210: Esbuild.install_and_run/2
    (phoenix 1.7.14) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.17.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["esbuild", {Esbuild, :install_and_run, [:my_project, ["--sourcemap=inline", "--watch"]]}]
[error] Task #PID<0.930.0> started from MyProjectWeb.Endpoint terminating
** (RuntimeError) Couldn't fetch https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64: {:error, {:failed_connect, [{:to_address, {~c"github.com", 443}}, {:inet, [:inet], :enetunreach}]}}

This typically means we cannot reach the source or you are behind a proxy.
You can try again later and, if that does not work, you might:

  1. If behind a proxy, ensure your proxy is configured and that
     your certificates are set via the cacerts_path configuration

  2. Manually download the executable from the URL above and
     place it inside "_build/tailwind-linux-x64"

  3. Install and use Tailwind from npmJS. See our module documentation
     to learn more: https://hexdocs.pm/tailwind

    (tailwind 0.2.3) lib/tailwind.ex:303: Tailwind.fetch_body!/1
    (tailwind 0.2.3) lib/tailwind.ex:224: Tailwind.install/1
    (tailwind 0.2.3) lib/tailwind.ex:205: Tailwind.install_and_run/2
    (phoenix 1.7.14) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.17.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["tailwind", {Tailwind, :install_and_run, [:my_project, ["--watch"]]}]
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64



wget however can retrieve the files just fine:

# wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64

--2024-10-13 18:13:51--  https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64
Resolving github.com (github.com)... 64:ff9b::8c52:7004, 140.82.112.4
Connecting to github.com (github.com)|64:ff9b::8c52:7004|:443... connected.
HTTP request sent, awaiting response... 302 Found
.....
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 64:ff9b::b9c7:6e85, 64:ff9b::b9c7:6d85, 64:ff9b::b9c7:6c85, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|64:ff9b::b9c7:6e85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42069667 (40M) [application/octet-stream]
Saving to: ‘tailwindcss-linux-x64’

tailwindcss-linux-x64        100%[=============================================>]  40.12M  27.8MB/s    in 1.4s

2024-10-13 18:13:53 (27.8 MB/s) - ‘tailwindcss-linux-x64’ saved [42069667/42069667]




So you are saying: **[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64** is output from esbuild, not mix?

**Comment by josevalim** [comment] 2024-10-14 07:26
Those come from the esbuild and tailwind packages. What is interesting is that, the thing that Mix actually does, is to download Rebar3 and (indirectly) Hex packages. Looking at Mix source, we do this:

```
      case httpc_request(request, http_options) do
        {:error, {:failed_connect, [{:to_address, _}, {inet, _, reason}]}}
        when inet in [:inet, :inet6] and
               reason in [:ehostunreach, :enetunreach, :eprotonosupport, :nxdomain] ->
          :httpc.set_options([ipfamily: fallback(inet)], :mix)
          request |> httpc_request(http_options) |> httpc_response()

        response ->
          httpc_response(response)
      end
```

And we should probably add this to esbuild/tailwind. [Here](https://github.com/phoenixframework/esbuild/blob/ac23b695dabdc88bc25c82b81acc596b79e3d55b/lib/esbuild/npm_registry.ex#L94) and [here](https://github.com/phoenixframework/tailwind/blob/f729dc32582c697deab1c9d6aa71993256a60da7/lib/tailwind.ex#L304).

**Comment by josevalim** [comment] 2024-10-16 18:18
Closing as the issue is upstream, but feel free to ask if you need help.

**Closed** 2024-10-16 18:18 UTC
