### ISSUE TITLE
Improve unhandled operator

### ISSUE THREAD

**Issue by yordis** [elixir-lang/elixir#7454] opened 2018-03-15 07:44 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  Elixir 1.7.0-dev (d8dbc6f) (compiled with OTP 20)
* Operating system: MacOS

### Current behavior

```elixir
  def get_account_type(account) do
    case do
      account.patient_id != nil -> "patient"
      _ -> "unknown"
    end
  end
```

```
== Compilation error in file lib/app_name/schema/account.ex ==
** (CompileError) lib/app_name/schema/account.ex:47: unhandled operator ->
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

```

### Expected behavior

To be more descriptive about this error.

I wasn't sure what I was doing wrong, thanks to @bitwalker  that explains me 

> case clauses and function heads are both pattern matches, so you can really generalize the rule to any pattern match, guards are an extension of pattern matching really, so the same rules apply

but I wouldn't figure out based on the errror.

**Comment by josevalim** [comment] 2018-03-15 07:49
Thanks. Closing as duplicate of #7440.

**Closed by josevalim** 2018-03-15 07:49 UTC
