### ISSUE TITLE
New logger fails when `handle_sasl_reports` and `metadata: :all`

### ISSUE THREAD

**Issue by brainlid** [elixir-lang/elixir#9830] opened 2020-02-18 22:41 UTC
### Environment

* Elixir 1.10.1 (compiled with Erlang/OTP 22)
* Operating system: Ubuntu LTS

### Current behavior

Set `config/prod.exs` to something similar:

```elixir
use Mix.Config

# Override for improved log output.
config :logger,
  backends: [:console],
  truncate: :infinity,
  compile_time_purge_matching: [
    [level_lower_than: :info]
  ],
  handle_otp_reports: true,
  handle_sasl_reports: true

config :logger, :console,
  format: "\n$time $metadata[$level] $levelpad$message\n",
  metadata: :all
```
Note that sasl logging is on and metadata is `:all`.

Then start the application:

```
MIX_ENV=prod mix phx.server
```

It blows up. The sasl reports include metadata that is a map, which is not handled or expected.

```
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{tag: :info_report, type: :progress} of type Map. This protocol is implemented for the following type(s): ...
        (elixir 1.10.1) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir 1.10.1) lib/string/chars.ex:22: String.Chars.to_string/1
        (logger 1.10.1) lib/logger/formatter.ex:180: Logger.Formatter.metadata/1
        (logger 1.10.1) lib/logger/formatter.ex:180: Logger.Formatter.metadata/1
        (logger 1.10.1) lib/logger/formatter.ex:152: anonymous fn/6 in Logger.Formatter.format/5
        (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (logger 1.10.1) lib/logger/formatter.ex:151: Logger.Formatter.format/5
        (logger 1.10.1) lib/logger/backends/console.ex:186: Logger.Backends.Console.format_event/5
```

### Expected behavior

Not blow up. Perhaps ignore the data or convert it to a string. I don't even care about that specific message. An example of the unhandled data is `:logger_formatter` and the value is `%{title: 'PROGRESS REPORT'}`

### Why do I have `:all`?

I have a custom logger to format to JSON. I let all the metadata through and use a blacklist to block the ones I don't want. With the change to 1.10, this changed for me. Thought I should still report the issue as if the two options are enabled it breaks.

**Comment by josevalim** [comment] 2020-02-18 22:55
Duplicate of #9814. :)

**Comment by josevalim** [comment] 2020-02-18 22:55
In any case, Thanks for the report!

**Closed by josevalim** 2020-02-18 22:55 UTC
