### ISSUE TITLE
Supervisor.init callback is incompatible with Supervisor.init/2

### ISSUE THREAD

**Issue by serokellcao** [elixir-lang/elixir#10987] opened 2021-05-17 22:12 UTC
# Environment

```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
```

OS: Ubuntu LTS (WSL)

Editor: VSCode

Language server: ElixirLS

# Current behaviour

```
  def init(_) do
    Supervisor.init([Minimal.Example], strategy: :one_for_one)
  end
```

results in the following dialyzer error, as reported by ElixirLS:

```
The @spec return type does not match the expected return type
for init/1 callback in Supervisor behaviour.
Actual:
@spec init(...) :: {:ok, {%{:intensity => _, :period => _, :strategy => _}, [any()]}}
Expected:
@spec init(...) :: 
  :ignore
  | {:ok,
     {{:one_for_all, non_neg_integer(), pos_integer()}
     *snip*
      | %{
          :intensity => non_neg_integer(),
          :period => pos_integer(),
          :strategy => :one_for_all | :one_for_one | :rest_for_one | :simple_one_for_one
        },
      [
        {_, {atom(), atom(), :undefined | [any()]}, :permanent | :temporary | :transient,
         :brutal_kill | timeout(), :supervisor | :worker, :dynamic | [atom()]}
        | %{
            :id => _,
            *snip*
            :type => :supervisor | :worker
          }
      ]}}
```

It happens, seemingly, because dialyzer picks up [callback signature](https://github.com/elixir-lang/elixir/blob/308255bda81e7f76f9bec838cef033e8e869981b/lib/elixir/lib/supervisor.ex#L476).

# Expected behaviour

No dialyzer error is reported for valid typespecs.

**Comment by josevalim** [comment] 2021-05-17 22:19
What is your dialyzer configuration? In the example you provided, the actual and expected actually match, unless you are using underspec/overspec or simular. If you can isolate this into its own repo, even better! Thanks!

**Comment by josevalim** [comment] 2021-05-18 07:42
I could not reproduce this issue. I created a new project with `mix new foo --sup` then update lib/foo/application.ex:

```elixir
defmodule Foo.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      Foo.Supervisor
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Foo.Supervisor]
    Supervisor.start_link(children, opts)
  end
end

defmodule Foo.Supervisor do
  use Supervisor

  def start_link(_opts) do
    Supervisor.start_link(__MODULE__, :ok)
  end

  def init(:ok) do
    Supervisor.init([{Task, & &1}], strategy: :one_for_one)
  end
end
```

Then added dialyxir as a dep and ran `mix dialyzer`. I am using Elixir v1.12 and Erlang/OTP 24. Therefore, can you please fill in the issues template and provides the steps to reproduce? Thank you.

**Comment by serokellcao** [comment] 2021-05-18 18:06
Hello, Jose! Thanks for more questions.

I still didn't get around to understand how exactly `@impl true` works, but here is a file where I face a problem with typing `init`: https://git.sr.ht/~doma/do-auth/tree/d2a28de2e48dfd3c739b40633b280c4ab4814826/item/lib/do_auth/persistence.ex#L10

I haven't configured dialyzer, however the issue that I'm having is with [ElixirLS](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls), which might ship its own configuration.

But I'll trust you entirely on whether or not the types between callback and the way it's actually used are compatible and will live with this ElixirLS annoyance until I have the time to wrap my head around what exactly is going on.

**Comment by serokellcao** [comment] 2021-05-18 18:14
PS.

Apologies for not following a reasonable format for the issue and not presenting with enough details about the environment!

I probably shouldn't have made the issue straight before going to bed, but it's one of those things which if I wouldn't have done then, I would have probably done in a month or so. :)

**Comment by josevalim** [comment] 2021-05-18 20:01
I see, thanks for following up! I cannot reproduce the issue, even with the references above, so I will go ahead and close this. If you (or anyone) can reproduce it, then I will be glad to take a look!

**Closed by josevalim** 2021-05-18 20:01 UTC
Labels: Note:Needs more info
