### ISSUE TITLE
Windows web-installer "Select another release to install" not working

### ISSUE THREAD

**Issue by KeeperB5** [elixir-lang/elixir#5616] opened 2017-01-05 05:17 UTC
OS: Windows 10 64-bit

In Elixir Web-installer when selecting "Select another release to install", it still installs the latest version no matter which release is selected.

**Comment by josevalim** [comment] 2017-01-05 09:53
When did you download the installer? 

@chyndman could this be related to the fact we finally started listing the shas for [installations here](https://github.com/elixir-lang/elixir-lang.github.com/blob/master/elixir.csv)?

**Comment by KeeperB5** [comment] 2017-01-05 10:09
I downloaded the installer yesterday, shortly before the 1.4.0 release. At the time 1.3.4 was the latest release.

**Comment by josevalim** [comment] 2017-01-05 10:11
@KeeperB5 thank you for the info. Can you please try again and let me know if this time it works? Also, can you make sure you don't have another Elixir installed in your system that may be set with higher precedence than the one from the installer? I believe on Windows you can run something like `where elixir`.

**Comment by KeeperB5** [comment] 2017-01-05 10:25
The installer is supposed to remove any previous version of Elixir prior to installing the selected version, and it does. I also do not have Elixir or Erlang installed by other means than the Elixir installer.

Unfortunately now even "Install the latest stable release" option is also broken.
[Error message](https://dl.dropboxusercontent.com/u/33353202/elixir-web-installer-error.jpg)

Selecting version 1.3.4 still downloads 1.4.0 and attempts to run the 1.4.0 installer, with the above error message.

**Comment by josevalim** [comment] 2017-01-05 10:38
@KeeperB5 I see. So I believe the bug is unrelated to the sha messages. I have added the sha's back, can you please check if installing at least v1.4.0 now works again?

**Comment by KeeperB5** [comment] 2017-01-05 10:40
Latest stable option works again.

**Comment by KeeperB5** [comment] 2017-01-06 05:23
I only now realized Windows installer has its own repo. Oops, sorry.

**Comment by chyndman** [comment] 2017-01-06 07:25
@KeeperB5 no problem, I've created a new thread at elixir-lang/elixir-windows-setup#8 to pick up the discussion. I haven't yet reproduced this issue myself but I want to revisit the code I haven't touched in months anyway, which might shed some light.

@josevalim the CSV changes should not have caused this issue.

**Comment by josevalim** [comment] 2017-01-06 08:14
@chyndman good to know, thanks for looking into this! I will close this since we have moved the issue to the appropriate tracker. :)

**Closed by josevalim** 2017-01-06 08:14 UTC
Labels: App:Elixir, Note:Windows
