### ISSUE TITLE
`mix test --cover` bug when using `cond` and binary pattern matching

### ISSUE THREAD

**Issue by dersmon** [elixir-lang/elixir#13945] opened 2024-11-01 08:44 UTC
### Elixir and Erlang/OTP versions

```
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
```

### Operating system

Operating System: Manjaro Linux, Kernel: Linux 6.6.54-2-MANJARO, Architecture: x86-64

### Current behavior

While trying to improve my code coverage, I ran into this bug (?). 

I trimmed down my initial test to the bare minimum, I can reproduce it with the following module:

```elixir
defmodule Example do
  def test("a_" <> _rest = a_prefix) do
    IO.puts("a_prefix")
    IO.puts(a_prefix)
  end

  def test(other) do
    cond do
      true ->
        IO.puts("other")
        IO.puts(other)
    end
  end
end
```

My test:
```elixir
defmodule ExampleTest do
  use ExUnit.Case

  test "full coverage" do
    Example.test("a_something")
    Example.test("something_else")
  end
end
```

My log output for `mix test --cover`:

```
Running ExUnit with seed: 49838, max_cases: 16

a_prefix
a_something
other
something_else
.
Finished in 0.1 seconds (0.00s async, 0.1s sync)
1 test, 0 failures

Generating cover results ...

(...)
    33.33% | Example
(...)
```

The generated HTML:
[Elixir.Example.html.zip](https://github.com/user-attachments/files/17597804/Elixir.Example.html.zip)

### Expected behavior

```
    100.00% | Example
```

**Comment by josevalim** [comment] 2024-11-02 10:35
I was able to isolate it as a duplicate of #13863. :) It should be fixed on OTP 27.2.

**Closed by josevalim** 2024-11-02 10:35 UTC
