### ISSUE TITLE
Incorrect dependency warnings with new application boundary checks

### ISSUE THREAD

**Issue by dmarkow** [elixir-lang/elixir#10422] opened 2020-10-12 17:20 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.0 (compiled with Erlang/OTP 23)
* Operating system: macOS 10.15.7

### Current behavior

New empty app (using `mix new`) with just two dependencies: `phoenix` and `phoenix_swoosh`. The `phoenix_swoosh` library [correctly lists `phoenix` as one of its dependencies](https://github.com/swoosh/phoenix_swoosh/blob/master/mix.exs#L35)

When I `mix compile` my app, I get this in the output, even though both my own app and `phoenix_swoosh` list `phoenix` as a dependency:

```
==> phoenix_swoosh
Compiling 1 file (.ex)
warning: Phoenix.View.render_to_string/3 defined in application :phoenix is used by the current application but the current application does not directly depend on :phoenix. To fix this, you must do one of:

  1. If :phoenix is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :phoenix is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :phoenix, you may optionally skip this warning by adding [xref: [exclude: Phoenix.View] to your "def project" in mix.exs

  lib/phoenix_swoosh.ex:159: Phoenix.Swoosh.do_render_body/4

Generated phoenix_swoosh app
```

[Sample app here](https://github.com/dmarkow/elixir-dependency-issue/)

### Expected behavior

My app should compile without any warnings.

**Comment by wojtekmach** [comment] 2020-10-12 18:04
The problem is `phoenix_swoosh` defines `:applications` list that does not include :phoenix. https://github.com/swoosh/phoenix_swoosh/blob/3b9f4e8877321093dc703f9c45fc81bab1a469b9/mix.exs#L30. The best fix is to simply remove `:applications`, so that the application list is inferred from deps. I'm sure they'd appreciate a PR. :-)

**Comment by josevalim** [comment] 2020-10-12 18:44
Fixed in https://github.com/swoosh/phoenix_swoosh/pull/152 :)

**Closed by josevalim** 2020-10-12 18:44 UTC

**Comment by dmarkow** [comment] 2020-10-12 18:47
Ah, ok... that makes sense. Now I know what PRs to send on about a dozen other libraries in my app that have the same issue. Thank you, you all are amazing.
