### ISSUE TITLE
Weird formatting when case is combined with nested patterns

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#10360] opened 2020-09-21 17:11 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
```
* Operating system: macOS

### Current behavior

Given the following snipet:
```elixir
a = {b, c} = case d do e -> e end
```
The elixir formatter currently produces
```elixir
a =
  {b, c} =
  case d do
    e -> e
  end
```

### Expected behavior

It seems either of two formats would work better in this case:
```elixir
a = {b, c} =
  case d do
    e -> e
  end
```
or
```elixir
a =
  {b, c} =
    case d do
      e -> e
    end
```

---

We got a similar report for `erlfmt` in https://github.com/WhatsApp/erlfmt/issues/163 and I noticed Elixir formatter has a very similar behaviour. I'd be interested if this behaviour is intentional in the elixir formatter or just a coincidence of different rules coming together.

**Comment by josevalim** [comment] 2020-09-21 17:28
In my opinion, it is intentional. What I do in this case is to replace the operators and expressions and ask what looks natural. For example, I do expect this:

    foo ++
      bar ++
      baz

I think indenting baz another time would feel unnatural. There is an argument though that the first two should be on the same line but it is relatively hard to do with right precedence operators.

**Comment by josevalim** [comment] 2020-09-22 15:15
Closing this as it is considered working as intended for Elixir. If you do change it on `erlfmt`, please let us know! :heart:

**Closed by josevalim** 2020-09-22 15:15 UTC

**Comment by michalmuskala** [comment] 2020-09-22 15:17
Thanks, the reasoning makes sense. I'll let you know what we decide.
