### ISSUE TITLE
Mix Compile invalid argument

### ISSUE THREAD

**Issue by jruts** [elixir-lang/elixir#8459] opened 2018-12-04 12:55 UTC
### Environment
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.2 (compiled with Erlang/OTP 20)
Windows 10 (Ubuntu WSL)

### Current behavior

When I run `mix compile` in a new project (`mix new asapi --module ASAPI`) I always receive an invalid argument exception.

```bash
Compiling 1 file (.ex)
** (File.Error) could not touch "/c/Users/Jimmy/projects/asapi/_build/dev/lib/asapi/ebin/Elixir.ASAPI.beam": invalid argument
    (elixir) lib/file.ex:528: File.touch!/2
    (mix) lib/mix/compilers/elixir.ex:561: anonymous fn/4 in Mix.Compilers.Elixir.write_manifest/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/compilers/elixir.ex:555: Mix.Compilers.Elixir.write_manifest/5
    (mix) lib/mix/compilers/elixir.ex:198: Mix.Compilers.Elixir.compile_manifest/9
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
```

### Expected behavior

I would expect `mix compile` to work on a default mix project.

**Comment by OnorioCatenacci** [comment] 2018-12-04 13:50
It sounds as if he's using the "Ubuntu shell thingy" :)  Just for sake of insuring it's not some sort of regression, I'd have someone test this on true Ubuntu (not WSL) with the configuration he mentions.  It's unlikely but not impossible that this may be some sort of Ubuntu issue.

The other thing I'd check (if I were him) is to insure that path "/c/Users/Jimmy/projects . . . " is actually there.  And make sure that the case is correct as well--remember that while Windows isn't case sensitive, Ubuntu is.

**Comment by OnorioCatenacci** [comment] 2018-12-04 13:51
I don't know if I have WSL on my Windows box @josevalim because I only use Windows for work and I'm not sure if work permits the installation of WSL.  Hence it may take me a day or two to get a repro environment set up.  But I'll see what I can do to help!

**Comment by jruts** [comment] 2018-12-04 14:34
Hi @josevalim (and @OnorioCatenacci ). It happens on any project I create with `mix new...`.
And I am using the [Ubuntu subsystem on Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10), or as you call it, an _Ubuntu shell thingy_.

I have played around with Elixir before on a native ubuntu installation and did not have those issues.
I can also confirm that the path `/c/Users/Jimmy/projects/asapi/_build/dev/lib/asapi/ebin/Elixir.Asapi.beam` actually exists.

So to recreate I did nothing more than:
1. `mix new asapi --module ASAPI` (I also tried it without `--module`)
2. `cd` into the new project and run `mix compile`.

Thanks for looking into this!

**Comment by OvermindDL1** [comment] 2018-12-04 15:18
I don't have WSL installed at work, couldn't keep using it due to issues it had so I can't test currently...  :-/

**Comment by josevalim** [comment] 2018-12-04 15:52
> And I am using the Ubuntu subsystem on Windows, or as you call it, an Ubuntu shell thingy.

Haha, sorry for the poor name, but I wanted to give you a reply before I went into a meeting.

@jruts can you try some manual tests? If you start `iex`, outside of a project, can you open up files with `File.read`? If so, does it work with absolute paths? With relative paths? With volume relative paths? Trying to narrow the problem down can be helpful!

**Comment by jruts** [comment] 2018-12-04 16:01
Hi @josevalim ,

first of all you were not in a meeting, you were live streaming on Twitch 😄 .

So I did some manual test as per your suggestion, and the issue seems to be a simlink.

So my Ubuntu subsystem has a simlink in my home folder to my user folder in Windows.

So on Windows I have: `C:\Users\Jimmy\projects`
And in my Ubuntu home dir `~`  I have a simlink to `C:\Users\Jimmy\projects`.

When I create a `mix new` project inside the simlink folder then I have the issue as described in the first post.

If I create the `mix new` project in my Ubuntu home dir or just anywhere _but_ a simlink, it works just fine.

So thanks for helping me to point down the issue.
Not sure how to fix it rather then not creating the mix project inside a simlinked folder.

**Comment by josevalim** [comment] 2018-12-04 17:09
> first of all you were not in a meeting, you were live streaming on Twitch 😄 .

I am hoping that counts as a meeting :P

> Not sure how to fix it rather then not creating the mix project inside a simlinked folder.

Can you reproduce the error from the *Ubuntu shell thingy*? What if you create the project inside the symlink as before and then you do:

    touch /c/Users/Jimmy/projects/asapi/_build/dev/lib/asapi/ebin/Elixir.Asapi.beam

Does it work? What is the result of `echo $?`? Because if that doesn'twork, then it is a *Ubuntu shell thingy* bug. :)

**Comment by jruts** [comment] 2018-12-04 20:13
Hey @josevalim ,

> Can you reproduce the error from the Ubuntu shell thingy? What if you create the project inside the symlink as before and then you do:
> 
> `touch /c/Users/Jimmy/projects/asapi/_build/dev/lib/asapi/ebin/Elixir.Asapi.beam`
> 

This is when the issues happens.

So I think it is safe to assume that the Ubuntu Shell Thingy is the issue :)

If you agree then I (or you) can close the issue.

**Comment by josevalim** [comment] 2018-12-04 20:14
Closing this as requested then. :)

**Closed by josevalim** 2018-12-04 20:14 UTC
Labels: Note:Windows

**Comment by jruts** [comment] 2018-12-04 20:16
I will always remember this as the day the creator of Elixir talked to me 😄 
Thanks @josevalim

**Comment by OnorioCatenacci** [comment] 2018-12-04 21:51
I can tell you from experience that José is a great guy! That's part of the
reason I am happy to see Elixir taking off.
