### ISSUE TITLE
GenServer termination log doesn't use process label

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#13923] opened 2024-10-21 19:37 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 25)

### Operating system

MacOS Sonoma 14.6

### Current behavior

GenServer termination logs `GenServer #PID<0.812305.0> terminating`

### Expected behavior

If a process label has been set, it should be included in this log instead of, or in addition to, the PID

**Comment by sabiwara** [comment] 2024-10-23 22:08
@nathanl it actually should [be the case](https://github.com/elixir-lang/elixir/blob/fbc618ea35d2ab4cec784f9f20bbe13404e1504c/lib/logger/test/logger/translator_test.exs#L214-L225) already if the label is present, do you have a repro for this?

One hypothesis: it could be a manually emitted one supported by this [clause](https://github.com/elixir-lang/elixir/blob/fbc618ea35d2ab4cec784f9f20bbe13404e1504c/lib/logger/lib/logger/translator.ex#L131-L133). But in this case, I don't think we even have the process label data available, so I'm not sure there's anything to be done.

> Elixir 1.17.3 (compiled with Erlang/OTP 25)

Another hypothesis, although I don't think that's the reason, but just to rule it out: do have the same issue if you use a "compiled with OTP27" version?

**Comment by josevalim** [comment] 2024-10-30 07:32
Hi @nathanl, please let us know if you have updates here. Thanks!

**Comment by josevalim** [comment] 2024-11-06 14:48
I will close this since we cannot reproduce. But we will gladly reopen if we have more info!

**Closed by josevalim** 2024-11-06 14:48 UTC
Labels: App:Logger, Note:Needs more info
