### ISSUE TITLE
Module definitions lost after `defoverridable`

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8896] opened 2019-03-15 09:53 UTC
### Environment

```
$ elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

### Current behavior

Given a file defining this module

```
defmodule MyOtherModule do
  def foo, do: "hello"
  IO.inspect Module.definitions_in(__MODULE__, :def), label: "Definitions 1"
  defoverridable [foo: 0]
  IO.inspect Module.definitions_in(__MODULE__, :def), label: "Definitions 2"
end
```

when compiled gives the following output:

```
$ mix do clean, compile
Compiling 18 files (.ex)
Definitions 1: [foo: 0]
Definitions 2: []
Generated things app
```

That is, the module definitions have been lost after the `defoverridable` clause.

### Expected behavior

Declaring something as overridable should not affect the fact that it is a declared definition, consequently the output should be

```
$ mix do clean, compile
Compiling 18 files (.ex)
Definitions 1: [foo: 0]
Definitions 2: [foo: 0]
Generated things app
```

**Comment by mguimas** [comment] 2019-03-15 10:01
It seems that it is the definitions in the list passed to `defoverridable` that are lost.

**Comment by josevalim** [comment] 2019-03-15 10:05
Yes, good catch. this is by design, since defoverridable effectively
removes the definition until a new one is added. We should likely document
it better though.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by mguimas** [comment] 2019-03-15 10:05
Without looking into the code, it seems that there is a kind of "definitions collection" from where the overridable ones are removed. Instead of doing so, t would be preferable to allow a definition to be redefined in case it has an entry in an "overridable collection".

**Comment by mguimas** [comment] 2019-03-15 10:13
@josevalim I don't know if it is "by design" in the sense that the observed behavior is meant for any developer to take advantage (I mean, developers outside of the core team), or if it is more "by implementation", and the implementation I suggested could inform how to fix.

In the first case, then it is as you say, it should be documented better because it involves unclear interference between two APIs, otherwise it should be fixed.

Thanks

**Comment by mguimas** [comment] 2019-03-15 10:37
@josevalim One issue I find if we keep the current behavior, is that if I add a `@before_compile` hook which attempts to know which definitions are present in the module, this won't work if there is a `defoverridable` before the hook is run.

This example seems to show the need for reconsideration of the current implementation.

Thanks

**Comment by josevalim** [comment] 2019-03-15 10:51
The opposite is also true, if something was marked as overridable and you
want to know if the user overrode it or not, we can’t if we change the
behavior as you propose.

As already said, the current behavior is by design and we will document it.
Changing it would be a breaking change.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mguimas** [comment] 2019-03-15 11:05
Ok. I suggest you then to include in the documention the following:

- how to know which definitions are present in a module despite they were listed in `defoverridable`

- and, how to get the list of all overridable definitions in a module

**Comment by josevalim** [comment] 2019-03-15 11:10
You can check for overridable?/2 to know if something is overridable but
there is no mechanism to retrieve all of them. A proposal should be sent to
the mailing list outlining the use case so we can add it to the language.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mguimas** [comment] 2019-03-15 11:12
And what about the first bullet point:

> how to get the list of all definitions in a module, despite they were added or not to defoverridable

**Comment by mguimas** [comment] 2019-03-15 11:36
I add two other use cases:

Suppose in a `@before_compile` hook we need to know if the current definition of a function was that added by `use X`, or that added by `use Y`, which overrode the one added by `use X`?

What if we wants to forbid overrides of the definitions added by `use X`?

**Comment by josevalim** [comment] 2019-03-15 11:51
Can you please send a proposal to the mailing list? Try to be as
descriptive as possible and use actual examples instead of X and Y. For
example, the bug report you did on Module.create/2 is very good. Note, you
usually know what was marked as overridable, so filtering your list through
Module.overridable?/2 should be enough but we can only say for sure with a
complete specification of the problem, which we don’t have.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mguimas** [comment] 2019-03-15 11:56
Ok, I will try to compose a clear one. Neverthless, despite the decision about the proposal, the before mentioned interference between `defoverridable` and `Module.definitions_in`, should, as you agreed, be documented clearly next to these two APIs. Thanks

**Closed** 2019-03-26 12:26 UTC
