### ISSUE TITLE
Can't pattern-match string with pinned-variable fixed prefix

### ISSUE THREAD

**Issue by henrik** [elixir-lang/elixir#4181] opened 2016-01-10 20:56 UTC
Not sure if this is a bug or by design. If nothing else, the error message is a bit misleading:

```
iex(5)> "123" <> _ = "123456"
"123456"
iex(6)> a = "123"
"123"
iex(7)> ^a <> _ = "123456"
** (CompileError) iex:7: a binary field without size is only allowed at the end of a binary pattern
```

I would have expected that last example to match, since `^a` should resolve to the known-size `"123"`.

Elixir 1.2.0.

**Comment by tuvistavie** [comment] 2016-01-10 21:34
I think this is a duplicate of #3406
From what I understood, when using a variable, the size cannot be resolved early enough in the compilation process.

**Comment by josevalim** [comment] 2016-01-10 21:36
Yes, precisely. The size is *not* known.

**Closed by josevalim** 2016-01-10 21:36 UTC

**Comment by henrik** [comment] 2016-01-10 22:26
Thank you!
