### ISSUE TITLE
IEx not saving shell history with ERL_AFLAGS set

### ISSUE THREAD

**Issue by mgartner** [elixir-lang/elixir#6475] opened 2017-08-17 21:18 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20, Elixir 1.5.1 
* Operating system: macOS Sierra 10.12.4

### Current behavior

Setting the environment variable `ERL_AFLAGS="-kernel shell_history enabled"` does not enable shell history to be saved in `iex` sessions. I have made sure this environment variable is set, and I have noticed that shell history is indeed working for Erlang's REPL, `erl`. 

If I explicitly turn on shell history when starting `iex` with `iex --erl "-kernel shell_history enabled"` then shell history is saved correctly.

### Expected behavior

According to the [docs](https://hexdocs.pm/iex/IEx.html#module-shell-history) this should enabled shell history between `iex` sessions.

**Comment by josevalim** [comment] 2017-08-17 21:31
I cannot reproduce this behaviour. How are you setting the environment variable? If you are changing your profile, can you make sure you are starting a new instance? What does running `iex` show in your case (the first line)?

**Comment by mgartner** [comment] 2017-08-17 22:31
I use zsh, and I'm just setting it in my `~/.zshrc` file.

![image](https://user-images.githubusercontent.com/1128750/29436579-0f05047e-8361-11e7-8733-a48c95b491d9.png)

**Comment by josevalim** [comment] 2017-08-18 07:45
Thanks. @mgartner and just to make sure we are all on the same page: if you press the up arrow, it does not show anything, right?

**Comment by Bjarno** [comment] 2017-08-18 11:02
I can confirm this issue on macOS Sierra (using bash).

A simple workaround I quickly tested was adding this to Bash, instead of adding an environment variable.

```
alias iex='iex --erl "-kernel shell_history enabled"'
```

While it can give some issues (e.g. if you then want to pass additional parameters, it will probably given an error), in most cases this will be fine.

**Comment by josevalim** [comment] 2017-08-18 12:07
What is the value of `System.get_env "ERL_AFLAGS"` inside your IEx session? To clarify, Elixir does not touch this environment variable anyway, so if it is not working, maybe the environment variable is not going through?

**Comment by mgartner** [comment] 2017-08-18 16:19
Did some more testing and I thought I was going crazy when I saw what seemed to be non-deterministic saving of the history. I think I know what is going on though.

When I was initially testing the history feature, I was `Ctrl-C`ing to kill `iex` very shortly after entering a command into the REPL. I'm assuming that writes to the history file are asynchronous, and that I was killing the VM before the latest history could be flushed to the file.

My tests seem to support this – if I enter a command and quickly kill `iex` then that command is not saved, and if I enter a command and wait a moment before killing the REPL, then it works.

@Bjarno can you confirm if this is the case for you as well?

**Comment by OvermindDL1** [comment] 2017-08-18 19:54
> My tests seem to support this – if I enter a command and quickly kill iex then that command is not saved, and if I enter a command and wait a moment before killing the REPL, then it works.

That is the way the feature is designed, it saves every few commands or so (forget the precise amount).  Ctrl+C'ing will prevent it from saving.  Should safely exit by instead doing something like Ctrl+g, then q<enter>.  :-)

**Comment by mgartner** [comment] 2017-08-18 20:04
Ya I figured. However, even if I `Ctrl-g` then `q` too quickly, then the history is not saved either.

**Comment by Bjarno** [comment] 2017-08-18 21:05
I can confirm this behaviour, when closing `iex` too fast, the history is not saved. If I wait a couple of seconds, it is. This contradicts the following...

> That is the way the feature is designed, it saves every few commands or so (forget the precise amount).

I think it should save either way, even if the command crashes the shell. When restarting the application, after making some changes, I often redo the same commands, but if sometimes history is not saved, this is inconsistent behaviour.

**Comment by josevalim** [comment] 2017-08-18 21:17
I will close this issue then as it is not an Elixir issue.

> I think it should save either way, even if the command crashes the shell. When restarting the application, after making some changes, I often redo the same commands, but if sometimes history is not saved, this is inconsistent behaviour.

The feature is provided fully by Erlang - so please forward such suggestions to them. :)

**Closed by josevalim** 2017-08-18 21:17 UTC
