### ISSUE TITLE
Another beam_dead issue.

### ISSUE THREAD

**Issue by suazithustra** [elixir-lang/elixir#8954] opened 2019-04-13 18:00 UTC
Probably just a duplicate of [#8626 ](https://github.com/elixir-lang/elixir/issues/8626), but submitting anyway for sobriety.

### Environment
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
on MacOS 10.13.6
### Current behavior

The code is broad, so I'm attaching it. The macros causing this are in `beam_error/css.ex`.
[beam_error.zip](https://github.com/elixir-lang/elixir/files/3076540/beam_error.zip)
```
Compiling 13 files (.ex)
Function index.html/1 refers to undefined label 71

== Compilation error in file lib/beam_error_web/views/page_view.ex ==
** (CompileError) lib/beam_error_web/views/page_view.ex: internal error in beam_dead;
crash reason: {case_clause,{'EXIT',{undefined_label,71}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 439)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Expected behavior

Successful compilation, assuming the code is ok.

**Comment by fertapric** [comment] 2019-04-13 19:56
@suazithustra thanks for reporting! Fortunately, it's the same error and it's fixed in master!

If you run your code against master, it will raise:

```
== Compilation error in file lib/beam_error_web/views/page_view.ex ==
** (CompileError) lib/beam_error_web/views/page_view.ex:2: cannot invoke macro styles_css/1 before its definition
```

As the error above says, the problem is that the macros generated by `BeamError.CSS` are used before its definition. This happens because Phoenix also uses `@before_compile` to compile the templates, and the generated code is placed before the macros generated by `BeamError.CSS`.

If you change the order, everything compiles:

```elixir
defmodule BeamErrorWeb.PageView do
  use BeamError.CSS
  use BeamErrorWeb, :view
end
```

**Closed by fertapric** 2019-04-13 19:56 UTC

**Comment by suazithustra** [comment] 2019-04-13 20:18
That’s amazing, I can’t thank you enough for sharing that with me.
