### ISSUE TITLE
`mix deps.get` gets confused with "> 0.0.0"

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4829] opened 2016-06-19 06:50 UTC
I've got Elixir v1.2.6 running on OS X.

Here's a test project in which you can reproduce the issue – https://github.com/alco/mixdepstest.

Clone the project and edit the Ecto dep `mix.exs` to look like this:

``` elixir
{:ecto, "2.0.0-rc.6"},
```

Then run `mix deps.get`. Here's the result I get:

```
$ mix deps.get
Running dependency resolution
Dependency resolution completed
  connection: 1.0.2
  db_connection: 1.0.0-rc.1
  decimal: 1.1.2
  ecto: 2.0.0-rc.6
  poolboy: 1.5.1
  postgrex: 0.11.2
* Updating ecto (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ecto-2.0.0-rc.6.tar)
  Using locally cached package
* Updating postgrex (Hex package)
  Checking package (https://repo.hex.pm/tarballs/postgrex-0.11.2.tar)
  Using locally cached package
* Updating db_connection (Hex package)
  Checking package (https://repo.hex.pm/tarballs/db_connection-1.0.0-rc.1.tar)
  Using locally cached package
Dependencies have diverged:
* postgrex (Hex package)
  the dependency postgrex

  > In mix.exs:
    {:postgrex, "> 0.0.0", [hex: :postgrex, manager: :mix]}

  does not match the requirement specified

  > In deps/ecto/mix.exs:
    {:postgrex, "~> 0.11.2", [hex: :postgrex, optional: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

Without making any other changes I run `mix deps.get` again and it works this time around:

```
$ mix deps.get
Running dependency resolution
All dependencies up to date
```

That is why I think it's a bug, because the error only happens in the first invocation of `mix deps.get`.

You can see the resulting `mix.lock` that I got in [this commit](https://github.com/alco/mixdepstest/commit/71a2c1c22e2ecfa963e4922c7f4920bcdb4a8647) in the test repo.

**Comment by josevalim** [comment] 2016-06-19 08:35
Can you please check if it has been fixed on master and you are running on
latest Hex? :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment] 2016-06-19 13:49
@josevalim I still think the `:divergedreq` check is wrong. What we really should be checking is if the version requirements are not compatible/overlapping (we would need to add this functionality to `Version`). But what we are checking is if the new requirement matches the compiled version in .app. We shouldn't do that check because we will be recompiling postgrex anyway since it changed.

**Comment by alco** [comment] 2016-06-19 16:18
The error doesn't appear when using Elixir master (e26f8de5753c16ad047b25e4ee9c31b9a45026e5) and Hex v0.12.1.

**Comment by ericmj** [comment] 2016-06-19 16:20
@alco Did you recreate the same _build/ when you tested on Elixir master? Or rather; can you reproduce it again on Elixir v1.2.6?

**Comment by alco** [comment] 2016-06-19 16:30
After switching back to Elixir v1.2.6, I wasn't able to reproduce this, before and after removing `_build/`. It may have had to do with the particular Hex version I had on the first try but I don't remember seeing any suggestions to upgrade Hex at the time when I filed the issue.

**Comment by ericmj** [comment] 2016-06-19 16:33
@alco I think you should be able to reproduce by fetching and compiling a version of postgrex that doesn't match "~> 0.11.2" and then changing the mix.exs file to `{:ecto, "2.0.0-rc.6"}` again.

**Comment by alco** [comment] 2016-06-19 16:46
Compiling the project with Ecto v2.0.0-rc.5 and Postgrex v0.11.1, then updating to Ecto v2.0.0-rc.6 and doing `mix deps.get` reproduces the error.

**Comment by josevalim** [comment] 2016-11-20 09:21
I can no longer reproduce it on Elixir master. I will gladly reopen if others can still reproduce this.

**Closed by josevalim** 2016-11-20 09:21 UTC
Labels: App:Mix, Kind:Bug
