### ISSUE TITLE
mix local.hex does nothing in Windows

### ISSUE THREAD

**Issue by zorbyte** [elixir-lang/elixir#9987] opened 2020-04-28 02:57 UTC
### Environment

* Elixir & Erlang/OTP versions:
```
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.10.0 (compiled with Erlang/OTP 21)
```
* Operating system: Windows 10

* Shell: Powershell (Same behavior in cmd)

### Current behavior

I am trying to learn elixir and I wanted to use the koans repository. My editor intelisense for elixir kept crashing, and I found that after doing mix local.hex, it would try to run and immediately crash (presumably because the installation is important). Running `mix local.hex` yields not result. I tried with the --force flag as well. I tried this with the latest version of elixir (1.10.3) and the same behaviour occurs.
![Code_SNR8shSlxX](https://user-images.githubusercontent.com/39759284/80442126-ae6ca980-894f-11ea-92e0-7a638599c918.png)

Additionally, when attempting the same through git bash the following occurs:
![mintty_mDr9AvA0p9](https://user-images.githubusercontent.com/39759284/80442324-fbe91680-894f-11ea-959e-e952d66ddcc3.png)

### Expected behavior

Hex should install successfully.

**Comment by michallepicki** [comment] 2020-04-28 08:31
Not sure if related but dialyzer suggests that the functions `` `Elixir.Hex`:start()`` at `Mix.Hex.start/0` and `` `Elixir.Hex`:version() `` at two places in `Mix.Hex.ensure_updated?/0` do not exist

**Comment by josevalim** [comment] 2020-04-28 09:15
@michallepicki we check if Hex is loaded before running those functions, it is just that Dialyzer doesn't see it. :)

**Comment by ericmj** [comment] 2020-04-28 09:20
Another option is to build Hex yourself if you cant install the prebuilt version:

```
git clone https://github.com/hexpm/hex.git
cd hex
git checkout v0.20.5
mix install
```

**Comment by zorbyte** [comment] 2020-04-29 01:38
Building it from source solved the issue.

**Comment by zorbyte** [comment] 2020-04-29 02:01
Not sure if this is related but now a new issue has arrived, where running mix deps.get observes the same behaviour.

**Comment by josevalim** [comment] 2020-04-29 07:19
Hi @zorbyte, it would be the same issue. It seems that Erlang/Elixir is having troubles doing HTTP request. What happens if you try this out. Start `iex` by calling `iex` (or `iex.bat`) and then run this:

```elixir
iex(1)> Application.start(:inets)
:ok
iex(2)> :httpc.request('http://google.com')
{:ok,
```

Note it should be single quotes instead of double quotes.

**Comment by zorbyte** [comment] 2020-04-29 23:01
It functions correctly, it returns :ok and the second also returns a body.

**Comment by josevalim** [comment] 2020-04-29 23:42
@zorbyte thanks! What about this: 

```iex
iex(1)> Application.start(:inets)
:ok
iex(2)> :httpc.request('https://repo.hex.pm/installs/1.10.0/hex-0.20.5.ez')
```

Also, are you behind a proxy? You can try typing `SET` on a Windows shell or `env` on a Unix shell and see if HTTP_PROXY or HTTPS_PROXY environment variables are set.

**Comment by zorbyte** [comment] 2020-04-29 23:54
@josevalim I get the following output:
```
iex(1)> Application.start(:inets)
:ok
iex(2)> :httpc.request('https://repo.hex.pm/installs/1.10.0/hex-0.20.5.ez')
{:error,
 {:failed_connect,
  [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :ssl_not_started}]}}
```

I also checked those variables, none of which are set.

**Comment by josevalim** [comment] 2020-04-30 00:00
Ok, please try these now:

```elixir
iex(1)> Application.start(:inets)
:ok
iex(2)> Application.start(:ssl)
:ok
iex(3)> :httpc.request('https://repo.hex.pm/installs/1.10.0/hex-0.20.5.ez')
iex(3)> :httpc.request('https://google.com/')

**Comment by zorbyte** [comment] 2020-04-30 00:17
The following occurred:
```elixir
iex(1)> Application.start(:inets)
:ok
iex(2)> Application.start(:ssl)
{:error, {:not_started, :crypto}}
```

**Comment by zorbyte** [comment] 2020-04-30 00:21
I also tried this:
```elixir
iex(1)> Application.start(:inets)
:ok
iex(2)> Application.start(:crypto)
:ok
iex(3)> Application.start(:asn1)
:ok
iex(4)> Application.start(:public_key)
:ok
iex(5)> Application.start(:ssl)
:ok
iex(6)> :httpc.request('https://repo.hex.pm/installs/1.10.0/hex-0.20.5.ez')
```
iex exited immediately here, with no output.

**Comment by josevalim** [comment] 2020-04-30 00:30
@zorbyte oh! so you reproduced it. :) my hand is that there is something wrong with the crypto<->erlang interface. I would suggest reinstalling it or installing it using another way. How did you install it?

**Comment by zorbyte** [comment] 2020-04-30 00:31
I installed elixir using the GUI windows installer. However on my previous attempts to resolve this issue, I used chocolatey.

**Comment by josevalim** [comment] 2020-04-30 00:44
I am so sorry none of the steps above worked. My only suggestion then is for you to try a different Erlang version. Which ones have you tried? Consider trying 21.3 or 21.1 with Elixir v1.10.x or pick Elixir v1.9 and 20.1 or 20.3.

Note this is most likely an Erlang issue, so the Elixir version doesn't matter (as long as it supports the Erlang version you are running on).

**Comment by zorbyte** [comment] 2020-04-30 01:21
I'll give it a shot tomorrow. Thank you for your support thus far.

**Comment by zorbyte** [comment] 2020-05-04 13:17
Same results, gonna give WSL a shot.

**Comment by zorbyte** [comment] 2020-05-04 23:13
It does work on WSL, however this behaviour is abnormal so I will leave it to you if you would like to close this issue.

**Comment by josevalim** [comment] 2020-05-05 08:12
Thanks for the updates. Let's keep this open for a while more but I do suspect it to be an OS specific issue, unfortunately.

**Comment by i1t** [comment] 2020-05-11 13:10
I confirm the issue on Windows 10 Home x64.

Tried OTP 21-22 with Elixir 1.10.0 and OTP 20 with Elixir 1.9.4. No luck. Tried both standalone installers and installing via Chocolatey.

After installing, `mix archive` reports `hex` with unspecified version (on normal installation hex 0.20.5 is reported).

Everything as per above reports. Git Bash reports Segmentation fault. Cmd and PowerShell just crash with no output (mouse cursor changes to spinner, and Elixir shell exits silently within a second).

There are no issues with Windows 10 Corporate LTSC x64. In both cases all updates are installed, both Windows versions are the latest available.

**Comment by i1t** [comment] 2020-05-11 13:15
@zorbyte, which Windows 10 edition are you using? Is it Home x64?

**Comment by zorbyte** [comment] 2020-05-11 22:11
Yeah

**Comment by PragTob** [comment] 2020-05-12 17:46
Heyho, our benchee CI on appveyor seems to be hit by this as well.

You can see a failing build here: https://ci.appveyor.com/project/PragTob/benchee-8e4gw/builds/32804950

Our error message basically looks like this:

```
mix local.hex --force
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1085}]},{init,do_boot,3,[{file,"init.erl"},{line,793}]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})
Crash dump is being written to: erl_crash.dump...done
Command exited with code 1
```

Claims to be running most recent elixir/erlang versions:

```
Progress: Downloading erlang 22.3... 100%
Progress: Downloading Elixir 1.10.3... 100%
```

Cheers and as always thanks for all your work! :)

**Comment by josevalim** [comment] 2020-05-12 17:51
@PragTob your error is a different one, unfortunately. It seems like `mix` and `elixir` are not being able to find the files in `ebin`.

@PragTob can you double check if it works with 1.10.2? thanks!

**Comment by PragTob** [comment] 2020-05-12 17:53
@josevalim fast and helpful as always :green_heart: 

Sorry didn't check my error message further as it looked similar enough and I wanted to do something else :sweat_smile: But there's a PR to get merged, will check.

**Comment by PragTob** [comment] 2020-05-12 19:12
@josevalim somehow couldn't roll back to `1.10.2` chocolatey doesn't seem to have all versions so 1.10.2 errored out. I'm not quite sure how they wok with what's available https://chocolatey.org/packages/Elixir#versionhistory - rolled back to 1.9.4 which does work. 

Sorry don't have the time to work on a manual setup to get the version working right now. But rolling back to 1.9 has alleviated the problem for me/us for now.

**Comment by i1t** [comment] 2020-05-13 05:28
To anyone reading the above comment and ready to try out 1.9.4: unfortunately, it helped with in irrelevant problem also reported in this thread by a mistake, and it doesn't help with _silent_ crashes of `mix local.hex` on Windows 10 Home.

If you guys have any messages from `mix local.hex` then it's almost certainly a different issue, please report separately.

**Comment by josevalim** [comment] 2020-05-18 08:07
I could not reproduce any of the issues in my Windows VM. Since this issue seems to be hit or miss, we are now pointing users to run the command `mix archive.install github hexpm/hex branch latest` whenever we cannot install Hex. This should allow them to get unstuck and move forward in their Elixir journey.

**Closed by josevalim** 2020-05-18 08:07 UTC
Labels: Note:Windows

**Comment by fedoracoreuser** [comment] 2020-06-01 08:42
Hello, sorry to  bump this, but I've run into this issue with every install of elixir on this laptop in particular (intel 10th gen Ice lake). By following things around the various bug tracking boards of elixir, erlang and openssl, it appears that the culprit is a bug in the OpenSSL version used by Erlang OTP up to version 23. This version tries to use Intel SHA extensions, but they break on several processors. Intel suggests a workaround that uses a software-based alternative path in the code, and it seems to work:

Add an environment variable called OPENSSL_ia32cap. set its value to ":~0x20000000", as in the attached screenshot.
![OpenSSL_ia32cap](https://user-images.githubusercontent.com/947134/83391750-3c76fc80-a3f4-11ea-9c0f-1c58942f059c.jpg)

Close and reopen terminals, and it "works on my machine".
I don't like it, I don't like messing with OpenSSL flags, or running old versions of it, but it is not an Elixir problem. Hope this helps people stumbling across this page as I did.

**Comment by Codball** [comment] 2020-06-14 22:53
> Close and reopen terminals, and it "works on my machine".

Had this issue as well, brand new LG Gram with Intel 10th Generation i7-1065G7 CPU

**Comment by propername** [comment] 2020-09-12 15:47
also had this issue, new surface. thanks

**Comment by send2abhishek** [comment] 2020-09-29 01:29
Building from source resolved the issue for me
git clone https://github.com/hexpm/hex.git
cd hex
git checkout v0.20.5
mix install

**Comment by roehst** [comment] 2021-04-10 20:44
Had the same issue here after running the official Windows installer. Uninstalling and choosing a lower erlang version using Chocolatey solved ir for me.

**Comment by frunox** [comment] 2021-10-20 15:57
I had the same issue (segmentation faults when executing 'mix deps.get').  I run Windows 10 Pro.  

I uninstalled Elixir/Erlang, then first installed Erlang/OTP v, 24.  Then I used the installation file from elixir-lang.org and installed Elixir v 1.12.3.  It sees the Erlang/OTP installation, so it only installs Elixir.

This solved the problem.  I was able to use 'mix deps.get' to install a dependency.

**Comment by dylantf** [comment] 2021-11-09 14:54
Same issue for me on a fresh win10 (and win11, tried both) install. I tried elixir 1.10, 1.11, and 1.12 with OTP 20, 21, and 22 and nothing worked, no output from any mix command. Building hex from source didn't fix it. Adding the OpenSSL flag above seems to have fixed it, though I don't know what it does.

**Comment by frunox** [comment] 2021-11-09 15:13
dylantf:
What worked for me:

-  Uninstall Elixir/Erlang.
-  Then, download the Erlang Windows installer from [https://www.erlang.org/downloads#prebuilt](https://www.erlang.org/downloads#prebuilt).  Install Erlang v. 24.  Do this first before installing Elixir.
- Then use the Elixir Windows installer to install Elixir.  It recognizes the existing Erlang installation so it does not overwrite it.   Now both will be installed and 'mix deps.get' should work normally.

The Elixir Windows installer does not include Erlang v.24 as an option.

**Comment by josevalim** [comment] 2021-11-09 16:19
I change the installer to install Erlang/OTP 24.1 by default. If someone could give it a try and tell us if it is all good, it will be appreciated. Thanks!

**Comment by fedoracoreuser** [comment] 2021-11-09 19:48
Hello, the new version seems to work correctly on both of my machines (i7-6700k and i7-1145G7, both running Windows 11). Thank you!

**Comment by dylantf** [comment] 2021-11-10 07:36
I had tried installing OTP 23 manually before and it still did not work, but the updated installer with 24.1 _does_ work for me now on my i7 surface laptop 3. It's interesting that my other computer had no problems with any versions.

**Comment by fedoracoreuser** [comment] 2021-11-10 10:14
At least in my situation, it was due to a weird corner case between:
- the CPU in use, which broke some Intel SHA extensions (looking at you, Ice Lake)
- the specific version of the OpenSSL library in use within the Erlang version itself.

If that's not an amazing coincidence, I don't know what is.
