### ISSUE TITLE
URI.parse can't parse uppercase URLs

### ISSUE THREAD

**Issue by samphilipd** [elixir-lang/elixir#9343] opened 2019-09-13 10:52 UTC
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
```

I suspect this may be a regression, because it used to work. But it seems that URI cannot parse uppercase urls any more. See below:

```
iex> URI.parse("HTTP://EXAMPLE.COM")
...> %URI{
  authority: nil,
  fragment: nil,
  host: nil,
  path: "HTTP://EXAMPLE.COM",
  port: nil,
  query: nil,
  scheme: nil,
  userinfo: nil
}
```

**Comment by josevalim** [comment] 2019-09-13 15:29
So I tried both master and v1.9.1 and I got this:

```
iex(2)> URI.parse("HTTP://EXAMPLE.COM")
%URI{
  authority: "EXAMPLE.COM",
  fragment: nil,
  host: "EXAMPLE.COM",
  path: nil,
  port: 80,
  query: nil,
  scheme: "http",
  userinfo: nil
}
```

Same OTP version. I am puzzled. What could be the cause of the difference? Can you make sure your string does not have any Unicode character that looks like an ascii character but actually isn't?

**Comment by eksperimental** [comment] 2019-09-14 00:36
same here and I copied the code from your comment @josevalim `URI.parse("HTTP://EXAMPLE.COM")`

```console
$ elixir --version
Erlang/OTP 22 [erts-10.4.4] [source] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 20)
```

```iex
$ iex
Erlang/OTP 22 [erts-10.4.4] [source] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  URI.parse("HTTP://EXAMPLE.COM")
%URI{
  authority: nil,
  fragment: nil,
  host: nil,
  path: "HTTP://EXAMPLE.COM",
  port: nil, 
  query: nil,
  scheme: nil,
  userinfo: nil
}
```

**Comment by eksperimental** [comment] 2019-09-14 00:38
It is the scheme, when it contains an uppercase character it wouldn't recognize it.

**Comment by eksperimental** [comment] 2019-09-14 00:53
it works on master, in my system.
I'm looking into it, so I can submit a patch for v1.9

**Comment by eksperimental** [comment] 2019-09-14 01:15
Alright. I have read the changes since  v1.9.0 till today, and none of the new commits seems to be related to this. So I think it is related to the regexes, the way they are compiled. I know there have been changes to the Regex module, So i when ahead and compiled v1.9.0 in my system, and it works fine.

```iex
$ bin/iex 
Erlang/OTP 22 [erts-10.4] [source] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> URI.parse("HTTP://EXAMPLE.COM")
%URI{
  authority: "EXAMPLE.COM",
  fragment: nil,
  host: "EXAMPLE.COM",
  path: nil,
  port: 80,
  query: nil,
  scheme: "http",
  userinfo: nil
}
```

So it is definitely the Regex running in a different system that they have been compiled in.

**Comment by josevalim** [comment] 2019-09-14 06:52
Ah, so it was definitely fixed by 145b7019ae77cf7467d2b24548e9df8821f90e7f. If that's the case, this change of behaviour was one or two minor versions or go. We could backport it to v1.9 but it is somewhat a larger change so I would hold it until v1.10.

For now, you can surely fix it by making sure you are using an Elixir version compiled for your sysstem. Thanks @samphilipd for the report and @eksperimental for solving the mystery.

**Comment by rmoorman** [comment] 2019-10-11 10:01
@josevalim , the issue also crops up while using the latest 1.9.1 version provided through the erlang solutions repository.

One can reproduce it using e.g. by a Dockerfile like this:
````dockerfile
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y language-pack-en wget gnupg
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb \
	&& dpkg -i erlang-solutions_1.0_all.deb
RUN apt-get update
RUN apt-get install -y esl-erlang elixir
CMD elixir -e '"HTTP://example.com" |> URI.parse |> IO.inspect'
````
which yields:
````shell
$ docker build . -t elixir-issue-9343
(...) a lot of output (...)
Successfully tagged elixir-issue-9343:latest

$ docker run -it --rm elixir-issue-9343
%URI{
  authority: nil,
  fragment: nil,
  host: nil,
  path: "HTTP://example.com",
  port: nil,
  query: nil,
  scheme: nil,
  userinfo: nil
}
````
So the out-of-the-box experience is still a bit broken regarding URI (and maybe other packages using the same functionality).

From my testing, this also happens when elixir is installed through asdf (does not matter if erlang also has been installed through asdf or comes from erlang-solutions).

The issue does not crop up while using erlang-solutions provided erlang and compiling elixir from source (master) over here. (My base system is Ubuntu 18.04 based linux mint)

**Comment by rmoorman** [comment] 2019-10-11 14:50
@josevalim just spoke to you briefly on irc. You mentioned that the change simply was not released yet. But the problem also occurs when I use the master release from hex.pm.

Using a Dockerfile like this:
````Dockerfile
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y language-pack-en wget gnupg unzip
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb \
	&& dpkg -i erlang-solutions_1.0_all.deb
RUN apt-get update
RUN apt-get install -y esl-erlang
RUN wget https://repo.hex.pm/builds/elixir/master.zip
RUN unzip -d elixir-master/ master.zip
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
CMD elixir-master/bin/elixir -e '"HTTP://example.com" |> URI.parse |> IO.inspect'
````
(which downloads/uses the master "release" from hex.pm and runs it on top of the erlang solutions canned erlang) yields similar results:
````shell
$ docker run -it --rm elixir-issue-9343-2
%URI{
  authority: nil,
  fragment: nil,
  host: nil,
  path: "HTTP://example.com",
  port: nil,
  query: nil,
  scheme: nil,
  userinfo: nil
}
````
For reference the version information:
````shell
$ docker run -it --rm elixir-issue-9343-2 elixir-master/bin/elixir --version
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.0-dev (0eb3fbb) (compiled with Erlang/OTP 20)
````

**Closed** 2019-10-11 15:44 UTC
Labels: Note:Needs more info

**Comment by rmoorman** [comment] 2019-10-11 16:08
@josevalim , I can confirm that the issue does not surface again using the same methodology as used earlier. With the same dockerfile that refers to the master release on hex:
````shell
$ docker build . --no-cache  -t elixir-issue-9343-3
(...) a lot of output (...)
Successfully tagged elixir-issue-9343-3:latest

$ docker run -it --rm  elixir-issue-9343-3
%URI{
  authority: "example.com",
  fragment: nil,
  host: "example.com",
  path: nil,
  port: 80,
  query: nil,
  scheme: "http",
  userinfo: nil
}
````

Thank you for fixing this!
