### ISSUE TITLE
Elixir and mix crashing after install on macOS

### ISSUE THREAD

**Issue by bion** [elixir-lang/elixir#9931] opened 2020-04-11 21:53 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir 1.10.2, erlang 22.3.2.
* Operating system: macOS 10.15.3

I tried uninstalling both erlang and elixir with `brew uninstall` and reinstalling with `brew install elixir` and am still getting a crash.

### Current behavior
Running `elixir`, `mix`, and `iex` all result in a large crash output. `iex` does appear to still provide a prompt at the end of it though.

The error output from `elixir --version` along with the erl_crash.dump file are both in this gist: https://gist.github.com/bion/addedbd4a233cc3c6a00ce533090ee19

Running `erl` on the command line appears to be working:
```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Eshell V10.7.1  (abort with ^G)
1> 1 + 1.
2
```

**Comment by josevalim** [comment] 2020-04-12 09:39
Thank you for the report. Unfortunately I could not reproduce the issue using the same versions (although an older Mac version). Can you try using something like `asdf` or `kerl` to install another Erlang version (maybe 22.2 or 22.1) to rule out it being an issue with the Erlang version from brew?

**Comment by dmorneau** [comment] 2020-04-12 17:25
The binary in the stack trace starts with "ERCP", which is "PCRE" in reverse, meaning the regex was compiled on a system with a different endianness. This is similar to https://github.com/elixir-lang/elixir/issues/2785

Is it possible you might have some other install of Elixir on your path taking precedence over the Homebrew one?

**Comment by josevalim** [comment] 2020-04-13 11:28
Try removing `rm -rf ~/.mix` and let us know if it works!

**Comment by ericmj** [comment] 2020-04-14 11:02
Can you show the output of `brew info erlang` and `brew info elixir`?

**Comment by josevalim** [comment] 2020-04-21 18:49
Closing this. Please let us know if you have more information so we can move forward. Thanks.

**Closed by josevalim** 2020-04-21 18:49 UTC
Labels: App:Mix, Note:Needs more info

**Comment by brrgrl** [comment] 2023-07-02 13:09
I have this issue as well
