### ISSUE TITLE
Tests fail on Elixir v1.14.2 due to SystemTest failure

### ISSUE THREAD

**Issue by philippeqd** [elixir-lang/elixir#12290] opened 2022-12-06 13:06 UTC
### Elixir and Erlang/OTP versions

Elixir v1.14.2
Erlang 25

### Operating system

macOS Ventura Version 13.0

### Current behavior

I tried to install Elixir v1.14.2 by running the following commands:

```
brew install erlang@25
git clone https://github.com/elixir-lang/elixir.git
cd elixir
make clean test
```

The last `make clean test` command fails with the following output:

```
❯ make clean test

rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/src/elixir_parser.erl
rm -rf lib/*/_build/
rm -rf lib/*/tmp/
rm -rf lib/elixir/test/ebin/
rm -rf lib/mix/test/fixtures/deps_on_git_repo/
rm -rf lib/mix/test/fixtures/git_rebar/
rm -rf lib/mix/test/fixtures/git_repo/
rm -rf lib/mix/test/fixtures/git_sparse_repo/
rm -rf lib/mix/test/fixtures/archive/ebin/
rm -f erl_crash.dump
rm -f man/elixir.1
rm -f man/elixir.1.bak
rm -f man/iex.1
rm -f man/iex.1.bak
Recompile: src/elixir_utils
Recompile: src/elixir_tokenizer
Recompile: src/elixir_sup
Recompile: src/elixir_rewrite
Recompile: src/elixir_quote
Recompile: src/elixir_parser
Recompile: src/elixir_overridable
Recompile: src/elixir_module
Recompile: src/elixir_map
Recompile: src/elixir_locals
Recompile: src/elixir_lexical
Recompile: src/elixir_interpolation
Recompile: src/elixir_import
Recompile: src/elixir_fn
Recompile: src/elixir_expand
Recompile: src/elixir_errors
Recompile: src/elixir_erl_var
Recompile: src/elixir_erl_try
Recompile: src/elixir_erl_pass
Recompile: src/elixir_erl_for
Recompile: src/elixir_erl_compiler
Recompile: src/elixir_erl_clauses
Recompile: src/elixir_erl
Recompile: src/elixir_env
Recompile: src/elixir_dispatch
Recompile: src/elixir_def
Recompile: src/elixir_config
Recompile: src/elixir_compiler
Recompile: src/elixir_code_server
Recompile: src/elixir_clauses
Recompile: src/elixir_bootstrap
Recompile: src/elixir_bitstring
Recompile: src/elixir_aliases
Recompile: src/elixir
Generated elixir app
==> bootstrap (compile)
Compiled kernel.ex
Compiled kernel/utils.ex
Compiled macro/env.ex
Compiled keyword.ex
Compiled module.ex
Compiled list.ex
Compiled macro.ex
Compiled kernel/typespec.ex
Compiled code.ex
Compiled code/identifier.ex
Compiled protocol.ex
Compiled stream/reducers.ex
Compiled enum.ex
Compiled regex.ex
Compiled inspect/algebra.ex
Compiled inspect.ex
Compiled string.ex
Compiled string/chars.ex
Compiled kernel.ex
Compiled list/chars.ex
Compiled module/locals_tracker.ex
Compiled module/parallel_checker.ex
Compiled module/types/behaviour.ex
Compiled module/types/helpers.ex
Compiled module/types/unify.ex
Compiled module/types/of.ex
Compiled module/types/pattern.ex
Compiled module/types/expr.ex
Compiled module/types.ex
Compiled exception.ex
Compiled path.ex
Compiled file.ex
Compiled map.ex
Compiled range.ex
Compiled access.ex
Compiled io.ex
Compiled system.ex
Compiled code/formatter.ex
Compiled code/normalizer.ex
Compiled kernel/cli.ex
Compiled kernel/error_handler.ex
Compiled kernel/parallel_compiler.ex
Compiled kernel/lexical_tracker.ex
==> unicode (compile)
[Unicode] Break on 25 whitespace codepoints
[Unicode] Tokenizing 112077 non-ascii codepoints
[Unicode] Tokenizing 44 scriptsets
==> elixir (compile)
Generated elixir app
==> eex (compile)
==> mix (compile)
Generated mix app
==> ex_unit (compile)
Generated ex_unit app
==> logger (compile)
Generated logger app
Generated eex app
==> iex (compile)
Generated iex app
==> elixir (eunit)
  All 131 tests passed.

==> elixir (ex_unit)
Excluding tags: [windows: true]

...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test Unix cmd/3 with absolute and relative paths (SystemTest)
     test/elixir/system_test.exs:178
     match (=) failed
     code:  assert {"hello\n", 0} = System.cmd(Path.join(File.cwd!(), @echo), ["hello"], arg0: "echo")
     left:  {"hello\n", 0}
     right: {"", 137}
     stacktrace:
       test/elixir/system_test.exs:191: anonymous fn/0 in SystemTest."test Unix cmd/3 with absolute and relative paths"/1
       (elixir 1.15.0-dev) lib/file.ex:1620: File.cd!/2
       test/elixir/system_test.exs:183: (test)

....................................................................................................................................................
13:57:56.634 [error] beam/beam_load.c(180): Error loading module 'Elixir.Io':
  module name in object code is 'Elixir.IO'



13:57:56.634 [error] Loading of /Users/philippelammerts/Development/elixir/bin/../lib/elixir/ebin/Elixir.Io.beam failed: :badfile

..........................................................................................................................................................................................................................................................................................................................................................................................
Finished in 19.0 seconds (6.6s on load, 6.6s async, 5.7s sync)
1939 doctests, 4180 tests, 1 failure, 13 excluded

Randomized with seed 668952
```

The installation succeeds when I comment the failing test out and Elixir becomes functional again.

### Expected behavior

I expected a successful install.

**Comment by josevalim** [comment] 2022-12-06 15:19
I cannot reproduce the failure on macOS. 

The exit code is 137=128+9, which means some other process has sent it a signal 9, which is SIGKILL. So maybe something in the OS is not letting the script execute? Can you please try debugging the test? Can you go to the created temp directory and try to invoke the executable yourself?

**Comment by philippeqd** [comment] 2022-12-07 09:01
Thank you for your quick response. You were right, the macOS was not letting the echo script execute. We have looked into the issue and solved the problem.

A colleague of mine also runs on Ventura Version 13.0 and receives the following output when running the first part of the failing test:

```
iex(1)> System.find_executable("echo")
"/opt/homebrew/opt/coreutils/libexec/gnubin/echo"
```

When I am running this, I get the following:

```
iex(1)> System.find_executable("echo")
"/bin/echo"
```

The difference was that on his machine coreutils were installed, and on mine, it was not.

I fixed the problem on by installing coreutils:
```
brew install coreutils
```

And adding the following lines to my `.zshrc`:

```
BREW_PREFIX=/opt/homebrew
export PATH=${BREW_PREFIX}/opt/coreutils/libexec/gnubin:$PATH
```

Now the test passes as expected.

**Comment by josevalim** [comment] 2022-12-07 09:04
Thank you! I will close this for now but keep an eye open if more people run into this and we need to take further action.

**Closed by josevalim** 2022-12-07 09:04 UTC
Labels: Note:Needs more info

**Comment by jolee11** [comment] 2022-12-08 11:13
I think this is the problem of codesign.

I just google the problem and find this:
   https://developer.apple.com/forums/thread/130313

**Comment by dvic** [comment] 2022-12-08 13:35
Yes I also think so. The suggested solution in that thread is 'use mv not cp', which is of course not an option in this case.

**Comment by soren121** [comment] 2023-01-09 23:24
I don't quite understand why this was closed with a workaround to use GNU coreutils. It's clear from the linked thread above that Apple considers this to be the intended result of an intentional change in macOS 13+, not a bug. Shouldn't Elixir, or the test in question, be modified so it installs correctly on macOS 13?

**Comment by yilongli-tubi** [comment] 2023-02-13 05:33
Invoking `asdf install elixir ref:v1.14.3` on my macOS 13.2 still reports this issue.

**Comment by jechol** [comment] 2023-05-04 02:35
Invoking asdf install elixir ref:v1.14.4 on my macOS 13.2.1 still reports this issue.

**Comment by gsarwate** [comment] 2023-06-03 05:08
I could compile version 1.15.0-rc.0 (ref 3cdb388) using asdf - `asdf install elixir ref:3cdb388` on MacOS 13.4 (22F66) without installing coreutils.

I **could not** compile version 1.14.5(ref 81d6007) or 1.15.0-rc.1(ref d7bdf22) on the same Mac with or without coreutils.

**Comment by fartek** [comment] 2023-06-10 18:19
> I could compile version 1.15.0-rc.0 (ref [3cdb388](https://github.com/elixir-lang/elixir/commit/3cdb3883e4e3b38e5389d98cc9429a6ca4f17143)) using asdf - `asdf install elixir ref:3cdb388` on MacOS 13.4 (22F66) without installing coreutils.
> 
> I **could not** compile version 1.14.5(ref [81d6007](https://github.com/elixir-lang/elixir/commit/81d6007410b3ae43e279cfb689bd03ffc5f06830)) or 1.15.0-rc.1(ref [d7bdf22](https://github.com/elixir-lang/elixir/commit/d7bdf2270803c84971ad12e7a6b713fb2dfa9db4)) on the same Mac with or without coreutils.

I had the same problem ☝️.

https://github.com/elixir-lang/elixir/issues/12290#issuecomment-1340611999 was the solution in the end.

Initially I tried it in `nushell` which uses its own `echo`. Since that failed, I just ran zsh, added coreutils to my PATH (make sure to add it BEFORE `/bin`) and ran asdf install.

**Comment by serpent213** [comment] 2023-06-22 14:00
Same issue here, running Ventura 13.4 with brew coreutils 9.3.

```PATH=/usr/local/Cellar/coreutils/9.3/libexec/gnubin/:$PATH asdf install elixir ref:v1.14.5```

...did work in the end. Part of a (too) long journey to get ElixirLS to find the source code.
