### ISSUE TITLE
Incorrect pattern matching results using OTP 19.0.x on some platforms

### ISSUE THREAD

**Issue by scouten** [elixir-lang/elixir#5586] opened 2016-12-23 20:40 UTC
I've identified what looks like a bug in pattern matching (function head selection) in OTP 19.0.x, but only on some platforms.

### Environment

* Elixir versions tested: 1.2, 1.3.0, 1.3.2, 1.3.4 (happens in all versions)
* OTP versions tested: 18.0, 19.0, 19.1, 19.2 (happens **only** in OTP 19.0)
* Operating systems tested: Ubuntu 12.04.5 LTS, Mac OS 10.11.6 (happens **only** on Ubuntu)

### Current behavior

A minimal repro case (one file, one test) is available at https://github.com/scouten/otp-pattern-match. This is a very stripped down version of [sqlitex](https://github.com/mmmries/sqlitex), where I first encountered the bug.

If you examine the Travis CI build logs at https://travis-ci.org/scouten/otp-pattern-match/builds/186425073, you'll see that the test fails on OTP 19.0, but succeeds on 18.0, 19.1, and 19.2.

The bug is essentially that the code fails to match the `translate_value` clause at https://github.com/scouten/otp-pattern-match/blob/master/lib/pattern_match_bug.ex#L11 in my example. It instead falls through to the catch-all clause at line 23 and thus generates an unwanted result.

### Expected behavior

Test matches https://github.com/scouten/otp-pattern-match/blob/master/lib/pattern_match_bug.ex#L11 on all OTP versions.

**Comment by scouten** [comment] 2016-12-23 20:43
This is likely an OTP bug, but wanted to make sure Elixir core team was aware of it.

I will discontinue testing my code on OTP 19.0 for now. 🙂

**Comment by josevalim** [comment] 2016-12-23 21:48
It is a known bug that has been fixed. Here is the test case added to OTP: https://github.com/erlang/otp/commit/8b83bc0b54b728cf9179ef3fa0e7610f99f7a6a4

Since it was fixed on later 19.0 releases, I believe the OS difference is caused by the version in the OS package manager.

Thanks for the report!

**Closed by josevalim** 2016-12-23 21:48 UTC
