### ISSUE TITLE
warnings during build

### ISSUE THREAD

**Issue by yogo1212** [elixir-lang/elixir#7319] opened 2018-02-06 14:40 UTC
### Environment

* Erlang Erlang/OTP 20 
* Operating system: CentOS 7

### Current behavior

```
warning: erlang:get_stacktrace/0 used in the wrong part of 'try' expression. (Use it in the block between 'catch' and 'end'.)
  /opt/elixir/lib/elixir/lib/exception.ex:1244

warning: erlang:get_stacktrace/0 used in the wrong part of 'try' expression. (Use it in the block between 'catch' and 'end'.)
  lib/exception.ex:1244

warning: use Dict is deprecated, use the Map module for working with maps or the Keyword module for working with keyword lists
  lib/hash_dict.ex:11
```

and

```
make[1]: Entering directory `/opt/elixir'
==> unicode (compile)
erl_child_setup closed

Crash dump is being written to: erl_crash.dump...done
make[1]: *** [lib/elixir/ebin/Elixir.String.Unicode.beam] Error 1
make[1]: Leaving directory `/opt/elixir'
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 2
```

### Expected behavior

successful build without warnings :-D

**Comment by josevalim** [comment] 2018-02-06 15:15
The warnings are not related to the failure but we will take note to fix them since they can be confusing. :)

About the error, how much memory you have on this machine? Compiling Unicode is memory intensive, can it be the process is being killed due to OOM?

**Comment by josevalim** [comment] 2018-02-09 17:30
Ping.

**Comment by josevalim** [comment] 2018-02-10 18:22
Closing this. Please let us know if you have more info.

**Closed by josevalim** 2018-02-10 18:22 UTC
Labels: Note:Needs more info

**Comment by yogo1212** [comment] 2018-02-12 13:38
sorry, i didn't find the time to fetch my emails last week.
4GB

**Comment by josevalim** [comment] 2018-02-12 15:02
Thanks, can you consistently reproduce it?

**Comment by yogo1212** [comment] 2018-02-15 07:41
yes - on an amazon ec2-machine with centos7, installing gcc etc., adding the epel-repo, and then following instructions to install erlang (which include installing erlang).

**Comment by eksperimental** [comment] 2018-04-30 03:45
should this be reopened?
