### ISSUE TITLE
EEx can't compile `with` that contains an `else` clause

### ISSUE THREAD

**Issue by whitepaperclip** [elixir-lang/elixir#8809] opened 2019-02-18 20:54 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Erlang/OTP 21 [erts-10.2.3] Elixir 1.8.0 (compiled with Erlang/OTP 21)`
* Operating system: macOS 10.14.

### Current behavior

```elixir
string = """
<% y = ["a", "b", "c"] %>
<%= with list when is_list(list) <- y do %>
  list
<% else _ -> nil %>
<% end %>
"""

result = EEx.eval_string(string, [], engine: EEx.Engine)
IO.inspect(result)
```

```
 ** (SyntaxError) nofile:4: syntax error before: else
   lib/eex/compiler.ex:45: EEx.Compiler.generate_buffer/4
   lib/eex/compiler.ex:54: EEx.Compiler.generate_buffer/4
   lib/eex.ex:197: EEx.eval_string/3
   foo.exs:9: (file)
```

### Expected behavior

`list`

**Comment by josevalim** [comment] 2019-02-18 21:11
Can you please follow the issue template and fill in relevant information
such as the Elixir version? Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by denvaar** [comment] 2019-02-24 17:09
`<% else _ -> nil %>` is being evaluated as `:expr` -- should it be `:middle_expr`?

**Comment by josevalim** [comment] 2019-02-24 17:20
Yes! :D
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by denvaar** [comment] 2019-02-24 22:36
Hmm. actually maybe this is not a bug. Shouldn't it be written like this?

```string = """
<% y = [1, 2] %>
<%= with list when is_list(y) <- y do %>
  list
<% else _ -> %>
  nil
<% end %>
"""```

**Comment by josevalim** [comment] 2019-02-25 09:47
@denvaar you are correct. We always expect a closing `%>` after the `->`. So what you propose or what we have below would be a suitable alternative:

```elixir
string = """
<% y = ["a", "b", "c"] %>
<%= with list when is_list(list) <- y do %>
  list
<% else _ -> %>
<% end %>
"""
```

**Closed by josevalim** 2019-02-25 09:47 UTC
Labels: App:EEx, Kind:Bug, Note:Unresolved
