### ISSUE TITLE
Imperative Assignements are breaking the application in 1.7 update

### ISSUE THREAD

**Issue by jfayad** [elixir-lang/elixir#8076] opened 2018-08-13 09:15 UTC
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 21 [erts-10.0] [ source] [64-bit]
Elixir 1.7.0 (Compiled with Erlang/OTP 20)
* Operating system: Ubuntu 16.04

### Current behavior

After updated Elixir from 1.6 to 1.7 the `params` variable will always be equal to %{} outside the if statements

```
params = %{}

        if Map.has_key?(entities, "email") do
          params = Map.put_new(params, :email, get_values(entities["email"]))
        end
```

### Expected behavior

The `params` variable should be correctly assigned for now and updating to 1.7 shouldn't break such a code since nothing has been mentioned in the release not of 1.7

**Comment by jfayad** [comment] 2018-08-13 09:26
Actually no @fertapric since the variable is defined outside the if statement.

**Comment by wojtekmach** [comment] 2018-08-13 09:37
I can confirm the behaviour changed between 1.6 and 1.7:

```
~/foo% asdf local elixir 1.6.5 && elixir -e "x = 1; if(true, do: x = 2); IO.inspect x" 2> /dev/null
2
~/foo% asdf local elixir 1.7.0 && elixir -e "x = 1; if(true, do: x = 2); IO.inspect x" 2> /dev/null
1
```

**Comment by fertapric** [comment] 2018-08-13 09:37
🤔 That's odd! 

Before posting, I checked the warning was there using this small example:

```elixir
params = %{}

if true do
  params = Map.put_new(params, :email, 1)
end

IO.inspect params
```

The warning was emitted for the assignment in the line 4 :)

**Comment by wojtekmach** [comment] 2018-08-13 09:39
@fertapric I got the warning in both cases as expected, I removed it with `2> /dev/null` for brevity.

**Comment by josevalim** [comment] 2018-08-13 11:53
Duplicate of #7403.

Rationale is here:
https://github.com/elixir-lang/elixir/issues/7403#issuecomment-368902698

We should have a CHANGELOG entry too. But I will be glad to clarify it.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jfayad** [comment] 2018-08-13 13:06
Thanks for the clarification @josevalim indeed updating the changelog would have saved us (and probably others) some precious time searching for the reason behind these errors.

**Comment by josevalim** [comment] 2018-08-13 13:09
Julien, sorry for not being clear. I meant that this is already in the
CHANGELOG but apparently not clear enough. Could you please give it a
second pass and suggest how should we change the CHANGELOG to make this
clearer?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by jfayad** [comment] 2018-08-13 13:15
@josevalim I'll be glad to suggest but after I've made a CTRL+F of the following terms:
- Imperative
- Variable
- leak
- if
on this page: https://github.com/elixir-lang/elixir/releases/tag/v1.7.0

I couldn't find anything relevant.
If a line is there, can you please point me to it?

**Comment by josevalim** [comment] 2018-08-13 13:55
I think adding “also known as imperative assignment” to that entry could be
enough. Thoughts?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by jfayad** [comment] 2018-08-13 14:49
I would definitely add the key expression Imperative assignment. So adding to the end of the sentence "and stop leaking Imperative assignment variables to the upper context"

**Comment by josevalim** [comment] 2018-08-14 11:05
Updated, thanks everyone for the feedback!

**Closed by josevalim** 2018-08-14 11:05 UTC

**Comment by adrianomitre** [comment] 2020-06-03 17:13
This breaking change on the Elixir led to this [erratum](https://pragprog.com/titles/elixir16/errata#row-86784) on Programming Elixir 1.6 book by Dave Thomas.
