### ISSUE TITLE
Inconsistent parens behaviour on TypeSpecs when formatting. 

### ISSUE THREAD

**Issue by seivan** [elixir-lang/elixir#7490] opened 2018-03-26 15:33 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 20)
```

* Operating system: 

```
macOS High Sierra 10.13.3 (17D102)
```

### Current behavior

Formatter assigns parens to typespecs in an inconsistent manner. My guess is it makes no distinction between functions and typespec and if something looks like a function it gets parens. 
```elixir
  @spec new(Point.t, Size.t) :: t
```
becomes
```elixir
  @spec new(Point.t(), Size.t()) :: t
```

### Expected behavior

Either don't add parens at all to specs (my preference!) or be consistent

```elixir
  @spec new(Point.t, Size.t) :: t
```
or

```elixir
  @spec new(Point.t(), Size.t()) :: t()
```

**Comment by josevalim** [comment] 2018-03-26 15:45
Duplicate of #7401. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Closed** 2018-03-26 15:50 UTC

**Comment by seivan** [comment] 2018-03-26 16:03
This answers the question https://github.com/elixir-lang/elixir/issues/7401#issuecomment-368804268
