### ISSUE TITLE
IEx and pipes ergonomics

### ISSUE THREAD

**Issue by thbar** [elixir-lang/elixir#11418] opened 2021-11-25 15:43 UTC
### Precheck

This follows a discussion on the Elixir Core mailing list: https://groups.google.com/g/elixir-lang-core/c/r4_KRdNrjwk

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

* Operating system: Mac OS Big Sur (11.6)

### Current behavior

A coworker (new to Elixir) was quite surprised today when pasting this code into IEx:

```elixir
import Ecto.Query

a = DB.Resource
  |> where([r], not is_nil(r.datagouv_id))
  |> group_by([r], r.datagouv_id)
  |> having([r], count(r.datagouv_id) > 1)
  |> select([r], r.datagouv_id)
  |> DB.Repo.all()
```

The output appears to do exactly what one would hope for, thanks to [Elixir 1.12.0 paste code with pipelines support](https://elixir-lang.org/blog/2021/05/19/elixir-v1-12-0-released/#iex-improvements):

```elixir
iex(1)> import Ecto.Query
Ecto.Query
iex(2)> a = DB.Resource
DB.Resource
iex(3)>   |> where([r], not is_nil(r.datagouv_id))
#Ecto.Query<from r0 in DB.Resource, where: not(is_nil(r0.datagouv_id))>
iex(4)>   |> group_by([r], r.datagouv_id)
#Ecto.Query<from r0 in DB.Resource, where: not(is_nil(r0.datagouv_id)),
 group_by: [r0.datagouv_id]>
iex(5)>   |> having([r], count(r.datagouv_id) > 1)
#Ecto.Query<from r0 in DB.Resource, where: not(is_nil(r0.datagouv_id)),
 group_by: [r0.datagouv_id], having: count(r0.datagouv_id) > 1>
iex(6)>   |> select([r], r.datagouv_id)
#Ecto.Query<from r0 in DB.Resource, where: not(is_nil(r0.datagouv_id)),
 group_by: [r0.datagouv_id], having: count(r0.datagouv_id) > 1,
 select: r0.datagouv_id>
iex(7)>   |> DB.Repo.all()
[debug] QUERY OK source="resource" db=7.5ms queue=1.8ms idle=1231.3ms
SELECT r0."datagouv_id" FROM "resource" AS r0 WHERE (NOT (r0."datagouv_id" IS NULL)) GROUP BY r0."datagouv_id" HAVING (count(r0."datagouv_id") > 1) []
["a33d3831-8dd0-4a60-95df-66b9b8f3d86d", "ec23d4d9-2347-4f96-9674-163d628d6729",
 "d066b629-8b19-47e0-8898-8286114cfb6f", "099f7d00-bdc7-434b-ae4f-8d9d5f5585dc"]
iex(8)>
```

At this point, the POLS is not broken.

But if one starts playing with `a`, comes some confusion:

```elixir
iex(8)> a |> List.first
** (FunctionClauseError) no function clause matching in List.first/2    
    
    The following arguments were given to List.first/2:
    
        # 1
        DB.Resource
    
        # 2
        nil
     
    Attempted function clauses (showing 2 out of 2):
    
        def first([], default)
        def first([head | _], _default)
    
    (elixir 1.12.2) lib/list.ex:287: List.first/2
```

This is because actually, `a` is not equal to what we have pasted, but instead the assignment is done at the first line only, so:

```elixir
iex(8)> a
DB.Resource
```

This makes the user wonder if the result is actually a special aggregated type due to `select` (like it can happen for some ORMs), or something else happened.

### Expected behavior

My coworker was expecting `a` to contain the actual result of the full pipeline.

**Comment by maennchen** [comment] 2021-11-25 15:49
I would also expect, that code pasted into iex behaves as close as possible to code in a file. Therefore this should be how iex should behave:

```elixir
iex> a = 1
1
iex> |> Kernel.+(1)
2
iex> a
2
```

**Comment by maennchen** [comment] 2021-11-25 15:55
After seeing this question on slack (https://elixir-lang.slack.com/archives/C087B66BY/p1637766368437300), I tried to write a test and maybe even a fix for it:

```diff
diff --git a/lib/iex/test/iex/interaction_test.exs b/lib/iex/test/iex/interaction_test.exs
index a5566b01e..81f0bd958 100644
--- a/lib/iex/test/iex/interaction_test.exs
+++ b/lib/iex/test/iex/interaction_test.exs
@@ -204,6 +204,15 @@ test "malformed .iex", %{tmp_dir: tmp_dir} do
     end
   end
 
+  test "does re-assignment in pipe" do
+    input = """
+    a = 1
+    |> Kernel.+(1)
+    a
+    """
+    assert capture_iex(input, []) == "1\n2\n2"
+  end
+
   defp write_dot_iex!(tmp_dir, name, contents) do
     path = Path.join(tmp_dir, name)
     File.write!(path, contents)
```

But it seems as if the IEX tests can't deal with pipes at all even without variable bindings:

```
  1) test does re-assignment in pipe (IEx.InteractionTest)
     test/iex/interaction_test.exs:207
     Assertion with == failed
     code:  assert capture_iex(input, []) == "1\n2\n2"
     left:  "1\n** (SyntaxError) iex:2:1: syntax error before: '|>'\n\n1"
     right: "1\n2\n2"
     stacktrace:
       test/iex/interaction_test.exs:213: (test)
```

**Comment by Qqwy** [comment] 2021-11-25 15:58
When you describe the situation like this, it almost seems that it would be preferable if IEx would display an error if a line starting with a `|>` was entered, telling the person to paste a multi-line snippet inside parentheses.

**Comment by maennchen** [comment] 2021-11-25 16:04
@Qqwy That would make it harder to paste things into IEx. I think rebinding the variable would be more user-friendly.

A warning would be better for sure than producing a different output depending on if it is IEx or in a file.

**Comment by ericmj** [comment] 2021-11-25 16:22
It will be impossible to make IEx work exactly like code in a file because it doesn't know if you will pipe further:

```
iex> a = 1
iex> a = a
iex> |> Kernel.+(a)
iex> |> Kernel.+(a)
```

In code in a file you would have `a == 3` but with your proposal it would be `a == 4` in IEx.

**Comment by am-kantox** [comment] 2021-11-29 05:42
What we actually can do to avoid magic and still preserve a pipeline, would be to insert the actual content of the previous line instead of the result when the new line starts with a pipe.
```elixir
iex|1> foo = 42
42
iex|2> |> Kernel.+(3) # → foo = 42 |> Kernel.+(3) instead of v() |> Kernel.+(3)
45
```

**Comment by v0idpwn** [comment] 2021-11-29 06:07
@am-kantox the issue I see there is that it doesn't work well with non-pure functions. For example:

```elixir
foo = Enum.random(1..100)
#> 42
|> Kernel.+(3) # -> another result of Enum.random/1 + 3
```

**Comment by am-kantox** [comment] 2021-11-29 10:53
@v0idpwn well, technically `56` is a correct expectation in this case. One might go with 
```elixir
iex|1> foo = Enum.random(1..100)
42
iex|2> foo
42
iex|3> |> Kernel.+(3)
45
```
to preserve a seed. I think it’s still less frustrating to the end user compared to
```elixir
iex|1> foo = Enum.random(1..100)
42
iex|2> |> Kernel.+(3)
45
iex|3> |> foo
42
```
but I am not sure. REPL has a short memory in all the languages I am aware of, hence even the current behaviour looks fine to me, I was just throwing in ideas.

**Comment by josevalim** [comment] 2021-11-29 10:59
This approach doesn't work when the left side of `=` is a pattern and the correct pattern only comes at the end of the pipeline.

**Comment by am-kantox** [comment] 2021-11-29 12:17
Well, to some extent it indeed does work.
```elixir
iex|1 ▸ {:ok, _} = 42
** (MatchError) no match of right hand side value: 42

iex|1 ▸ |> then(&{:ok, &1}) # → {:ok, _} = 42 |> then(&{:ok, &1})
{:ok, 42}
```

**Comment by josevalim** [comment] 2021-12-02 23:05
Yes, so we have two options:

1. Detect that we have a match and then perform pattern matching on each step of the pipeline. You will get errors but it should work at the end.

2. Remove the feature altogether.

I am thinking 1 is the way to go. Thoughts?

**Comment by achempion** [comment] 2021-12-03 04:46
Can we just introduce additional wrapper instead? 

If you want to paste multiline command, you either have to indicate it explicitly (by switching shell into multiline mode, maybe even with some kind of editing possibilities) or simply wrap it with a sigil, i.e. type `> ~eval(`, hit enter, paste your multiline command, type `> )`.

**Comment by am-kantox** [comment] 2021-12-03 07:00
@achempion we already have parentheses for that. Simply wrap a multiline command into parentheses (type a parenthesis, then paste a multiline command and close parenthesis.)

@josevalim Could you please elaborate on why would we need to detect a match? In my understanding, that might bring unexpected inconsistencies, even if not now then in the future. I’d personally go with changing the current implementation that basically inserts `v()` to insert the whole content of the previous line. `v()` is not hard to type anyway if anyone wants to avoid time-consuming re-evaluation of the previous command.

**Comment by josevalim** [comment] 2021-12-03 07:12
> In my understanding, that might bring unexpected inconsistencies

can you please give examples?

**Comment by am-kantox** [comment] 2021-12-03 07:23
Yes, the aforementioned non-pure function. I found it inconsistent that in the case of no match
```elixir
iex|1> Enum.random([1,2,3,4,5])
3
iex|2> |> ...
```
the pipe in the latter line _always_ gets the result of a single evaluation (e. g. `3`,) but in a slightly changed
```elixir
iex|1> x = Enum.random([1,2,3,4,5])
3
iex|2> |> ...
```
the first argument to a pipe in `iex|2` might be whatever.

**Comment by josevalim** [comment] 2021-12-03 07:26
Right, if we change v(), then it is reevaluated and you will get the different results. My proposal is to rewrite:

    a = exrp1
    |> expr2

As:

    a = v(-1) |> expr2

I believe that's the best option so far. You don't get reevaluation of side-effects but you still reassign to a variable. The only downside is that you may get failures along the way.

**Comment by am-kantox** [comment] 2021-12-03 07:41
Ah, right, now I get it. Yes, 👍🏼.

**Comment by am-kantox** [comment] 2021-12-03 07:42
@josevalim I can work on the PR if everyone agrees on that proposal.

**Comment by josevalim** [comment] 2021-12-03 07:55
Yes, please do send a PR. In the worst case we merge it and remove the whole implementation later. But I would say that would be the most complete version of the implementation.

**Comment by josevalim** [comment] 2021-12-03 07:57
Actually I just realized that this pipeline would still be wrong:

    x = 1
    x = 2
    |> Kernel.*(x)

**Comment by josevalim** [comment] 2021-12-03 07:58
The best I think is to detect the use of = and then don’t allow the pipeline to be used right after.

**Comment by am-kantox** [comment] 2021-12-03 08:01
Maybe. It would also fix the non-expected behaviour when a match exception has been raised but the pipeline worked afterward despite it.

**Comment by josevalim** [comment] 2021-12-03 08:23
Yeah, so detecting and raising is the way to go. We can have a good error message telling them to write the pipeline between parens.

**Closed** 2021-12-03 19:24 UTC
Labels: Note:Discussion, App:IEx

**Comment by thbar** [comment] 2021-12-04 09:28
Just wanted to thank everyone involved - I must say I like the outcome of this since it restores the POLS. Thanks for your care about this!
