### ISSUE TITLE
Bug with String.length/1 and String.slice/2?

### ISSUE THREAD

**Issue by allanegidio** [elixir-lang/elixir#12154] opened 2022-09-26 14:43 UTC
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.13.1 (compiled with Erlang/OTP 24)

### Operating system

POP OS 22.04 LTS

### Current behavior

Hello.
I have a HTML text and I want to get a summary with the first 255 characters. This value should be stored in a varchar(255) column in postgres. However when I try to save this string, I get an Error because even though Elixir counts 255 caracteres, this text's lenght is actually 256 characters.

```elixir
short_description =
        description
        |> Floki.parse_document!()
        |> Floki.text()
        |> String.slice(0..254)
```

Elixir: 
```elixir
text = "O Olympikus Eros é um tênis clássico que nunca sai de moda, ideal para quem busca mais estilo e conforto para o dia a dia. O seu solado é feito em TR monocolor. Já o cabedal é confeccionado em sintético com detalhes na costura que modernizam o estilo casu"

String.graphemes(text) |> Enum.count # => 255
String.length(text) # => 255
byte_size(text) # => 263
```

How other languages counts this text:

Javascript:
```javascript
let text = "O Olympikus Eros é um tênis clássico que nunca sai de moda, ideal para quem busca mais estilo e conforto para o dia a dia. O seu solado é feito em TR monocolor. Já o cabedal é confeccionado em sintético com detalhes na costura que modernizam o estilo casu"
text.length // => 256
```

Ruby
```ruby
text = 'O Olympikus Eros é um tênis clássico que nunca sai de moda, ideal para quem busca mais estilo e conforto para o dia a dia. O seu solado é feito em TR monocolor. Já o cabedal é confeccionado em sintético com detalhes na costura que modernizam o estilo casu'
puts text.grapheme_clusters.length # => 255
puts text.length # => 256
```

### Expected behavior

I know that Elixir counts graphemes but why other languages counts 256 characters?
What's the best way to solve this problem I'm having?

**Comment by ericmj** [comment] 2022-09-26 15:13
> I know that Elixir counts graphemes but why other languages counts 256 characters?

The other languages seem to count codepoints instead of graphemes. Counting by graphemes is better, the character `é` should be counted as a single character regardless if it's represented with one or two codepoints. So I would say Elixir counts what most people think a character is, while Javascript and Ruby counts codepoints and multiple codepoints can be combined to a single character.

> What's the best way to solve this problem I'm having?

You can do `text |> String.codepoints |> Enum.take(255) |> Enum.join()` but there's a risk that if the last character is made of multiple codepoints that it will be split. More accurate would be something like this:

```elixir
Enum.reduce_while(String.graphemes(text), {"", 0}, fn grapheme, {text, codepoints} ->
  codepoints = codepoints + length(String.codepoints(grapheme))

  if codepoints > 255 do
    {:halt, {text, codepoints}}
  else
    {:cont, {text <> grapheme, codepoints}}
  end
end)
|> elem(0)
```

It can probably be optimized by using iolists and `String.next_grapheme/1` / `String.next_codepoint/1`.

**Comment by ericmj** [comment] 2022-09-26 15:13
Closing as this is intended behavior.

**Closed by ericmj** 2022-09-26 15:13 UTC

**Comment by kipcole9** [comment] 2022-09-26 17:23
`String.length/1` will correctly return the length of the string in graphemes which it the correct answer (in the Unicode sense of correct).

For many characters there are multiple encodings, especially characters in the Latin-1 script.  You will need to normalise the input string if you want to ensure a given string always returns the same number of code points.   Typically using the `:nfc` normal form but in more specialised cases `:nfkc`.

**Comment by allanegidio** [comment] 2022-09-26 18:22
> `String.length/1` will correctly return the length of the string in graphemes which it the correct answer (in the Unicode sense of correct).
> 
> For many graphemes there are multiple encodings, especially characters in the Latin-1 script (and especially the accented ones as you note).
> 
> You will need to normalise the input if you want to ensure a given string always returns the same number of code points. Typically using the `:nfc` normal form but in more specialised cases `:nfkc`. See `String.normalize/2`.

String.normalize/2 solved my problem. Thank you!
