### ISSUE TITLE
Can't run "deps.get", "deps.compile" and "compile" in same alias

### ISSUE THREAD

**Issue by michaelkschmidt** [elixir-lang/elixir#7059] opened 2017-11-22 18:08 UTC
We would like to have an alias that completely builds the app:

```elixir
defp aliases do
    [
       "build": [
          "deps.get",
          "deps.compile",
           "compile"
      ],
    ]
end
```

However we get an error:
```
Unchecked dependencies for environment dev:
...
** (Mix) Can't continue due to errors on dependencies
```

The equivalent Makefile works, however:
```make
get_deps:
	mix deps.get

compile_deps:
	mix deps.compile 

compile_source:
	mix compile

build: get_deps compile_deps compile_source
```

I tried adding a "loadconfig" to the alias after "deps.get".  It seems to help, but as dependencies change the bug returns.

Any ideas on what causes this?  The "unchecked dependencies" were in fact fetched, but not compiled

**Comment by josevalim** [comment] 2017-11-22 18:48
I tried it no master and I can't reproduce the error in the plug project, even after a removing _build and deps directory. Can you please provide a sample app that reproduces the error?

**Comment by josevalim** [comment] 2017-11-28 14:22
Closing this. If you have a mechanism to reproduce, please let us know.

**Closed by josevalim** 2017-11-28 14:22 UTC
Labels: Note:Needs more info
